### ISSUE TITLE
Job Point Implementation Tracker

### ISSUE THREAD

**Issue by claywar** [DerpyProjectGroup/topaz#13]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/DerpyProjectGroup/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/DerpyProjectGroup/topaz/blob/info/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: jp

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
## Packets
- [x] Job Point Flag
- [x] Job Point Menu
- [x] Job Point Details
- [x] Job Point Spent
- [x] BLU Spell Point Increase Support
- [x] Capacity Points Increase
- [x] Job Point Animation
- [x] Add Method for acquiring spells from JP Gifts

## Database
- [x] Character Job Points Table
- [x] Job Point Gifts Table

## Capacity Points
- [x] Capacity Points Server Multiplier
- [x] Add Capacity Points
- [x] Capacity Points Mod Bonus

### WAR
- [x] Mighty Strike Effect
- [x] Brazen Rush Effect (Using Mighty Strikes Animation)
- [x] Berserk Effect
- [x] Defender Effect
- [x] Warcry Effect
- [x] Aggressor Effect
- [ ] Retaliation Effect
- [ ] Restraint Effect
- [ ] Blood Rage Effect
- [ ] Double Attack Effect
### MNK
- [x] Hundred Fists Effect
- [ ] Inner Strength Effect
- [x] Dodge Effect
- [x] Focus Effect
- [x] Chakra Effect
- [x] Counterstance Effect
- [x] Footwork Effect
- [ ] Perfect Counter Effect
- [ ] Impetus Effect
- [ ] Kick Attack Effect
### WHM
- [ ] Benediction Effect
- [ ] Asylum Effect
- [ ] Divine Seal Effect
- [x] Magic Accuracy Bonus
- [ ] Afflatus Solace Effect
- [ ] Afflatus Misery Effect
- [ ] Divine Caress Duration
- [ ] Sacrosanctity Effect
- [x] Regen Duration
- [x] Bar Spell Effect
### BLM
- [x] Manafont Effect
- [x] Subtle Sorcery Effect
- [ ] Elemental Seal Effect
- [x] Magic Burst Damage Bonus
- [ ] Mana Wall Effect
- [x] Magic Accuracy Bonus
- [ ] Emnity Douse Recast
- [x] Manawell Effect
- [ ] Magic Burst Emnity Bonus
- [x] Magic Damage Bonus
### RDM
- [x] Chainspell Effect
- [x] Stymie Effect
- [x] Convert Effect
- [x] Magic Accuracy Bonus
- [x] Composure Effect
- [x] Magic Attack Bonus
- [x] Saboteur Effect
- [x] Enfeeble Duration
- [x] Quick Magic Effect
- [x] Enhancing Duration
### THF
- [x] Perfect Dodge Effect
- [ ] Larceny Effect
- [x] Sneak Attack Effect
- [x] Trick Attack Effect
- [x] Steal Recast
- [x] Mug Effect
- [x] Despoil Effect
- [x] Conspirator Effect
- [x] Bully Effect
- [ ] Triple Attack Effect
### PLD
- [x] Invincible Effect
- [ ] Intervene Effect
- [ ] Holy Circle Effect
- [ ] Sentinel Effect
- [x] Shield Bash Effect
- [x] Cover Duration
- [ ] Divine Emblem Effect
- [ ] Sepulcher Duration
- [ ] Palisade Effect
- [x] Enlight Effect
### DRK
- [x] Blood Weapon Effect
- [ ] Soul Enslavement Effect
- [ ] Arcane Circle Effect
- [x] Last Resort Effect
- [x] Souleater Duration
- [x] Weapon Bash Effect
- [ ] Nether Void Effect
- [ ] Arcane Crest Duration
- [ ] Scarlet Delirium Duration
- [x] Endark Effect
### BST
- [ ] Familiar Effect
- [ ] Unleash Effect
- [ ] Pet Accuracy Bonus
- [ ] Charm Success Rate
- [ ] Reward Effect
- [ ] Pet Attack Speed Bonus
- [ ] Ready Effect
- [ ] Spur Effect
- [ ] Run Wild Duration
- [ ] Pet Emnity Bonus
### BRD
- [x] Soul Voice Effect
- [ ] Clarion Call Effect
- [x] Minne Effect
- [x] Minuet Effect
- [x] Pianissimo Effect
- [ ] Song Accuracy Bonus
- [x] Tenuto Effect
- [x] Lullaby Duration
- [x] Marcato Effect
- [x] Requiem Effect
### RNG
- [x] Eagle Eye Shot Effect
- [ ] Overkill Effect
- [x] Sharpshot Effect
- [x] Camouflage Effect
- [x] Barrage Effect
- [x] Shadowbind Duration
- [x] Velocity Shot Effect
- [x] Double Shot Effect
- [ ] Decoy Shot Effect
- [x] Unlimited Shot Effect
### SAM
- [x] Meikyo Shisui Effect
- [ ] Yaegasumi Effect
- [x] Warding Circle Effect
- [x] Hasso Effect
- [x] Meditate Effect
- [x] Seigan Effect
- [ ] Konzen-Ittai Effect
- [x] Hamanoha Duration
- [x] Hagakure Effect
- [ ] Zanshin Effect
### NIN
- [x] Mijin Gaukure Effect
- [x] Mikage Effect
- [x] Yonin Effect
- [x] Inin Effect
- [x] Ninjitsu Accuracy Bonus
- [x] Ninjitsu Cast Time Bonus
- [x] Futae Effect
- [x] Elemental Ninjitsu Effect
- [x] Issekigan Effect
- [ ] Tactical Parry Effect
### DRG
- [x] Sprit Surge Effect
- [ ] Fly High Effect
- [x] Ancient Circle Effect
- [ ] Jump Effect
- [x] Spirit Link Effect
- [x] Wyvern Max HP Bonus
- [ ] Dragon Breaker Duration
- [ ] Wyvern Breath Effect
- [ ] High Jump Effect
- [ ] Wyvern Attribute Bonus
### SMN
- [x] Astral Flow Effect
- [ ] Astral Conduit Effect
- [x] Summon Accuracy Bonus
- [x] Summon Magic Accuracy Bonus
- [ ] Elemental Siphon Effect
- [x] Summon Physical Attack Bonus
- [ ] Mana Cede Effect
- [ ] Avatars Favor Effect
- [x] Summon Magic Damage Bonus
- [x] Blood Pact Damage Bonus
### BLU
- [ ] Azure Lore Effect
- [x] Unbridled Wisdom Effect
- [x] Blue Magic Point Bonus
- [ ] Burst Affinity Bonus
- [ ] Chain Affinity Effect
- [ ] Blue Physical Add. Effect Bonus
- [ ] Unbridled Learning Effect
- [ ] Unbridled Learning Effect II
- [ ] Efflux Effect
- [ ] Blue Magic Accuracy Bonus
### COR
- [ ] Wild Card Effect
- [ ] Cutting Cards Effect
- [x] Phantom Roll Effect
- [ ] Bust Evasion
- [x] Quick Draw Effect
- [x] Ammo Consumption
- [ ] Random Deal Effect
- [ ] Ranged Accuracy Bonus
- [x] Triple Shot Effect
- [ ] Optimal Range Bonus
### PUP
- [x] Overdrive Effect
- [ ] Heady Artifice Effect
- [x] Automation HP MP Bonus
- [x] Activate Effect
- [ ] Repair Effect
- [x] Deus Ex Automata Recast
- [ ] Tactical Switch Bonus
- [x] Cooldown Effect
- [ ] Deactivate Effect
- [ ] Martial Arts Effect
### DNC
- [x] Trance Effect
- [ ] Grand Pas Effect
- [x] Step Duration
- [x] Samba Duration
- [ ] Waltz Potency Bonus
- [x] Jig Duration
- [x] Flourish I Effect
- [ ] Flourish II Effect
- [ ] Flourish III Effect
- [ ] Contradance Effect
### SCH
- [x] Tabula Rasa Effect
- [ ] Caper Emmissarius Effect
- [ ] Light Arts Effect
- [x] Dark Arts Effect
- [x] Strategem Effect I
- [x] Strategem Effect II
- [ ] Strategem Effect III
- [ ] Strategem Effect IV
- [x] Modus Veritas Effect
- [x] Sublimation Effect
### GEO
- Skipping. Not Implemented.
### RUN
See #1340 

### Shared
- [x] Capacity Points Bonus
- [x] Superior Levels
- [x] Master Stars
- [x] /jobmasterdisp on/off
- [x] Master Bonus (1hr reduction)
- [ ] Master Titles
- [x] General Stat Increases
### WAR
- [x] No new traits/spells/abilities
### MNK
- [ ] COUNTER_DAMAGE
### WHM
- [x] REGEN_BONUS
- [ ] New Spells
### BLM
- [ ] New Spells
### RDM
- [ ] New Spells
### THF
- [ ] MAX_TREASURE_HUNTER
- [ ] TREASURE_HUNTER_PROC
### PLD
- [ ] PROTECT_EFFECT
- [ ] REPRISAL_EFFECT
- [ ] New Spells
### DRK
- [x] DREAD_SPIKES_EFFECT (%Health Increase)
- [ ] New Spells
### BST
- [ ] SIC_READY_RECAST
- [ ] PET_ATK_DEF
- [ ] PET_ACC_EVA
- [ ] PET_TP_BONUS
### BRD
- [x] New Spells
### RNG
- [ ] VELOCITY_SHOT_DELAY
- [ ] TRUE_SHOT_DMG (also COR)
- [ ] DEAD_AIM_CRIT_DMG
- [ ] BARRAGE_BONUS
### SAM
- [ ] HASSO_SEIGAN_ZANSHIN_CAP
- [ ] THIRD_EYE_EVASIONS
### NIN
- [x] NINJUTSU_DURATION (Placeholder, not utilized)
- [x] Utsusemi: San (100 JP Gift)
### DRG
- [ ] WYVERN_ATTR_DBLATK
- [ ] WYVERN_BREATH_DELAY
### SMN
- [x] No new traits/spells/abilities
### BLU
- [ ] BLUE_TRAIT_BONUS
- [ ] BLUE_MAGIC_ATTR_POTENCY
### COR
- [ ] QUICK_DRAW_DELAY
### PUP
- [x] AUTO_ELEM_CAPACITY
### DNC
- [x] MAX_FINISHING_MOVE_BONUS (Placeholder exists, needs refactoring)
### SCH
- [ ] STRATAGEM_RECAST
- [ ] New spells
### GEO
-- Skipping. Not Implemented.
- HANDBELL
- GEOMANCY
### RUN
See #1340

### All Pet Jobs
- [x] PET_ATK_DEF (not for BST)
- [x] PET_ACC_EVA (not for BST)
- [x] PET_MAB_MDB
- [x] PET_MACC_MEVA

**Comment by dynisor** [comment]
Thanks for taking this over @claywar ❤️

**Comment by claywar** [comment]
Note from testing: Capacity chain time needs more research for Chain1~30

**Comment by RAIST5150** [comment]
Not going to create a new issue for this just yet... will do if requested.

BLM "learned" Aspir III after spending the job points (it shows in the spell list), but it cannot cast it (gives yellow text... unable to cast)

Guessing it may be like the RDM elemental spells gift where the job is not included in the core jobs bitmask for the spell and needs an alternate means of integration in order to be able to cast it?

**Comment by WinterSolstice8** [comment]
>Guessing it may be like the RDM elemental spells gift where the job is not included in the core jobs bitmask for the spell and needs an alternate means of integration in order to be able to cast it?

That's the same problem. Thanks for reminding me of that, it's somewhere in my backlog. I have an idea of how to implement it already and it's going to be hooked up to lua for module overrides.

**Comment by WinterSolstice8** [comment]
So it turns out Aspir III isn't implemented and doesn't have a lua, but I made a PR to properly check for job point gift levels to enable use if Aspir III is implemented, see #2693
