### ISSUE TITLE
Rune Fencer Completeness tracking

### ISSUE THREAD

**Issue by WinterSolstice8** [DerpyProjectGroup/topaz#1340]
This is an issue to track the progress and needed data/functionality/formulae to finish Rune Fencer.

Contributors to this tracker:
@Xaver-DaRed, @WinterSolstice8, @helixhamin, an unknown contributor who originally added the item mods to some Runefencer gear that made their way to LSB

Open issues relating to Rune Fencer:
#2365

Closed issues relating to Rune Fencer:
#1434

Merged PRs
#1321 
#1333 
#1353
#1339 
#1371
#1388
#1414
#1442
#1444
#1469
#1536
#1545
#1552
#1558
#1759
#1765
#1781
#1878
#1896
#2202
#2206 
#2693
#5802
#3258
#5901
Open PRs:

The following tables are representative of the WIP PRs once they are merged as well as the previous merges.

| Job Ability        | Level      | Implemented? | Notes                                                                                                                                     |
|--------------------|------------|--------------|-------------------------------------------------------------------------------------------------------------------------------------------|
| Elemental Sforzo   | 1          | Partial      | Magic damage nulled, but statuses not nulled + verify claim.    Verify magic damage nulled from pet damage or other misc sources                                                                                      |
| Rune Enchantment   | 5          | Yes    |                  |
| Vallation          | 10         | Yes           |                                                                                                                                           |
| Swordplay          | 20         | Partial      | Complete, other than “until you take severe damage.” Implementing that would also enable Migawari, Earthen Armor and Scherzo to function. |
| Swipe              | 25         | Yes          |                                                                                                                                   |
| Lunge              | 25         | Yes         |                                                                                                                                        |
| Pflug              | 40         | Mostly           |  Status  effect resisting, merits, non-RUN main job penalty implemented. Pflug+ gear (activates when worn) not implemented.  |
| Valiance           | 50         | Yes           |                                                                                                                                           |
| Embolden           | 60         | Mostly           | Verify what if any status effects don't consume embolden. Pet blinkga/hastega is known to not consume but player blink is.                                                                                                                                           |
| Vivacious Pulse    | 65         | Yes      |                                                                                                                                           |
| Gambit             | 70         | Yes           |                                                                                                                                           |
| Battuta            | 75 (Merit) | Yes           |                                                                                                                                           |
| Rayke              | 75 (Merit) | Yes         |                                                                                                                                     |
| Liement            | 85         | Yes*           |  *  Certain sources of elemental breath damage not yet accounted for.                                                                                                                                        |
| One for All        | 95         | Yes           |                                                                                                                                          |
| Odyllic Subterfuge | 96         | No           |                                                                                                                                           |

| Job Trait           | Level(s)                   | Implemented? | Notes                                                                                                                 |
|---------------------|----------------------------|--------------|-----------------------------------------------------------------------------------------------------------------------|
| Tenacity            | 5,25,45,75,80/85           | Mostly          | It seems the trait is piggybacking off several “Resist X” traits with duplicate entries. Cleanup? Seems to be missing Resist Curse/Resist Charm (verified on retail) |
| Magic Defense Bonus | 10,12,14,16,18,20,22       | Yes          |                                                                                                                       |
| Inquartata          | 15,45,75,90,99(Job Points) | Yes          | Not all gifts tested. Need parse data to verify.                                                                      |
| Auto Regen          | 35, 65, 95                 | Yes          |                                                                                                                       |
| Tactical Parry      | 40, 60, 85                 | Yes          |                                                                                                                       |
| Accuracy Bonus      | 50, 70, 90                 | Yes          |                                                                                                                       |
| Inspiration         | 75 (Merit)                 | Yes           |                                                       |
| Sleight of Sword    | 75 (Merit)                 | Yes          |                                                                                                                       |

Note: Job Point categories and gifts appear to be enabled, and are only considered implemented when tested
| Job Point                   | Level          | Implemented? | Notes |
|-----------------------------|----------------|--------------|-------|
| Elemental Sforzo Effect     | 99 (Job Point) | No           |       |
| Odyllic Subterfuge Effect   | 99 (Job Point) | No           |       |
| Rune Enchantment Effect     | 99 (Job Point) | Yes          |       |
| Vallation Duration          | 99 (Job Point) | Yes           |       |
| Swordplay Effect            | 99 (Job Point) | Yes          |       |
| Swipe Effect                | 99 (Job Point) | Yes           |       |
| Embolden Effect             | 99 (Job Point) | Yes           |       |
| Vivacious Pulse             | 99 (Job Point) | Yes          |       |
| One for All Effect Duration | 99 (Job Point) | Yes           |       |
| Gambit Effect Duration      | 99 (Job Point) | Yes           |       |

List incomplete
| Gifts              | Level          | Implemented? | Notes                                            |
|--------------------|----------------|--------------|--------------------------------------------------|
| Inquartata Effect  | 99 (Job Point) | Yes          | Tested only via “!getmod”. Need parse to verify  |
| Temper             | 99 (Job Point) | Yes     |  |

| Spells  | Level          | Implemented? | Notes                                                 |
|---------|----------------|--------------|--------------------------------------------------|
| Foil    | 58             | Yes           | |
| Temper  | 99 (Job Point) | Yes     |  |
| Crusade | 88             | Yes           |                |

| RUN JSE item mods| Implemented? | Notes                                                 |
|--------------------|----------------|--------------|
|AF|No||
|Relic|No||
|Empyrean|No||
|JSE Capes|No||
|Epeolatry (Ergon weapon)|Partial|, ilvl 119 III version implemented|

- [ ] RUN genkai quest

Misc:
- [ ] Verify all new statuses dispellable/erasable conditions in Brenner (or from a colibri)
- [ ] Verify which abilities can or cant be used in combat (Rayke needs your weapon out)

And finally:
RUN specific job WS, Dimidiation
- [X] Implement Dimidiation
- [ ] Implement Dimidiation job quest (need caps)
- [ ] Ergon Aftermath (currently using Mythic AM equivalent)

**Comment by zach2good** [comment]
Nice tracking issue 👍

**Comment by helixhamin** [comment]
Here is a handy list of all the RUN specific gear. I will update it as I either verify or add the gear, and check off those that are addressed for the above list. Incomplete (Missing modifiers due to not implemented) will not be checked off, but will have a note on their status below.

Note: This does not show completeness of method of obtaining, only completeness of the JSE itself.

- [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
  - [ ] [Runeist Armor Set](https://www.bg-wiki.com/ffxi/Runeist_Armor_Set)
    - [ ] [Runeist Bandeau](https://www.bg-wiki.com/ffxi/Runeist_Bandeau) Not created yet in item_mods
    - [x] [Runeist Coat](https://www.bg-wiki.com/ffxi/Runeist_Coat)
    - [ ] [Runeist Mitons](https://www.bg-wiki.com/ffxi/Runeist_Mitons) Not created yet in item_mods
    - [ ] [Runeist Trousers](https://www.bg-wiki.com/ffxi/Runeist_Trousers) Missing Enh. res. to all status ailments. Other mods are complete.
    - [x] [Runeist Bottes](https://www.bg-wiki.com/ffxi/Runeist_Bottes)
  - [ ] [Beorc Sword](https://www.bg-wiki.com/ffxi/Beorc_Sword) Not created yet in item_mods
  - [ ] [Runeist Armor Set +1](https://www.bg-wiki.com/ffxi/Runeist_Armor_Set_%2B1)
    - [ ] [Runeist Bandeau +1](https://www.bg-wiki.com/ffxi/Runeist_Bandeau_%2B1) Not created yet
    - [x] [Runeist Coat +1](https://www.bg-wiki.com/ffxi/Runeist_Coat_%2B1) 
    - [ ] [Runeist Mitons +1](https://www.bg-wiki.com/ffxi/Runeist_Mitons_%2B1) Not created yet in item_mods
    - [ ] [Runeist Trousers +1](https://www.bg-wiki.com/ffxi/Runeist_Trousers_%2B1) Not created yet in item_mods
    - [x] [Runeist Bottes +1](https://www.bg-wiki.com/ffxi/Runeist_Bottes_%2B1)
  - [ ] [Runeist Armor Set +2](https://www.bg-wiki.com/ffxi/Runeist_Armor_Set_%2B2)
    - [ ] [Runeist Bandeau +2](https://www.bg-wiki.com/ffxi/Runeist_Bandeau_%2B2) missing "Regen" effect duration +24
    - [ ] [Runeist Coat +2](https://www.bg-wiki.com/ffxi/Runeist_Coat_%2B2) Missing Valiance and Vallation duration +17 seconds. (MOD: VALIANCE_VALLATION_DURATION = 1010)
    - [ ] [Runeist Mitons +2](https://www.bg-wiki.com/ffxi/Runeist_Mitons_%2B2)
    - [ ] [Runeist Trousers +2](https://www.bg-wiki.com/ffxi/Runeist_Trousers_%2B2)
    - [ ] [Runeist Bottes +2](https://www.bg-wiki.com/ffxi/Runeist_Bottes_%2B2)
  - [ ] [Runeist Armor Set +3](https://www.bg-wiki.com/ffxi/Runeist_Armor_Set_%2B3)
    - [ ] [Runeist Bandeau +3](https://www.bg-wiki.com/ffxi/Runeist_Bandeau_%2B3) missing "Regen" effect duration +27
    - [ ] [Runeist Coat +3](https://www.bg-wiki.com/ffxi/Runeist_Coat_%2B3) Missing Valiance and Vallation duration +19 seconds. (MOD: VALIANCE_VALLATION_DURATION = 1010)
    - [ ] [Runeist Mitons +3](https://www.bg-wiki.com/ffxi/Runeist_Mitons_%2B3)
    - [ ] [Runeist Trousers +3](https://www.bg-wiki.com/ffxi/Runeist_Trousers_%2B3)
    - [ ] [Runeist Bottes +3](https://www.bg-wiki.com/ffxi/Runeist_Bottes_%2B3)
- [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
  - [ ] [Futhark Armor Set](https://www.bg-wiki.com/ffxi/Futhark_Armor_Set)
    - [ ] [Futhark Bandeau](https://www.bg-wiki.com/ffxi/Futhark_Bandeau)
    - [ ] [Futhark Coat](https://www.bg-wiki.com/ffxi/Futhark_Coat)
    - [ ] [Futhark Mitons](https://www.bg-wiki.com/ffxi/Futhark_Mitons)
    - [ ] [Futhark Trousers](https://www.bg-wiki.com/ffxi/Futhark_Trousers)
    - [ ] [Futhark Boots](https://www.bg-wiki.com/ffxi/Futhark_Boots)
  - [ ] [Futhark Armor Set +1](https://www.bg-wiki.com/ffxi/Futhark_Armor_Set_%2B1)
    - [ ] [Futhark Bandeau +1](https://www.bg-wiki.com/ffxi/Futhark_Bandeau_%2B1)
    - [ ] [Futhark Coat +1](https://www.bg-wiki.com/ffxi/Futhark_Coat_%2B1)
    - [ ] [Futhark Mitons +1](https://www.bg-wiki.com/ffxi/Futhark_Mitons_%2B1)
    - [ ] [Futhark Trousers +1](https://www.bg-wiki.com/ffxi/Futhark_Trousers_%2B1)
    - [ ] [Futhark Boots +1](https://www.bg-wiki.com/ffxi/Futhark_Boots_%2B1)
  - [ ] [Futhark Armor Set +2](https://www.bg-wiki.com/ffxi/Futhark_Armor_Set_%2B2)
    - [ ] [Futhark Bandeau +2](https://www.bg-wiki.com/ffxi/Futhark_Bandeau_%2B2)
    - [ ] [Futhark Coat +2](https://www.bg-wiki.com/ffxi/Futhark_Coat_%2B2)
    - [ ] [Futhark Mitons +2](https://www.bg-wiki.com/ffxi/Futhark_Mitons_%2B2)
    - [ ] [Futhark Trousers +2](https://www.bg-wiki.com/ffxi/Futhark_Trousers_%2B2)
    - [ ] [Futhark Boots +2](https://www.bg-wiki.com/ffxi/Futhark_Boots_%2B2)
  - [ ] [Futhark Armor Set +3](https://www.bg-wiki.com/ffxi/Futhark_Armor_Set_%2B3)
    - [ ] [Futhark Bandeau +3](https://www.bg-wiki.com/ffxi/Futhark_Bandeau_%2B3)
    - [ ] [Futhark Coat +3](https://www.bg-wiki.com/ffxi/Futhark_Coat_%2B3)
    - [ ] [Futhark Mitons +3](https://www.bg-wiki.com/ffxi/Futhark_Mitons_%2B3)
    - [ ] [Futhark Trousers +3](https://www.bg-wiki.com/ffxi/Futhark_Trousers_%2B3)
    - [ ] [Futhark Boots +3](https://www.bg-wiki.com/ffxi/Futhark_Boots_%2B3)
  - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
    - [ ] [Futhark Torque](https://www.bg-wiki.com/ffxi/Futhark_Torque)
    - [ ] [Futhark Torque +1](https://www.bg-wiki.com/ffxi/Futhark_Torque_%2B1)
    - [ ] [Futhark Torque +2](https://www.bg-wiki.com/ffxi/Futhark_Torque_%2B2)
  - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
    - [ ] [Futhark Claymore](https://www.bg-wiki.com/ffxi/Futhark_Claymore)
    - [ ] [Peord Claymore](https://www.bg-wiki.com/ffxi/Peord_Claymore)
    - [ ] [Morgelai](https://www.bg-wiki.com/ffxi/Morgelai)
- [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
  - [ ] [Erilaz Armor Set](https://www.bg-wiki.com/ffxi/Erilaz_Armor_Set)
    - [ ] [Erilaz Galea](https://www.bg-wiki.com/ffxi/Erilaz_Galea)
    - [ ] [Erilaz Surcoat](https://www.bg-wiki.com/ffxi/Erilaz_Surcoat)
    - [ ] [Erilaz Gauntlets](https://www.bg-wiki.com/ffxi/Erilaz_Gauntlets)
    - [ ] [Erilaz Leg Guards](https://www.bg-wiki.com/ffxi/Erilaz_Leg_Guards)
    - [ ] [Erilaz Greaves](https://www.bg-wiki.com/ffxi/Erilaz_Greaves)
  - [ ] [Erilaz Armor Set +1](https://www.bg-wiki.com/ffxi/Erilaz_Armor_Set_%2B1)
    - [ ] [Erilaz Galea +1](https://www.bg-wiki.com/ffxi/Erilaz_Galea_%2B1)
    - [ ] [Erilaz Surcoat +1](https://www.bg-wiki.com/ffxi/Erilaz_Surcoat_%2B1)
    - [ ] [Erilaz Gauntlets +1](https://www.bg-wiki.com/ffxi/Erilaz_Gauntlets_%2B1)
    - [ ] [Erilaz Leg Guards +1](https://www.bg-wiki.com/ffxi/Erilaz_Leg_Guards_%2B1)
    - [ ] [Erilaz Greaves +1](https://www.bg-wiki.com/ffxi/Erilaz_Greaves_%2B1)
  - [ ] [Erilaz Armor Set +2](https://www.bg-wiki.com/ffxi/Erilaz_Armor_Set_%2B2)
    - [ ] [Erilaz Galea +2](https://www.bg-wiki.com/ffxi/Erilaz_Galea_%2B2)
    - [ ] [Erilaz Surcoat +2](https://www.bg-wiki.com/ffxi/Erilaz_Surcoat_%2B2)
    - [ ] [Erilaz Gauntlets +2](https://www.bg-wiki.com/ffxi/Erilaz_Gauntlets_%2B2)
    - [ ] [Erilaz Leg Guards +2](https://www.bg-wiki.com/ffxi/Erilaz_Leg_Guards_%2B2)
    - [ ] [Erilaz Greaves +2](https://www.bg-wiki.com/ffxi/Erilaz_Greaves_%2B2)
  - [ ] [Erilaz Armor Set +3](https://www.bg-wiki.com/ffxi/Erilaz_Armor_Set_%2B3)
    - [ ] [Erilaz Galea +3](https://www.bg-wiki.com/ffxi/Erilaz_Galea_%2B3)
    - [ ] [Erilaz Surcoat +3](https://www.bg-wiki.com/ffxi/Erilaz_Surcoat_%2B3)
    - [ ] [Erilaz Gauntlets +3](https://www.bg-wiki.com/ffxi/Erilaz_Gauntlets_%2B3)
    - [ ] [Erilaz Leg Guards +3](https://www.bg-wiki.com/ffxi/Erilaz_Leg_Guards_%2B3)
    - [ ] [Erilaz Greaves +3](https://www.bg-wiki.com/ffxi/Erilaz_Greaves_%2B3)
  - [ ] Accessories
    - [ ] [Erilaz Earring](https://www.bg-wiki.com/ffxi/Erilaz_Earring)
    - [ ] [Erilaz Earring +1](https://www.bg-wiki.com/ffxi/Erilaz_Earring_%2B1)
    - [ ] [Erilaz Earring +2](https://www.bg-wiki.com/ffxi/Erilaz_Earring_%2B2)
