### ISSUE TITLE
[build] Fix OSX build

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#150]
**TODO:**
Flesh out and test these, scraped from my old PR in DSP

- AppleClang defines nil as a macro for nullptr. This collides with sol pretty badly :( 
- Find/replace:
```
-               sol::nil;
+               sol::lua_nil;
```
- `server/src/map/CMakeLists.txt`: `link_options` -> `add_link_options`
- FileWatcher doesn't support OSX
- LuaJIT + Sol = panic on startup... (Update: just LuaJIT)

```
brew install git pkg-config autoconf make gcc openssl mariadb lua@5.1 zeromq zmqpp
brew install luajit --HEAD
mkdir build
cd build
cmake ..
make
```

- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by zach2good** [comment]
Some issues addressed by https://github.com/LandSandBoat/server/pull/168

**Comment by zach2good** [comment]
Update: It looks as though we could fix the OSX build by updating to a recent 2.1 update of LuaJIT:
https://github.com/LuaJIT/LuaJIT/issues/649

We can get to a similar stage: `error: Malformed Mach-o file`

Given that I'm a big scaredy cat and want to leave our LuaJIT binary alone, it looks as though the OSX build won't work for a while 🤷 
(I'm the only person that tends to try to run anything on OSX anyway, so no big loss)

**Comment by zach2good** [comment]
OSX Build fixed in: https://github.com/LandSandBoat/server/pull/1004

Also added OSX build instructions to the quick start guide:
https://github.com/LandSandBoat/server/wiki/Quick-Start-Guide
