### ISSUE TITLE
🔨 Feature: Logging improvements

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#1972]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

Internal chatting:

We have a bunch of commented out prints in Lua and C++ who's intention is that you uncomment them in order to get the info. We want to remove dead comments, so it's pretty hard to differentiate these two camps.

This lead to the ideas of:

`ShowTrace(...)` in C++ and `trace(...)` in Lua, which will only output if you're in debug, or if you have the correct settings on.

Also, some console_service/commands for changing the log levels at runtime. 

`!setconsolelevel 0-5` or whatever
 
Related: https://github.com/LandSandBoat/server/issues/2072

### Always On

- Critical
- Error
- Warn
- Info (should not be used for everything!)

### Conditional

- Debug (only on when built in debug)
- Trace (for very detailed, very verbose information about specific systems, should default to off and need to be turned on) (Should these be forced-on in debug builds?)

## TODO

- Test `release`, `debug` and `relwithdeb` builds and make sure that trace logging is only enabled by default on `debug`
- Add hot-reload to settings, and make sure various trace logs can be switched on/off
- Add a couple more trace categories and flags: auctions, trades, shop interactions, synths, navmesh/pathing, more detailed packet information (on request, not by default)
- Move audit flags to logging.lua, add more options for audits (auctions, trades, shop interactions, etc.)
- Look into sub-categories of logger again, not all warnings and errors are equal: a pet struggling to generate navmesh points is not as important as the navmesh results buffer being too small for the results etc.
- Even if all traces are turned off, we should still be filling spdlog's "Trace Buffer" so that we can output the last 20 trace messages on a crash

### Notes

Original categories:
```
#Makes server output more silent by omitting certain types of messages:
#Standard     = 1
#Status       = 2
#Info         = 4
#Notice       = 8
#Warn         = 16
#Debug        = 32
#Error        = 64
#Fatal Error  = 128
#SQL          = 256
#Lua          = 512
#Navmesh      = 1024
#Action       = 2048
#Example: "console_silent: 7" Hides standard, status and information messages (1+2+4)
console_silent: 0
```

**Comment by zach2good** [comment]
Relies on https://github.com/LandSandBoat/server/pull/1945 being finished, and logging.h/.cpp being refactored to be less crap

**Comment by TeoTwawki** [comment]
> or if you have the correct settings on
 
Teo loves configurable logging, hates "noise" that can't be shut off and hates rebuilding to turn logging on/off just putting these 3 things out there. :+1:

**Comment by zach2good** [comment]
I want to more closely match the levels internal to spdlog:
```
#define SPDLOG_LEVEL_TRACE 0
#define SPDLOG_LEVEL_DEBUG 1
#define SPDLOG_LEVEL_INFO 2
#define SPDLOG_LEVEL_WARN 3
#define SPDLOG_LEVEL_ERROR 4
#define SPDLOG_LEVEL_CRITICAL 5
```

I'm thinking about a layout like this:
```
TRACE (only visible when enabled through settings, or command/console commands, each sub-section can be toggled individually)
  - Navmesh
  - Events
  - Combat
  - etc.
DEBUG (only visible on a debug build, or when you've pushed your logging level high enough)
INFO (regular logging)
WARN (something is kinda fucky?)
ERROR (confirmed fucky)
CRITICAL (fatally fucky, goodbye!)
```

So then the settings would look like:
```
xi.settings.logging =
{
    ENABLE_TRACE = false,
    TRACE_NAVMESH = true,
    etc.

    ENABLE_DEBUG = false,

    -- These cannot be turned off
    -- ENABLE_INFO = false,
    -- ENABLE_WARN = false,
    -- ENABLE_ERROR = true,
    --ENABLE_FATAL_ERROR = true,
}

**Comment by zach2good** [comment]
I'm starting to not be sure about silently overriding user settings if they're in a Debug build or not.

Should we not use Trace and only use Debug, and have it controlled entirely from the logging settings?

We probably want to hook up the 'don't spam me because mob pets can't find their way' log options as an interim step

**Comment by zach2good** [comment]
Just had a little chat with Teo and we've come up with a design Im starting to like:

All the regular log levels, always on.

Debug is the one that's specialized, and they all default to off until you turn them on. Navmesh, actions etc. 

Trace is hyper detailed, and acts as comments in your code, and is writing to the trace buffer. When we get a crash, the last n lines of the trace buffer will be printed alongside the stack trace and other info

I feel like Lua print() should go to info(), and lua should also get debug() and trace() functions to help filter things out

**Comment by zach2good** [comment]
Combined with the new settings system, we have a good and quick way of enabling/disabling logging categories on the fly, making custom loggers, macros for loggers etc.
