### ISSUE TITLE
Items missing mods (Tracking purposes)

### ISSUE THREAD

**Issue by SirGouki** [DerpyProjectGroup/topaz#2580]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Multiple items are missing mods that are already in the core for example: Flame Degen is not in the database.
The intent of this Bug Report is so that I can publicly track these as a I hunt them down and correct them, as well as their status. 

NOTE: This is why I didn't [x] "I have checked all commits and Issues"  There's enough that its a pain for one person to gather all this info, and I'm sure there's a lot I haven't found yet considering my list started so small, I can't imagine how long it'd take to go through that many commits/issues

[LSB Stuff - Equipment Missing Mods](https://docs.google.com/spreadsheets/d/1ywYsSs7N46vSAzNkU9QtkL6gOB8dR4Of2FxiQuyguGA)

If anyone knows of others, please comment them below (please use the actual ingame name and not shorthand, as well as, as much information as you have on the item).  If you're in a server that I'm in (SirGouki in the private servers, or Trilion in Catseye) you may also DM me if its related to this.  You can also comment below if you've fixed them already so I don't fix something that's already been fixed (incase I don't catch issues/PRs for them).  I'll be monitoring this as I discover them.  As I fix these, I'll update the status.  If I (or someone else) has PR'd a fix, I will remove them from this list.

Edit: I moved the list to a google spreadsheet so its easier to track multiple items.  If you don't see something on this list, it was either fixed prior to me doing this, or I don't know about it.  NOTE: Only users I approve can edit this doc, anyone should be able to view it using that link.

## Expected behavior

The appropriate modifications should trigger (for Flame Degen: chance to cause Additional Effect fire damage should proc)

**Comment by Aeisu** [comment]
I asked a similar question recently here and am slowly poking the item_mods lua with more code daily
https://github.com/LandSandBoat/server/discussions/1670
I also came across other items missing mods but the ones i noted I don't think are implemented yet

**Comment by SirGouki** [comment]
my first (and primary) goal with this particular issue is to implement the ones that are just missing db entries.  Excalibur is in there because it was requested by the players in the server I'm part of.  Doesn't mean that others wont get done, just focusing on these kind for now.

**Comment by Aeisu** [comment]
gotcha
I'm just strolling down the list one ID at a time in both item_mods and item_mods_pets, commenting in what appears on the item description and adding items that are not there but those seem to be past 19000 now ,but i may find some stragglers.
I'm also keeping a list of **latents** and **zone** specific items and **sets** as well just to verify everything. 

i'm going to try and keep my list up to date but in a subfolder to the SQL one on my own branch so not to confuse anything
https://github.com/Aeisu/LSB_Item_Mod_Revisions

**Comment by TeoTwawki** [comment]
I did the fire weapons last night. elemental damage are the among easiest to get done. you just need to know the enumeration for:
- elements
- subeffects
- additional effect types (right in the global)

The power and chance confirmation is something every single one needs, until then estimating using [this commit](https://github.com/LandSandBoat/server/commit/e8b90c2384face115bfe2f5df1c02d77a54181f0#diff-83202f421ccc8482d12acfaffe0c092a93a1f3f7c16a1f45504474b3bd2c81d9L17) as a guide or using a seen value from retail is allowed. To really confirm the right power requires multiple retail tests against several mobs that don't resist the element.

**Comment by EpicTaru** [comment]
I'm reviewing the diffs of what Aeisu did in theirs, btw, Teo.

**Comment by RAIST5150** [comment]
Haven't thwacked anything with them in quite a while, but don't recall seeing the elemental staves getting updated (Dark/Pluto's Staff, Ice/Aquilo's Staff, etc.).

**Comment by Aeisu** [comment]
Just checked they are most definitely there Line 33992 - 34194 
I also saw the Chatoyant line 37227 and Iridal line 37233
or at least in that general area @.@

**Comment by TeoTwawki** [comment]
> Just checked they are most definitely there Line 33992 - 34194 I also saw the Chatoyant line 37227 and Iridal line 37233 or at least in that general area @.@

prolly missing the add effect mods though

**Comment by Aeisu** [comment]
-- Fire Staff
INSERT INTO `item_mods` VALUES (17545,8,4);    -- STR: 4
INSERT INTO `item_mods` VALUES (17545,16,15);  -- ICE_RES: 15
INSERT INTO `item_mods` VALUES (17545,23,10);  -- ATT: 10
INSERT INTO `item_mods` VALUES (17545,24,10);  -- RATT: 10
INSERT INTO `item_mods` VALUES (17545,347,2);  -- FIRE_AFFINITY_DMG: 2
INSERT INTO `item_mods` VALUES (17545,348,-2); -- ICE_AFFINITY_DMG: -2
INSERT INTO `item_mods` VALUES (17545,544,2);  -- FIRE_AFFINITY_ACC: 2
INSERT INTO `item_mods` VALUES (17545,545,-2); -- ICE_AFFINITY_ACC: -2
INSERT INTO `item_mods` VALUES (17545,553,2);  -- FIRE_AFFINITY_PERP: 2
INSERT INTO `item_mods` VALUES (17545,554,-2); -- ICE_AFFINITY_PERP: -2

-- Vulcans Staff
INSERT INTO `item_mods` VALUES (17546,8,5);    -- STR: 5
INSERT INTO `item_mods` VALUES (17546,16,20);  -- ICE_RES: 20
INSERT INTO `item_mods` VALUES (17546,23,10);  -- ATT: 10
INSERT INTO `item_mods` VALUES (17546,24,10);  -- RATT: 10
INSERT INTO `item_mods` VALUES (17546,347,3);  -- FIRE_AFFINITY_DMG: 3
INSERT INTO `item_mods` VALUES (17546,348,-3); -- ICE_AFFINITY_DMG: -3
INSERT INTO `item_mods` VALUES (17546,544,3);  -- FIRE_AFFINITY_ACC: 3
INSERT INTO `item_mods` VALUES (17546,545,-3); -- ICE_AFFINITY_ACC: -3
INSERT INTO `item_mods` VALUES (17546,553,3);  -- FIRE_AFFINITY_PERP: 3
INSERT INTO `item_mods` VALUES (17546,554,-3); -- ICE_AFFINITY_PERP: -3

you mean the hidden mods?

**Comment by RAIST5150** [comment]
> > Just checked they are most definitely there Line 33992 - 34194 I also saw the Chatoyant line 37227 and Iridal line 37233 or at least in that general area @.@
> 
> prolly missing the add effect mods though

Yeah... looks like they are all still missing the additional effect elemental damage (enspell style effect).

I had stumbled on a discussion about the frequency and strength of them like a year ago... can't find it now for the life of me.

**Comment by SirGouki** [comment]
Corrected excal ID in my list, don't know why it had Track Pants+1's id.

~~Pretty soon I'll be moving this list to a google doc and linking the google doc.~~
List is moved to a google doc.

**Comment by SirGouki** [comment]
I haven't completely stopped working on this, just got swamped with other stuff and am slowly getting back to it

If anyone's got info I don't have, or has fixed one of the ones I have listed, please let me know so I can update my table.
