### ISSUE TITLE
Remaining Level Sync Interaction Rejection Tracker

### ISSUE THREAD

**Issue by WinterSolstice8** [DerpyProjectGroup/topaz#2645]
This issue is to track the remaining interactions that are blocked with Level Sync

- [ ] Salvage/Assault does not give Level Cap status to prevent level sync inside
- [ ] Unity Wanted Battle when implemented needs to reject parties with Level Sync  with a generic bailout message "Unable to commence Wanted battle"
- [ ] Field Parchment battles reject the fight with the explicit MEMBERS_LEVELS_ARE_RESTRICTED message from zone message
 IDs
- [ ] ANNM battles reject the fight with the explicit MEMBERS_LEVELS_ARE_RESTRICTED message from zone message
 IDs
- [ ] Voidwatch just does not let you interact with level sync up
- [X] Battlefields reject entry & trade with level sync up #1053
