### ISSUE TITLE
WAR JSE Completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4390]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [WAR](https://www.bg-wiki.com/ffxi/Warrior)
  - [x] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [x] [Fighter's Armor Set](https://www.bg-wiki.com/ffxi/Fighter%27s_Armor_Set)
      - [x] [Fighter's Calligae](https://www.bg-wiki.com/ffxi/Fighter%27s_Calligae)
      - [x] [Fighter's Mufflers](https://www.bg-wiki.com/ffxi/Fighter%27s_Mufflers)
      - [x] [Fighter's Mask](https://www.bg-wiki.com/ffxi/Fighter%27s_Mask)
      - [x] [Fighter's Cuisses](https://www.bg-wiki.com/ffxi/Fighter%27s_Cuisses)
      - [x] [Fighter's Lorica](https://www.bg-wiki.com/ffxi/Fighter%27s_Lorica)
    - [x] [Fighter's Armor Set +1](https://www.bg-wiki.com/ffxi/Fighter%27s_Armor_Set_%2B1)
      - [x] [Fighter's Calligae +1](https://www.bg-wiki.com/ffxi/Fighter%27s_Calligae_%2B1)
      - [x] [Fighter's Mufflers +1](https://www.bg-wiki.com/ffxi/Fighter%27s_Mufflers_%2B1)
      - [x] [Fighter's Mask +1](https://www.bg-wiki.com/ffxi/Fighter%27s_Mask_%2B1)
      - [x] [Fighter's Cuisses +1](https://www.bg-wiki.com/ffxi/Fighter%27s_Cuisses_%2B1)
      - [x] [Fighter's Lorica +1](https://www.bg-wiki.com/ffxi/Fighter%27s_Lorica_%2B1)
    - [x] [Pummeler's Armor Set](https://www.bg-wiki.com/ffxi/Pummeler%27s_Armor_Set)
      - [x] [Pummeler's Mask](https://www.bg-wiki.com/ffxi/Pummeler%27s_Mask)
      - [x] [Pummeler's Lorica](https://www.bg-wiki.com/ffxi/Pummeler%27s_Lorica)
      - [x] [Pummeler's Mufflers](https://www.bg-wiki.com/ffxi/Pummeler%27s_Mufflers)
      - [x] [Pummeler's Cuisses](https://www.bg-wiki.com/ffxi/Pummeler%27s_Cuisses)
      - [x] [Pummeler's Calligae](https://www.bg-wiki.com/ffxi/Pummeler%27s_Calligae)
    - [x] [Pummeler's Armor Set +1](https://www.bg-wiki.com/ffxi/Pummeler%27s_Armor_Set_%2B1)
      - [x] [Pummeler's Mask +1](https://www.bg-wiki.com/ffxi/Pummeler%27s_Mask_%2B1)
      - [x] [Pummeler's Lorica +1](https://www.bg-wiki.com/ffxi/Pummeler%27s_Lorica_%2B1)
      - [x] [Pummeler's Mufflers +1](https://www.bg-wiki.com/ffxi/Pummeler%27s_Mufflers_%2B1)
      - [x] [Pummeler's Cuisses +1](https://www.bg-wiki.com/ffxi/Pummeler%27s_Cuisses_%2B1)
      - [x] [Pummeler's Calligae +1](https://www.bg-wiki.com/ffxi/Pummeler%27s_Calligae_%2B1)
    - [x] [Pummeler's Armor Set +2](https://www.bg-wiki.com/ffxi/Pummeler%27s_Armor_Set_%2B2)
      - [x] [Pummeler's Mask +2](https://www.bg-wiki.com/ffxi/Pummeler%27s_Mask_%2B2)
      - [x] [Pummeler's Lorica +2](https://www.bg-wiki.com/ffxi/Pummeler%27s_Lorica_%2B2)
      - [x] [Pummeler's Mufflers +2](https://www.bg-wiki.com/ffxi/Pummeler%27s_Mufflers_%2B2)
      - [x] [Pummeler's Cuisses +2](https://www.bg-wiki.com/ffxi/Pummeler%27s_Cuisses_%2B2)
      - [x] [Pummeler's Calligae +2](https://www.bg-wiki.com/ffxi/Pummeler%27s_Calligae_%2B2)
    - [x] [Pummeler's Armor Set +3](https://www.bg-wiki.com/ffxi/Pummeler%27s_Armor_Set_%2B3)
      - [x] [Pummeler's Mask +3](https://www.bg-wiki.com/ffxi/Pummeler%27s_Mask_%2B3)
      - [x] [Pummeler's Lorica +3](https://www.bg-wiki.com/ffxi/Pummeler%27s_Lorica_%2B3)
      - [x] [Pummeler's Mufflers +3](https://www.bg-wiki.com/ffxi/Pummeler%27s_Mufflers_%2B3)
      - [x] [Pummeler's Cuisses +3](https://www.bg-wiki.com/ffxi/Pummeler%27s_Cuisses_%2B3)
      - [x] [Pummeler's Calligae +3](https://www.bg-wiki.com/ffxi/Pummeler%27s_Calligae_%2B3)
  - [x] [Razor Axe](https://www.bg-wiki.com/ffxi/Razor_Axe)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [x] [Warrior's Armor Set](https://www.bg-wiki.com/ffxi/Warrior%27s_Armor_Set)
      - [x] [Warrior's Calligae](https://www.bg-wiki.com/ffxi/Warrior%27s_Calligae)
      - [x] [Warrior's Mufflers](https://www.bg-wiki.com/ffxi/Warrior%27s_Mufflers)
      - [x] [Warrior's Mask](https://www.bg-wiki.com/ffxi/Warrior%27s_Mask)
      - [x] [Warrior's Cuisses](https://www.bg-wiki.com/ffxi/Warrior%27s_Cuisses)
      - [x] [Warrior's Lorica](https://www.bg-wiki.com/ffxi/Warrior%27s_Lorica)
    - [x] [Warrior's Armor Set +1](https://www.bg-wiki.com/ffxi/Warrior%27s_Armor_Set_%2B1)
      - [x] [Warrior's Calligae +1](https://www.bg-wiki.com/ffxi/Warrior%27s_Calligae_%2B1)
      - [x] [Warrior's Mufflers +1](https://www.bg-wiki.com/ffxi/Warrior%27s_Mufflers_%2B1)
      - [x] [Warrior's Mask +1](https://www.bg-wiki.com/ffxi/Warrior%27s_Mask_%2B1)
      - [x] [Warrior's Cuisses +1](https://www.bg-wiki.com/ffxi/Warrior%27s_Cuisses_%2B1)
      - [x] [Warrior's Lorica +1](https://www.bg-wiki.com/ffxi/Warrior%27s_Lorica_%2B1)
    - [x] [Warrior's Armor Set +2](https://www.bg-wiki.com/ffxi/Warrior%27s_Armor_Set_%2B2)
      - [x] [Warrior's Calligae +2](https://www.bg-wiki.com/ffxi/Warrior%27s_Calligae_%2B2)
      - [x] [Warrior's Mufflers +2](https://www.bg-wiki.com/ffxi/Warrior%27s_Mufflers_%2B2)
      - [x] [Warrior's Mask +2](https://www.bg-wiki.com/ffxi/Warrior%27s_Mask_%2B2)
      - [x] [Warrior's Cuisses +2](https://www.bg-wiki.com/ffxi/Warrior%27s_Cuisses_%2B2)
      - [x] [Warrior's Lorica +2](https://www.bg-wiki.com/ffxi/Warrior%27s_Lorica_%2B2)
    - [x] [Agoge Armor Set](https://www.bg-wiki.com/ffxi/Agoge_Armor_Set)
      - [x] [Agoge Mask](https://www.bg-wiki.com/ffxi/Agoge_Mask)
      - [x] [Agoge Lorica](https://www.bg-wiki.com/ffxi/Agoge_Lorica)
      - [x] [Agoge Mufflers](https://www.bg-wiki.com/ffxi/Agoge_Mufflers)
      - [x] [Agoge Cuisses](https://www.bg-wiki.com/ffxi/Agoge_Cuisses)
      - [x] [Agoge Calligae](https://www.bg-wiki.com/ffxi/Agoge_Calligae)
    - [x] [Agoge Armor Set +1](https://www.bg-wiki.com/ffxi/Agoge_Armor_Set_%2B1)
      - [x] [Agoge Mask +1](https://www.bg-wiki.com/ffxi/Agoge_Mask_%2B1)
      - [x] [Agoge Lorica +1](https://www.bg-wiki.com/ffxi/Agoge_Lorica_%2B1)
      - [x] [Agoge Mufflers +1](https://www.bg-wiki.com/ffxi/Agoge_Mufflers_%2B1)
      - [x] [Agoge Cuisses +1](https://www.bg-wiki.com/ffxi/Agoge_Cuisses_%2B1)
      - [x] [Agoge Calligae +1](https://www.bg-wiki.com/ffxi/Agoge_Calligae_%2B1)
    - [x] [Agoge Armor Set +2](https://www.bg-wiki.com/ffxi/Agoge_Armor_Set_%2B2)
      - [x] [Agoge Mask +2](https://www.bg-wiki.com/ffxi/Agoge_Mask_%2B2)
      - [x] [Agoge Lorica +2](https://www.bg-wiki.com/ffxi/Agoge_Lorica_%2B2)
      - [x] [Agoge Mufflers +2](https://www.bg-wiki.com/ffxi/Agoge_Mufflers_%2B2)
      - [x] [Agoge Cuisses +2](https://www.bg-wiki.com/ffxi/Agoge_Cuisses_%2B2)
      - [x] [Agoge Calligae +2](https://www.bg-wiki.com/ffxi/Agoge_Calligae_%2B2)
    - [ ] [Agoge Armor Set +3](https://www.bg-wiki.com/ffxi/Agoge_Armor_Set_%2B3)
      - [ ] [Agoge Mask +3](https://www.bg-wiki.com/ffxi/Agoge_Mask_%2B3) - Missing all mods except WARCRY_DURATION
      - [ ] [Agoge Lorica +3](https://www.bg-wiki.com/ffxi/Agoge_Lorica_%2B3) - Missing all mods except AGGRESSOR_DURATION
      - [ ] [Agoge Mufflers +3](https://www.bg-wiki.com/ffxi/Agoge_Mufflers_%2B3) - Only 3 mods added
      - [x] [Agoge Cuisses +3](https://www.bg-wiki.com/ffxi/Agoge_Cuisses_%2B3)
      - [x] [Agoge Calligae +3](https://www.bg-wiki.com/ffxi/Agoge_Calligae_%2B3)
    - [x] [Warrior's Stone](https://www.bg-wiki.com/ffxi/Warrior%27s_Stone)
    - [x] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [x] [Warrior's Beads](https://www.bg-wiki.com/ffxi/Warrior%27s_Beads)
      - [x] [Warrior's Beads +1](https://www.bg-wiki.com/ffxi/Warrior%27s_Beads_%2B1)
      - [x] [Warrior's Beads +2](https://www.bg-wiki.com/ffxi/Warrior%27s_Beads_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Warrior's Chopper](https://www.bg-wiki.com/ffxi/Warrior%27s_Chopper) - Missing Dynamis (D): Accuracy+10 Magic Accuracy+10
      - [ ] [Agoge Chopper](https://www.bg-wiki.com/ffxi/Agoge_Chopper) - Missing Dynamis (D): Accuracy+10 Magic Accuracy+10
      - [x] [Labraunda](https://www.bg-wiki.com/ffxi/Labraunda)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [x] [Ravager's Armor Set](https://www.bg-wiki.com/ffxi/Ravager%27s_Armor_Set)
      - [x] [Ravager's Calligae](https://www.bg-wiki.com/ffxi/Ravager%27s_Calligae)
      - [x] [Ravager's Cuisses](https://www.bg-wiki.com/ffxi/Ravager%27s_Cuisses)
      - [x] [Ravager's Mask](https://www.bg-wiki.com/ffxi/Ravager%27s_Mask)
      - [x] [Ravager's Mufflers](https://www.bg-wiki.com/ffxi/Ravager%27s_Mufflers)
      - [x] [Ravager's Lorica](https://www.bg-wiki.com/ffxi/Ravager%27s_Lorica)
    - [x] [Ravager's Armor Set +1](https://www.bg-wiki.com/ffxi/Ravager%27s_Armor_Set_%2B1)
      - [x] [Ravager's Calligae +1](https://www.bg-wiki.com/ffxi/Ravager%27s_Calligae_%2B1)
      - [x] [Ravager's Cuisses +1](https://www.bg-wiki.com/ffxi/Ravager%27s_Cuisses_%2B1)
      - [x] [Ravager's Mask +1](https://www.bg-wiki.com/ffxi/Ravager%27s_Mask_%2B1)
      - [x] [Ravager's Mufflers +1](https://www.bg-wiki.com/ffxi/Ravager%27s_Mufflers_%2B1)
      - [x] [Ravager's Lorica +1](https://www.bg-wiki.com/ffxi/Ravager%27s_Lorica_%2B1)
    - [x] [Ravager's Armor Set +2](https://www.bg-wiki.com/ffxi/Ravager%27s_Armor_Set_%2B2)
      - [x] [Ravager's Calligae +2](https://www.bg-wiki.com/ffxi/Ravager%27s_Calligae_%2B2)
      - [x] [Ravager's Cuisses +2](https://www.bg-wiki.com/ffxi/Ravager%27s_Cuisses_%2B2)
      - [x] [Ravager's Mask +2](https://www.bg-wiki.com/ffxi/Ravager%27s_Mask_%2B2)
      - [x] [Ravager's Mufflers +2](https://www.bg-wiki.com/ffxi/Ravager%27s_Mufflers_%2B2)
      - [x] [Ravager's Lorica +2](https://www.bg-wiki.com/ffxi/Ravager%27s_Lorica_%2B2)
    - [x] [Boii Armor Set](https://www.bg-wiki.com/ffxi/Boii_Armor_Set)
      - [x] [Boii Mask](https://www.bg-wiki.com/ffxi/Boii_Mask)
      - [x] [Boii Lorica](https://www.bg-wiki.com/ffxi/Boii_Lorica)
      - [x] [Boii Mufflers](https://www.bg-wiki.com/ffxi/Boii_Mufflers)
      - [x] [Boii Cuisses](https://www.bg-wiki.com/ffxi/Boii_Cuisses)
      - [x] [Boii Calligae](https://www.bg-wiki.com/ffxi/Boii_Calligae)
    - [ ] [Boii Armor Set +1](https://www.bg-wiki.com/ffxi/Boii_Armor_Set_%2B1)
      - [ ] [Boii Mask +1](https://www.bg-wiki.com/ffxi/Boii_Mask_%2B1)
      - [ ] [Boii Lorica +1](https://www.bg-wiki.com/ffxi/Boii_Lorica_%2B1)
      - [ ] [Boii Mufflers +1](https://www.bg-wiki.com/ffxi/Boii_Mufflers_%2B1)
      - [ ] [Boii Cuisses +1](https://www.bg-wiki.com/ffxi/Boii_Cuisses_%2B1)
      - [ ] [Boii Calligae +1](https://www.bg-wiki.com/ffxi/Boii_Calligae_%2B1)
    - [ ] [Boii Armor Set +2](https://www.bg-wiki.com/ffxi/Boii_Armor_Set_%2B2)
      - [ ] [Boii Mask +2](https://www.bg-wiki.com/ffxi/Boii_Mask_%2B2)
      - [ ] [Boii Lorica +2](https://www.bg-wiki.com/ffxi/Boii_Lorica_%2B2)
      - [ ] [Boii Mufflers +2](https://www.bg-wiki.com/ffxi/Boii_Mufflers_%2B2)
      - [ ] [Boii Cuisses +2](https://www.bg-wiki.com/ffxi/Boii_Cuisses_%2B2)
      - [ ] [Boii Calligae +2](https://www.bg-wiki.com/ffxi/Boii_Calligae_%2B2)
    - [ ] [Boii Armor Set +3](https://www.bg-wiki.com/ffxi/Boii_Armor_Set_%2B3)
      - [ ] [Boii Mask +3](https://www.bg-wiki.com/ffxi/Boii_Mask_%2B3)
      - [ ] [Boii Lorica +3](https://www.bg-wiki.com/ffxi/Boii_Lorica_%2B3)
      - [ ] [Boii Mufflers +3](https://www.bg-wiki.com/ffxi/Boii_Mufflers_%2B3)
      - [ ] [Boii Cuisses +3](https://www.bg-wiki.com/ffxi/Boii_Cuisses_%2B3)
      - [ ] [Boii Calligae +3](https://www.bg-wiki.com/ffxi/Boii_Calligae_%2B3)
    - [ ] Accessories
      - [ ] [Ravager's Gorget](https://www.bg-wiki.com/ffxi/Ravager%27s_Gorget)
      - [ ] [Ravager's Orb](https://www.bg-wiki.com/ffxi/Ravager%27s_Orb)
      - [ ] [Ravager's Earring](https://www.bg-wiki.com/ffxi/Ravager%27s_Earring)
      - [ ] [Boii Earring](https://www.bg-wiki.com/ffxi/Boii_Earring)
      - [ ] [Boii Earring +1](https://www.bg-wiki.com/ffxi/Boii_Earring_%2B1)
      - [ ] [Boii Earring +2](https://www.bg-wiki.com/ffxi/Boii_Earring_%2B2)
