### ISSUE TITLE
MNK JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4391]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [MNK](https://www.bg-wiki.com/ffxi/Monk)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Temple Attire Set](https://www.bg-wiki.com/ffxi/Temple_Attire_Set)
      - [ ] [Temple Gaiters](https://www.bg-wiki.com/ffxi/Temple_Gaiters)
      - [ ] [Temple Gloves](https://www.bg-wiki.com/ffxi/Temple_Gloves)
      - [ ] [Temple Crown](https://www.bg-wiki.com/ffxi/Temple_Crown)
      - [ ] [Temple Cyclas](https://www.bg-wiki.com/ffxi/Temple_Cyclas)
      - [ ] [Temple Hose](https://www.bg-wiki.com/ffxi/Temple_Hose)
    - [ ] [Temple Attire Set +1](https://www.bg-wiki.com/ffxi/Temple_Attire_Set_%2B1)
      - [ ] [Temple Gaiters +1](https://www.bg-wiki.com/ffxi/Temple_Gaiters_%2B1)
      - [ ] [Temple Gloves +1](https://www.bg-wiki.com/ffxi/Temple_Gloves_%2B1)
      - [ ] [Temple Crown +1](https://www.bg-wiki.com/ffxi/Temple_Crown_%2B1)
      - [ ] [Temple Cyclas +1](https://www.bg-wiki.com/ffxi/Temple_Cyclas_%2B1)
      - [ ] [Temple Hose +1](https://www.bg-wiki.com/ffxi/Temple_Hose_%2B1)
    - [ ] [Anchorite's Attire Set](https://www.bg-wiki.com/ffxi/Anchorite%27s_Attire_Set)
      - [ ] [Anchorite's Crown](https://www.bg-wiki.com/ffxi/Anchorite%27s_Crown)
      - [ ] [Anchorite's Cyclas](https://www.bg-wiki.com/ffxi/Anchorite%27s_Cyclas)
      - [ ] [Anchorite's Gloves](https://www.bg-wiki.com/ffxi/Anchorite%27s_Gloves)
      - [ ] [Anchorite's Hose](https://www.bg-wiki.com/ffxi/Anchorite%27s_Hose)
      - [ ] [Anchorite's Gaiters](https://www.bg-wiki.com/ffxi/Anchorite%27s_Gaiters)
    - [ ] [Anchorite's Attire Set +1](https://www.bg-wiki.com/ffxi/Anchorite%27s_Attire_Set_%2B1)
      - [ ] [Anchorite's Crown +1](https://www.bg-wiki.com/ffxi/Anchorite%27s_Crown_%2B1)
      - [ ] [Anchorite's Cyclas +1](https://www.bg-wiki.com/ffxi/Anchorite%27s_Cyclas_%2B1)
      - [ ] [Anchorite's Gloves +1](https://www.bg-wiki.com/ffxi/Anchorite%27s_Gloves_%2B1)
      - [ ] [Anchorite's Hose +1](https://www.bg-wiki.com/ffxi/Anchorite%27s_Hose_%2B1)
      - [ ] [Anchorite's Gaiters +1](https://www.bg-wiki.com/ffxi/Anchorite%27s_Gaiters_%2B1)
    - [ ] [Anchorite's Attire Set +2](https://www.bg-wiki.com/ffxi/Anchorite%27s_Attire_Set_%2B2)
      - [ ] [Anchorite's Crown +2](https://www.bg-wiki.com/ffxi/Anchorite%27s_Crown_%2B2)
      - [ ] [Anchorite's Cyclas +2](https://www.bg-wiki.com/ffxi/Anchorite%27s_Cyclas_%2B2)
      - [ ] [Anchorite's Gloves +2](https://www.bg-wiki.com/ffxi/Anchorite%27s_Gloves_%2B2)
      - [ ] [Anchorite's Hose +2](https://www.bg-wiki.com/ffxi/Anchorite%27s_Hose_%2B2)
      - [ ] [Anchorite's Gaiters +2](https://www.bg-wiki.com/ffxi/Anchorite%27s_Gaiters_%2B2)
    - [ ] [Anchorite's Attire Set +3](https://www.bg-wiki.com/ffxi/Anchorite%27s_Attire_Set_%2B3)
      - [ ] [Anchorite's Crown +3](https://www.bg-wiki.com/ffxi/Anchorite%27s_Crown_%2B3)
      - [ ] [Anchorite's Cyclas +3](https://www.bg-wiki.com/ffxi/Anchorite%27s_Cyclas_%2B3)
      - [ ] [Anchorite's Gloves +3](https://www.bg-wiki.com/ffxi/Anchorite%27s_Gloves_%2B3)
      - [ ] [Anchorite's Hose +3](https://www.bg-wiki.com/ffxi/Anchorite%27s_Hose_%2B3)
      - [ ] [Anchorite's Gaiters +3](https://www.bg-wiki.com/ffxi/Anchorite%27s_Gaiters_%2B3)
    - [ ] [Beat Cesti](https://www.bg-wiki.com/ffxi/Beat_Cesti)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Melee Attire Set](https://www.bg-wiki.com/ffxi/Melee_Attire_Set)
      - [ ] [Melee Gaiters](https://www.bg-wiki.com/ffxi/Melee_Gaiters)
      - [ ] [Melee Hose](https://www.bg-wiki.com/ffxi/Melee_Hose)
      - [ ] [Melee Gloves](https://www.bg-wiki.com/ffxi/Melee_Gloves)
      - [ ] [Melee Cyclas](https://www.bg-wiki.com/ffxi/Melee_Cyclas)
      - [ ] [Melee Crown](https://www.bg-wiki.com/ffxi/Melee_Crown)
    - [ ] [Melee Attire Set +1](https://www.bg-wiki.com/ffxi/Melee_Attire_Set_%2B1)
      - [ ] [Melee Gaiters +1](https://www.bg-wiki.com/ffxi/Melee_Gaiters_%2B1)
      - [ ] [Melee Hose +1](https://www.bg-wiki.com/ffxi/Melee_Hose_%2B1)
      - [ ] [Melee Gloves +1](https://www.bg-wiki.com/ffxi/Melee_Gloves_%2B1)
      - [ ] [Melee Cyclas +1](https://www.bg-wiki.com/ffxi/Melee_Cyclas_%2B1)
      - [ ] [Melee Crown +1](https://www.bg-wiki.com/ffxi/Melee_Crown_%2B1)
    - [ ] [Melee Attire Set +2](https://www.bg-wiki.com/ffxi/Melee_Attire_Set_%2B2)
      - [ ] [Melee Gaiters +2](https://www.bg-wiki.com/ffxi/Melee_Gaiters_%2B2)
      - [ ] [Melee Hose +2](https://www.bg-wiki.com/ffxi/Melee_Hose_%2B2)
      - [ ] [Melee Gloves +2](https://www.bg-wiki.com/ffxi/Melee_Gloves_%2B2)
      - [ ] [Melee Cyclas +2](https://www.bg-wiki.com/ffxi/Melee_Cyclas_%2B2)
      - [ ] [Melee Crown +2](https://www.bg-wiki.com/ffxi/Melee_Crown_%2B2)
    - [ ] [Hesychast's Attire Set](https://www.bg-wiki.com/ffxi/Hesychast%27s_Attire_Set)
      - [ ] [Hesychast's Crown](https://www.bg-wiki.com/ffxi/Hesychast%27s_Crown)
      - [ ] [Hesychast's Cyclas](https://www.bg-wiki.com/ffxi/Hesychast%27s_Cyclas)
      - [ ] [Hesychast's Gloves](https://www.bg-wiki.com/ffxi/Hesychast%27s_Gloves)
      - [ ] [Hesychast's Hose](https://www.bg-wiki.com/ffxi/Hesychast%27s_Hose)
      - [ ] [Hesychast's Gaiters](https://www.bg-wiki.com/ffxi/Hesychast%27s_Gaiters)
    - [ ] [Hesychast's Attire Set +1](https://www.bg-wiki.com/ffxi/Hesychast%27s_Attire_Set_%2B1)
      - [ ] [Hesychast's Crown +1](https://www.bg-wiki.com/ffxi/Hesychast%27s_Crown_%2B1)
      - [ ] [Hesychast's Cyclas +1](https://www.bg-wiki.com/ffxi/Hesychast%27s_Cyclas_%2B1)
      - [ ] [Hesychast's Gloves +1](https://www.bg-wiki.com/ffxi/Hesychast%27s_Gloves_%2B1)
      - [ ] [Hesychast's Hose +1](https://www.bg-wiki.com/ffxi/Hesychast%27s_Hose_%2B1)
      - [ ] [Hesychast's Gaiters +1](https://www.bg-wiki.com/ffxi/Hesychast%27s_Gaiters_%2B1)
    - [ ] [Hesychast's Attire +2](https://www.bg-wiki.com/ffxi/Hesychast%27s_Attire_Set_%2B2)
      - [ ] [Hesychast's Crown +2](https://www.bg-wiki.com/ffxi/Hesychast%27s_Crown_%2B2)
      - [ ] [Hesychast's Cyclas +2](https://www.bg-wiki.com/ffxi/Hesychast%27s_Cyclas_%2B2)
      - [ ] [Hesychast's Gloves +2](https://www.bg-wiki.com/ffxi/Hesychast%27s_Gloves_%2B2)
      - [ ] [Hesychast's Hose +2](https://www.bg-wiki.com/ffxi/Hesychast%27s_Hose_%2B2)
      - [ ] [Hesychast's Gaiters +2](https://www.bg-wiki.com/ffxi/Hesychast%27s_Gaiters_%2B2)
    - [ ] [Hesychast's Attire +3](https://www.bg-wiki.com/ffxi/Hesychast%27s_Attire_Set_%2B3)
      - [ ] [Hesychast's Crown +3](https://www.bg-wiki.com/ffxi/Hesychast%27s_Crown_%2B3)
      - [ ] [Hesychast's Cyclas +3](https://www.bg-wiki.com/ffxi/Hesychast%27s_Cyclas_%2B3)
      - [ ] [Hesychast's Gloves +3](https://www.bg-wiki.com/ffxi/Hesychast%27s_Gloves_%2B3)
      - [ ] [Hesychast's Hose +3](https://www.bg-wiki.com/ffxi/Hesychast%27s_Hose_%2B3)
      - [ ] [Hesychast's Gaiters +3](https://www.bg-wiki.com/ffxi/Hesychast%27s_Gaiters_%2B3)
    - [ ] [Melee Cape](https://www.bg-wiki.com/ffxi/Melee_Cape)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Monk's Nodowa](https://www.bg-wiki.com/ffxi/Monk%27s_Nodowa)
      - [ ] [Monk's Nodowa +1](https://www.bg-wiki.com/ffxi/Monk%27s_Nodowa_%2B1)
      - [ ] [Monk's Nodowa +2](https://www.bg-wiki.com/ffxi/Monk%27s_Nodowa_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Melee Fists](https://www.bg-wiki.com/ffxi/Melee_Fists)
      - [ ] [Hesychast's Fists](https://www.bg-wiki.com/ffxi/Hesychast%27s_Fists)
      - [ ] [Sagitta](https://www.bg-wiki.com/ffxi/Sagitta)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Tantra Attire Set](https://www.bg-wiki.com/ffxi/Tantra_Attire_Set)
      - [ ] [Tantra Gaiters](https://www.bg-wiki.com/ffxi/Tantra_Gaiters)
      - [ ] [Tantra Hose](https://www.bg-wiki.com/ffxi/Tantra_Hose)
      - [ ] [Tantra Crown](https://www.bg-wiki.com/ffxi/Tantra_Crown)
      - [ ] [Tantra Gloves](https://www.bg-wiki.com/ffxi/Tantra_Gloves)
      - [ ] [Tantra Cyclas](https://www.bg-wiki.com/ffxi/Tantra_Cyclas)
    - [ ] [Tantra Attire Set +1](https://www.bg-wiki.com/ffxi/Tantra_Attire_Set_%2B1)
      - [ ] [Tantra Gaiters +1](https://www.bg-wiki.com/ffxi/Tantra_Gaiters_%2B1)
      - [ ] [Tantra Hose +1](https://www.bg-wiki.com/ffxi/Tantra_Hose_%2B1)
      - [ ] [Tantra Crown +1](https://www.bg-wiki.com/ffxi/Tantra_Crown_%2B1)
      - [ ] [Tantra Gloves +1](https://www.bg-wiki.com/ffxi/Tantra_Gloves_%2B1)
      - [ ] [Tantra Cyclas +1](https://www.bg-wiki.com/ffxi/Tantra_Cyclas_%2B1)
    - [ ] [Tantra Attire Set +2](https://www.bg-wiki.com/ffxi/Tantra_Attire_Set_%2B2)
      - [ ] [Tantra Gaiters +2](https://www.bg-wiki.com/ffxi/Tantra_Gaiters_%2B2)
      - [ ] [Tantra Hose +2](https://www.bg-wiki.com/ffxi/Tantra_Hose_%2B2)
      - [ ] [Tantra Crown +2](https://www.bg-wiki.com/ffxi/Tantra_Crown_%2B2)
      - [ ] [Tantra Gloves +2](https://www.bg-wiki.com/ffxi/Tantra_Gloves_%2B2)
      - [ ] [Tantra Cyclas +2](https://www.bg-wiki.com/ffxi/Tantra_Cyclas_%2B2)
    - [ ] [Bhikku Attire Set](https://www.bg-wiki.com/ffxi/Bhikku_Attire_Set)
      - [ ] [Bhikku Crown](https://www.bg-wiki.com/ffxi/Bhikku_Crown)
      - [ ] [Bhikku Cyclas](https://www.bg-wiki.com/ffxi/Bhikku_Cyclas)
      - [ ] [Bhikku Gloves](https://www.bg-wiki.com/ffxi/Bhikku_Gloves)
      - [ ] [Bhikku Hose](https://www.bg-wiki.com/ffxi/Bhikku_Hose)
      - [ ] [Bhikku Gaiters](https://www.bg-wiki.com/ffxi/Bhikku_Gaiters)
    - [ ] [Bhikku Attire Set +1](https://www.bg-wiki.com/ffxi/Bhikku_Attire_Set_%2B1)
      - [ ] [Bhikku Crown +1](https://www.bg-wiki.com/ffxi/Bhikku_Crown_%2B1)
      - [ ] [Bhikku Cyclas +1](https://www.bg-wiki.com/ffxi/Bhikku_Cyclas_%2B1)
      - [ ] [Bhikku Gloves +1](https://www.bg-wiki.com/ffxi/Bhikku_Gloves_%2B1)
      - [ ] [Bhikku Hose +1](https://www.bg-wiki.com/ffxi/Bhikku_Hose_%2B1)
      - [ ] [Bhikku Gaiters +1](https://www.bg-wiki.com/ffxi/Bhikku_Gaiters_%2B1)
    - [ ] [Bhikku Attire Set +2](https://www.bg-wiki.com/ffxi/Bhikku_Attire_Set_%2B2)
      - [ ] [Bhikku Crown +2](https://www.bg-wiki.com/ffxi/Bhikku_Crown_%2B2)
      - [ ] [Bhikku Cyclas +2](https://www.bg-wiki.com/ffxi/Bhikku_Cyclas_%2B2)
      - [ ] [Bhikku Gloves +2](https://www.bg-wiki.com/ffxi/Bhikku_Gloves_%2B2)
      - [ ] [Bhikku Hose +2](https://www.bg-wiki.com/ffxi/Bhikku_Hose_%2B2)
      - [ ] [Bhikku Gaiters +2](https://www.bg-wiki.com/ffxi/Bhikku_Gaiters_%2B2)
    - [ ] [Bhikku Attire Set +3](https://www.bg-wiki.com/ffxi/Bhikku_Attire_Set_%2B3)
      - [ ] [Bhikku Crown +3](https://www.bg-wiki.com/ffxi/Bhikku_Crown_%2B3)
      - [ ] [Bhikku Cyclas +3](https://www.bg-wiki.com/ffxi/Bhikku_Cyclas_%2B3)
      - [ ] [Bhikku Gloves +3](https://www.bg-wiki.com/ffxi/Bhikku_Gloves_%2B3)
      - [ ] [Bhikku Hose +3](https://www.bg-wiki.com/ffxi/Bhikku_Hose_%2B3)
      - [ ] [Bhikku Gaiters +3](https://www.bg-wiki.com/ffxi/Bhikku_Gaiters_%2B3)
    - [ ] Accessories
      - [ ] [Tantra Necklace](https://www.bg-wiki.com/ffxi/Tantra_Necklace)
      - [ ] [Tantra Tathlum](https://www.bg-wiki.com/ffxi/Tantra_Tathlum)
      - [ ] [Tantra Earring](https://www.bg-wiki.com/ffxi/Tantra_Earring)
      - [ ] [Bhikku Earring](https://www.bg-wiki.com/ffxi/Bhikku_Earring)
      - [ ] [Bhikku Earring +1](https://www.bg-wiki.com/ffxi/Bhikku_Earring_%2B1)
      - [ ] [Bhikku Earring +2](https://www.bg-wiki.com/ffxi/Bhikku_Earring_%2B2)
