### ISSUE TITLE
WHM JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4392]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [WHM](https://www.bg-wiki.com/ffxi/White_Mage)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Healer's Attire Set](https://www.bg-wiki.com/ffxi/Healer%27s_Attire_Set)
      - [ ] [Healer's Duckbills](https://www.bg-wiki.com/ffxi/Healer%27s_Duckbills)
      - [ ] [Healer's Cap](https://www.bg-wiki.com/ffxi/Healer%27s_Cap)
      - [ ] [Healer's Pantaloons](https://www.bg-wiki.com/ffxi/Healer%27s_Pantaloons)
      - [ ] [Healer's Bliaut](https://www.bg-wiki.com/ffxi/Healer%27s_Bliaut)
      - [ ] [Healer's Mitts](https://www.bg-wiki.com/ffxi/Healer%27s_Mitts)
    - [ ] [Healer's Attire Set +1](https://www.bg-wiki.com/ffxi/Healer%27s_Attire_Set_%2B1)
      - [ ] [Healer's Duckbills +1](https://www.bg-wiki.com/ffxi/Healer%27s_Duckbills_%2B1)
      - [ ] [Healer's Cap +1](https://www.bg-wiki.com/ffxi/Healer%27s_Cap_%2B1)
      - [ ] [Healer's Pantaloons +1](https://www.bg-wiki.com/ffxi/Healer%27s_Pantaloons_%2B1)
      - [ ] [Healer's Bliaut +1](https://www.bg-wiki.com/ffxi/Healer%27s_Bliaut_%2B1)
      - [ ] [Healer's Mitts +1](https://www.bg-wiki.com/ffxi/Healer%27s_Mitts_%2B1)
    - [ ] [Theophany Attire Set](https://www.bg-wiki.com/ffxi/Theophany_Attire_Set)
      - [ ] [Theophany Cap](https://www.bg-wiki.com/ffxi/Theophany_Cap)
      - [ ] [Theophany Bliaut](https://www.bg-wiki.com/ffxi/Theophany_Bliaut)
      - [ ] [Theophany Mitts](https://www.bg-wiki.com/ffxi/Theophany_Mitts)
      - [ ] [Theophany Pantaloons](https://www.bg-wiki.com/ffxi/Theophany_Pantaloons)
      - [ ] [Theophany Duckbills](https://www.bg-wiki.com/ffxi/Theophany_Duckbills)
    - [ ] [Theophany Attire Set +1](https://www.bg-wiki.com/ffxi/Theophany_Attire_Set_%2B1)
      - [ ] [Theophany Cap +1](https://www.bg-wiki.com/ffxi/Theophany_Cap_%2B1)
      - [ ] [Theophany Bliaut +1](https://www.bg-wiki.com/ffxi/Theophany_Bliaut_%2B1)
      - [ ] [Theophany Mitts +1](https://www.bg-wiki.com/ffxi/Theophany_Mitts_%2B1)
      - [ ] [Theophany Pantaloons +1](https://www.bg-wiki.com/ffxi/Theophany_Pantaloons_%2B1)
      - [ ] [Theophany Duckbills +1](https://www.bg-wiki.com/ffxi/Theophany_Duckbills_%2B1)
    - [ ] [Theophany Attire Set +2](https://www.bg-wiki.com/ffxi/Theophany_Attire_Set_%2B2)
      - [ ] [Theophany Cap +2](https://www.bg-wiki.com/ffxi/Theophany_Cap_%2B2)
      - [ ] [Theophany Bliaut +2](https://www.bg-wiki.com/ffxi/Theophany_Bliaut_%2B2)
      - [ ] [Theophany Mitts +2](https://www.bg-wiki.com/ffxi/Theophany_Mitts_%2B2)
      - [ ] [Theophany Pantaloons +2](https://www.bg-wiki.com/ffxi/Theophany_Pantaloons_%2B2)
      - [ ] [Theophany Duckbills +2](https://www.bg-wiki.com/ffxi/Theophany_Duckbills_%2B2)
    - [ ] [Theophany Attire Set +3](https://www.bg-wiki.com/ffxi/Theophany_Attire_Set_%2B3)
      - [ ] [Theophany Cap +3](https://www.bg-wiki.com/ffxi/Theophany_Cap_%2B3)
      - [ ] [Theophany Bliaut +3](https://www.bg-wiki.com/ffxi/Theophany_Bliaut_%2B3)
      - [ ] [Theophany Mitts +3](https://www.bg-wiki.com/ffxi/Theophany_Mitts_%2B3)
      - [ ] [Theophany Pantaloons +3](https://www.bg-wiki.com/ffxi/Theophany_Pantaloons_%2B3)
      - [ ] [Theophany Duckbills +3](https://www.bg-wiki.com/ffxi/Theophany_Duckbills_%2B3)
    - [ ] [Blessed Hammer](https://www.bg-wiki.com/ffxi/Blessed_Hammer)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Cleric's Attire Set](https://www.bg-wiki.com/ffxi/Cleric%27s_Attire_Set)
      - [ ] [Cleric's Duckbills](https://www.bg-wiki.com/ffxi/Cleric%27s_Duckbills)
      - [ ] [Cleric's Cap](https://www.bg-wiki.com/ffxi/Cleric%27s_Cap)
      - [ ] [Cleric's Pantaloons](https://www.bg-wiki.com/ffxi/Cleric%27s_Pantaloons)
      - [ ] [Cleric's Bliaut](https://www.bg-wiki.com/ffxi/Cleric%27s_Bliaut)
      - [ ] [Cleric's Mitts](https://www.bg-wiki.com/ffxi/Cleric%27s_Mitts)
    - [ ] [Cleric's Attire Set +1](https://www.bg-wiki.com/ffxi/Cleric%27s_Attire_Set_%2B1)
      - [ ] [Cleric's Duckbills +1](https://www.bg-wiki.com/ffxi/Cleric%27s_Duckbills_%2B1)
      - [ ] [Cleric's Cap +1](https://www.bg-wiki.com/ffxi/Cleric%27s_Cap_%2B1)
      - [ ] [Cleric's Pantaloons +1](https://www.bg-wiki.com/ffxi/Cleric%27s_Pantaloons_%2B1)
      - [ ] [Cleric's Bliaut +1](https://www.bg-wiki.com/ffxi/Cleric%27s_Bliaut_%2B1)
      - [ ] [Cleric's Mitts +1](https://www.bg-wiki.com/ffxi/Cleric%27s_Mitts_%2B1)
    - [ ] [Cleric's Attire Set +2](https://www.bg-wiki.com/ffxi/Cleric%27s_Attire_Set_%2B2)
      - [ ] [Cleric's Duckbills +2](https://www.bg-wiki.com/ffxi/Cleric%27s_Duckbills_%2B2)
      - [ ] [Cleric's Cap +2](https://www.bg-wiki.com/ffxi/Cleric%27s_Cap_%2B2)
      - [ ] [Cleric's Pantaloons +2](https://www.bg-wiki.com/ffxi/Cleric%27s_Pantaloons_%2B2)
      - [ ] [Cleric's Bliaut +2](https://www.bg-wiki.com/ffxi/Cleric%27s_Bliaut_%2B2)
      - [ ] [Cleric's Mitts +2](https://www.bg-wiki.com/ffxi/Cleric%27s_Mitts_%2B2)
    - [ ] [Piety Attire Set](https://www.bg-wiki.com/ffxi/Piety_Attire_Set)
      - [ ] [Piety Cap](https://www.bg-wiki.com/ffxi/Piety_Cap)
      - [ ] [Piety Bliaut](https://www.bg-wiki.com/ffxi/Piety_Bliaut)
      - [ ] [Piety Mitts](https://www.bg-wiki.com/ffxi/Piety_Mitts)
      - [ ] [Piety Pantaloons](https://www.bg-wiki.com/ffxi/Piety_Pantaloons)
      - [ ] [Piety Duckbills](https://www.bg-wiki.com/ffxi/Piety_Duckbills)
    - [ ] [Piety Attire Set +1](https://www.bg-wiki.com/ffxi/Piety_Attire_Set_%2B1)
      - [ ] [Piety Cap +1](https://www.bg-wiki.com/ffxi/Piety_Cap_%2B1)
      - [ ] [Piety Bliaut +1](https://www.bg-wiki.com/ffxi/Piety_Bliaut_%2B1)
      - [ ] [Piety Mitts +1](https://www.bg-wiki.com/ffxi/Piety_Mitts_%2B1)
      - [ ] [Piety Pantaloons +1](https://www.bg-wiki.com/ffxi/Piety_Pantaloons_%2B1)
      - [ ] [Piety Duckbills +1](https://www.bg-wiki.com/ffxi/Piety_Duckbills_%2B1)
    - [ ] [Piety Attire Set +2](https://www.bg-wiki.com/ffxi/Piety_Attire_Set_%2B2)
      - [ ] [Piety Cap +2](https://www.bg-wiki.com/ffxi/Piety_Cap_%2B2)
      - [ ] [Piety Bliaut +2](https://www.bg-wiki.com/ffxi/Piety_Bliaut_%2B2)
      - [ ] [Piety Mitts +2](https://www.bg-wiki.com/ffxi/Piety_Mitts_%2B2)
      - [ ] [Piety Pantaloons +2](https://www.bg-wiki.com/ffxi/Piety_Pantaloons_%2B2)
      - [ ] [Piety Duckbills +2](https://www.bg-wiki.com/ffxi/Piety_Duckbills_%2B2)
    - [ ] [Piety Attire Set +3](https://www.bg-wiki.com/ffxi/Piety_Attire_Set_%2B3)
      - [ ] [Piety Cap +3](https://www.bg-wiki.com/ffxi/Piety_Cap_%2B3)
      - [ ] [Piety Bliaut +3](https://www.bg-wiki.com/ffxi/Piety_Bliaut_%2B3)
      - [ ] [Piety Mitts +3](https://www.bg-wiki.com/ffxi/Piety_Mitts_%2B3)
      - [ ] [Piety Pantaloons +3](https://www.bg-wiki.com/ffxi/Piety_Pantaloons_%2B3)
      - [ ] [Piety Duckbills +3](https://www.bg-wiki.com/ffxi/Piety_Duckbills_%2B3)
    - [ ] [Cleric's Belt](https://www.bg-wiki.com/ffxi/Cleric%27s_Belt)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Cleric's Torque](https://www.bg-wiki.com/ffxi/Cleric%27s_Torque)
      - [ ] [Cleric's Torque +1](https://www.bg-wiki.com/ffxi/Cleric%27s_Torque_%2B1)
      - [ ] [Cleric's Torque +2](https://www.bg-wiki.com/ffxi/Cleric%27s_Torque_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Cleric's Wand](https://www.bg-wiki.com/ffxi/Cleric%27s_Wand)
      - [ ] [Piety Wand](https://www.bg-wiki.com/ffxi/Piety_Wand)
      - [ ] [Asclepius](https://www.bg-wiki.com/ffxi/Asclepius)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Orison Attire Set](https://www.bg-wiki.com/ffxi/Orison_Attire_Set)
      - [ ] [Orison Duckbills](https://www.bg-wiki.com/ffxi/Orison_Duckbills)
      - [ ] [Orison Pantaloons](https://www.bg-wiki.com/ffxi/Orison_Pantaloons)
      - [ ] [Orison Cap](https://www.bg-wiki.com/ffxi/Orison_Cap)
      - [ ] [Orison Mitts](https://www.bg-wiki.com/ffxi/Orison_Mitts)
      - [ ] [Orison Bliaut](https://www.bg-wiki.com/ffxi/Orison_Bliaut)
    - [ ] [Orison Attire Set +1](https://www.bg-wiki.com/ffxi/Orison_Attire_Set_%2B1)
      - [ ] [Orison Duckbills +1](https://www.bg-wiki.com/ffxi/Orison_Duckbills_%2B1)
      - [ ] [Orison Pantaloons +1](https://www.bg-wiki.com/ffxi/Orison_Pantaloons_%2B1)
      - [ ] [Orison Cap +1](https://www.bg-wiki.com/ffxi/Orison_Cap_%2B1)
      - [ ] [Orison Mitts +1](https://www.bg-wiki.com/ffxi/Orison_Mitts_%2B1)
      - [ ] [Orison Bliaut +1](https://www.bg-wiki.com/ffxi/Orison_Bliaut_%2B1)
    - [ ] [Orison Attire Set +2](https://www.bg-wiki.com/ffxi/Orison_Attire_Set_%2B2)
      - [ ] [Orison Duckbills +2](https://www.bg-wiki.com/ffxi/Orison_Duckbills_%2B2)
      - [ ] [Orison Pantaloons +2](https://www.bg-wiki.com/ffxi/Orison_Pantaloons_%2B2)
      - [ ] [Orison Cap +2](https://www.bg-wiki.com/ffxi/Orison_Cap_%2B2)
      - [ ] [Orison Mitts +2](https://www.bg-wiki.com/ffxi/Orison_Mitts_%2B2)
      - [ ] [Orison Bliaut +2](https://www.bg-wiki.com/ffxi/Orison_Bliaut_%2B2)
    - [ ] [Ebers Attire Set](https://www.bg-wiki.com/ffxi/Ebers_Attire_Set)
      - [ ] [Ebers Cap](https://www.bg-wiki.com/ffxi/Ebers_Cap)
      - [ ] [Ebers Bliaut](https://www.bg-wiki.com/ffxi/Ebers_Bliaut)
      - [ ] [Ebers Mitts](https://www.bg-wiki.com/ffxi/Ebers_Mitts)
      - [ ] [Ebers Pantaloons](https://www.bg-wiki.com/ffxi/Ebers_Pantaloons)
      - [ ] [Ebers Duckbills](https://www.bg-wiki.com/ffxi/Ebers_Duckbills)
    - [ ] [Ebers Attire Set +1](https://www.bg-wiki.com/ffxi/Ebers_Attire_Set_%2B1)
      - [ ] [Ebers Cap +1](https://www.bg-wiki.com/ffxi/Ebers_Cap_%2B1)
      - [ ] [Ebers Bliaut +1](https://www.bg-wiki.com/ffxi/Ebers_Bliaut_%2B1)
      - [ ] [Ebers Mitts +1](https://www.bg-wiki.com/ffxi/Ebers_Mitts_%2B1)
      - [ ] [Ebers Pantaloons +1](https://www.bg-wiki.com/ffxi/Ebers_Pantaloons_%2B1)
      - [ ] [Ebers Duckbills +1](https://www.bg-wiki.com/ffxi/Ebers_Duckbills_%2B1)
    - [ ] [Ebers Attire Set +2](https://www.bg-wiki.com/ffxi/Ebers_Attire_Set_%2B2)
      - [ ] [Ebers Cap +2](https://www.bg-wiki.com/ffxi/Ebers_Cap_%2B2)
      - [ ] [Ebers Bliaut +2](https://www.bg-wiki.com/ffxi/Ebers_Bliaut_%2B2)
      - [ ] [Ebers Mitts +2](https://www.bg-wiki.com/ffxi/Ebers_Mitts_%2B2)
      - [ ] [Ebers Pantaloons +2](https://www.bg-wiki.com/ffxi/Ebers_Pantaloons_%2B2)
      - [ ] [Ebers Duckbills +2](https://www.bg-wiki.com/ffxi/Ebers_Duckbills_%2B2)
    - [ ] [Ebers Attire Set +3](https://www.bg-wiki.com/ffxi/Ebers_Attire_Set_%2B3)
      - [ ] [Ebers Cap +3](https://www.bg-wiki.com/ffxi/Ebers_Cap_%2B3)
      - [ ] [Ebers Bliaut +3](https://www.bg-wiki.com/ffxi/Ebers_Bliaut_%2B3)
      - [ ] [Ebers Mitts +3](https://www.bg-wiki.com/ffxi/Ebers_Mitts_%2B3)
      - [ ] [Ebers Pantaloons +3](https://www.bg-wiki.com/ffxi/Ebers_Pantaloons_%2B3)
      - [ ] [Ebers Duckbills +3](https://www.bg-wiki.com/ffxi/Ebers_Duckbills_%2B3)
    - [ ] Accessories
      - [ ] [Orison Cape](https://www.bg-wiki.com/ffxi/Orison_Cape)
      - [ ] [Orison Locket](https://www.bg-wiki.com/ffxi/Orison_Locket)
      - [ ] [Orison Earring](https://www.bg-wiki.com/ffxi/Orison_Earring)
      - [ ] [Ebers Earring](https://www.bg-wiki.com/ffxi/Ebers_Earring)
      - [ ] [Ebers Earring +1](https://www.bg-wiki.com/ffxi/Ebers_Earring_%2B1)
      - [ ] [Ebers Earring +2](https://www.bg-wiki.com/ffxi/Ebers_Earring_%2B2)
