### ISSUE TITLE
BLM JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4393]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [BLM](https://www.bg-wiki.com/ffxi/Black_Mage)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Wizard's Attire Set](https://www.bg-wiki.com/ffxi/Wizard%27s_Attire_Set)
      - [ ] [Wizard's Sabots](https://www.bg-wiki.com/ffxi/Wizard%27s_Sabots)
      - [ ] [Wizard's Gloves](https://www.bg-wiki.com/ffxi/Wizard%27s_Gloves)
      - [ ] [Wizard's Tonban](https://www.bg-wiki.com/ffxi/Wizard%27s_Tonban)
      - [ ] [Wizard's Coat](https://www.bg-wiki.com/ffxi/Wizard%27s_Coat)
      - [ ] [Wizard's Petasos](https://www.bg-wiki.com/ffxi/Wizard%27s_Petasos)
    - [ ] [Wizard's Attire Set +1](https://www.bg-wiki.com/ffxi/Wizard%27s_Attire_Set_%2B1)
      - [ ] [Wizard's Sabots +1](https://www.bg-wiki.com/ffxi/Wizard%27s_Sabots_%2B1)
      - [ ] [Wizard's Gloves +1](https://www.bg-wiki.com/ffxi/Wizard%27s_Gloves_%2B1)
      - [ ] [Wizard's Tonban +1](https://www.bg-wiki.com/ffxi/Wizard%27s_Tonban_%2B1)
      - [ ] [Wizard's Coat +1](https://www.bg-wiki.com/ffxi/Wizard%27s_Coat_%2B1)
      - [ ] [Wizard's Petasos +1](https://www.bg-wiki.com/ffxi/Wizard%27s_Petasos_%2B1)
    - [ ] [Spaekona's Attire Set](https://www.bg-wiki.com/ffxi/Spaekona%27s_Attire_Set)
      - [ ] [Spaekona's Petasos](https://www.bg-wiki.com/ffxi/Spaekona%27s_Petasos)
      - [ ] [Spaekona's Coat](https://www.bg-wiki.com/ffxi/Spaekona%27s_Coat)
      - [ ] [Spaekona's Gloves](https://www.bg-wiki.com/ffxi/Spaekona%27s_Gloves)
      - [ ] [Spaekona's Tonban](https://www.bg-wiki.com/ffxi/Spaekona%27s_Tonban)
      - [ ] [Spaekona's Sabots](https://www.bg-wiki.com/ffxi/Spaekona%27s_Sabots)
    - [ ] [Spaekona's Attire Set +1](https://www.bg-wiki.com/ffxi/Spaekona%27s_Attire_Set_%2B1)
      - [ ] [Spaekona's Petasos +1](https://www.bg-wiki.com/ffxi/Spaekona%27s_Petasos_%2B1)
      - [ ] [Spaekona's Coat +1](https://www.bg-wiki.com/ffxi/Spaekona%27s_Coat_%2B1)
      - [ ] [Spaekona's Gloves +1](https://www.bg-wiki.com/ffxi/Spaekona%27s_Gloves_%2B1)
      - [ ] [Spaekona's Tonban +1](https://www.bg-wiki.com/ffxi/Spaekona%27s_Tonban_%2B1)
      - [ ] [Spaekona's Sabots +1](https://www.bg-wiki.com/ffxi/Spaekona%27s_Sabots_%2B1)
    - [ ] [Spaekona's Attire Set +2](https://www.bg-wiki.com/ffxi/Spaekona%27s_Attire_Set_%2B2)
      - [ ] [Spaekona's Petasos +2](https://www.bg-wiki.com/ffxi/Spaekona%27s_Petasos_%2B2)
      - [ ] [Spaekona's Coat +2](https://www.bg-wiki.com/ffxi/Spaekona%27s_Coat_%2B2)
      - [ ] [Spaekona's Gloves +2](https://www.bg-wiki.com/ffxi/Spaekona%27s_Gloves_%2B2)
      - [ ] [Spaekona's Tonban +2](https://www.bg-wiki.com/ffxi/Spaekona%27s_Tonban_%2B2)
      - [ ] [Spaekona's Sabots +2](https://www.bg-wiki.com/ffxi/Spaekona%27s_Sabots_%2B2)
    - [ ] [Spaekona's Attire Set +3](https://www.bg-wiki.com/ffxi/Spaekona%27s_Attire_Set_%2B3)
      - [ ] [Spaekona's Petasos +3](https://www.bg-wiki.com/ffxi/Spaekona%27s_Petasos_%2B3)
      - [ ] [Spaekona's Coat +3](https://www.bg-wiki.com/ffxi/Spaekona%27s_Coat_%2B3)
      - [ ] [Spaekona's Gloves +3](https://www.bg-wiki.com/ffxi/Spaekona%27s_Gloves_%2B3)
      - [ ] [Spaekona's Tonban +3](https://www.bg-wiki.com/ffxi/Spaekona%27s_Tonban_%2B3)
      - [ ] [Spaekona's Sabots +3](https://www.bg-wiki.com/ffxi/Spaekona%27s_Sabots_%2B3)
    - [ ] [Casting Wand](https://www.bg-wiki.com/ffxi/Casting_Wand)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Sorcerer's Attire Set](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Attire_Set)
      - [ ] [Sorcerer's Sabots](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Sabots)
      - [ ] [Sorcerer's Gloves](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Gloves)
      - [ ] [Sorcerer's Tonban](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Tonban)
      - [ ] [Sorcerer's Coat](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Coat)
      - [ ] [Sorcerer's Petasos](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Petasos)
    - [ ] [Sorcerer's Attire Set +1](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Attire_Set_%2B1)
      - [ ] [Sorcerer's Sabots +1](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Sabots_%2B1)
      - [ ] [Sorcerer's Gloves +1](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Gloves_%2B1)
      - [ ] [Sorcerer's Tonban +1](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Tonban_%2B1)
      - [ ] [Sorcerer's Coat +1](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Coat_%2B1)
      - [ ] [Sorcerer's Petasos +1](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Petasos_%2B1)
    - [ ] [Sorcerer's Attire Set +2](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Attire_Set_%2B2)
      - [ ] [Sorcerer's Sabots +2](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Sabots_%2B2)
      - [ ] [Sorcerer's Gloves +2](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Gloves_%2B2)
      - [ ] [Sorcerer's Tonban +2](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Tonban_%2B2)
      - [ ] [Sorcerer's Coat +2](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Coat_%2B2)
      - [ ] [Sorcerer's Petasos +2](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Petasos_%2B2)
    - [ ] [Archmage's Attire Set](https://www.bg-wiki.com/ffxi/Archmage%27s_Attire_Set)
      - [ ] [Archmage's Petasos](https://www.bg-wiki.com/ffxi/Archmage%27s_Petasos)
      - [ ] [Archmage's Coat](https://www.bg-wiki.com/ffxi/Archmage%27s_Coat)
      - [ ] [Archmage's Gloves](https://www.bg-wiki.com/ffxi/Archmage%27s_Gloves)
      - [ ] [Archmage's Tonban](https://www.bg-wiki.com/ffxi/Archmage%27s_Tonban)
      - [ ] [Archmage's Sabots](https://www.bg-wiki.com/ffxi/Archmage%27s_Sabots)
    - [ ] [Archmage's Attire Set +1](https://www.bg-wiki.com/ffxi/Archmage%27s_Attire_Set_%2B1)
      - [ ] [Archmage's Petasos +1](https://www.bg-wiki.com/ffxi/Archmage%27s_Petasos_%2B1)
      - [ ] [Archmage's Coat +1](https://www.bg-wiki.com/ffxi/Archmage%27s_Coat_%2B1)
      - [ ] [Archmage's Gloves +1](https://www.bg-wiki.com/ffxi/Archmage%27s_Gloves_%2B1)
      - [ ] [Archmage's Tonban +1](https://www.bg-wiki.com/ffxi/Archmage%27s_Tonban_%2B1)
      - [ ] [Archmage's Sabots +1](https://www.bg-wiki.com/ffxi/Archmage%27s_Sabots_%2B1)
    - [ ] [Archmage's Attire Set +2](https://www.bg-wiki.com/ffxi/Archmage%27s_Attire_Set_%2B2)
      - [ ] [Archmage's Petasos +2](https://www.bg-wiki.com/ffxi/Archmage%27s_Petasos_%2B2)
      - [ ] [Archmage's Coat +2](https://www.bg-wiki.com/ffxi/Archmage%27s_Coat_%2B2)
      - [ ] [Archmage's Gloves +2](https://www.bg-wiki.com/ffxi/Archmage%27s_Gloves_%2B2)
      - [ ] [Archmage's Tonban +2](https://www.bg-wiki.com/ffxi/Archmage%27s_Tonban_%2B2)
      - [ ] [Archmage's Sabots +2](https://www.bg-wiki.com/ffxi/Archmage%27s_Sabots_%2B2)
    - [ ] [Archmage's Attire Set +3](https://www.bg-wiki.com/ffxi/Archmage%27s_Attire_Set_%2B3)
      - [ ] [Archmage's Petasos +3](https://www.bg-wiki.com/ffxi/Archmage%27s_Petasos_%2B3)
      - [ ] [Archmage's Coat +3](https://www.bg-wiki.com/ffxi/Archmage%27s_Coat_%2B3)
      - [ ] [Archmage's Gloves +3](https://www.bg-wiki.com/ffxi/Archmage%27s_Gloves_%2B3)
      - [ ] [Archmage's Tonban +3](https://www.bg-wiki.com/ffxi/Archmage%27s_Tonban_%2B3)
      - [ ] [Archmage's Sabots +3](https://www.bg-wiki.com/ffxi/Archmage%27s_Sabots_%2B3)
    - [ ] [Sorcerer's Belt](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Belt)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Sorcerer's Stole](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Stole)
      - [ ] [Sorcerer's Stole +1](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Stole_%2B1)
      - [ ] [Sorcerer's Stole +2](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Stole_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Sorcerer's Staff](https://www.bg-wiki.com/ffxi/Sorcerer%27s_Staff)
      - [ ] [Archmage's Staff](https://www.bg-wiki.com/ffxi/Archmage%27s_Staff)
      - [ ] [Kaumodaki](https://www.bg-wiki.com/ffxi/Kaumodaki)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Goetia Attire Set](https://www.bg-wiki.com/ffxi/Goetia_Attire_Set)
      - [ ] [Goetia Sabots](https://www.bg-wiki.com/ffxi/Goetia_Sabots)
      - [ ] [Goetia Chausses](https://www.bg-wiki.com/ffxi/Goetia_Chausses)
      - [ ] [Goetia Petasos](https://www.bg-wiki.com/ffxi/Goetia_Petasos)
      - [ ] [Goetia Gloves](https://www.bg-wiki.com/ffxi/Goetia_Gloves)
      - [ ] [Goetia Coat](https://www.bg-wiki.com/ffxi/Goetia_Coat)
    - [ ] [Goetia Attire Set +1](https://www.bg-wiki.com/ffxi/Goetia_Attire_Set_%2B1)
      - [ ] [Goetia Sabots +1](https://www.bg-wiki.com/ffxi/Goetia_Sabots_%2B1)
      - [ ] [Goetia Chausses +1](https://www.bg-wiki.com/ffxi/Goetia_Chausses_%2B1)
      - [ ] [Goetia Petasos +1](https://www.bg-wiki.com/ffxi/Goetia_Petasos_%2B1)
      - [ ] [Goetia Gloves +1](https://www.bg-wiki.com/ffxi/Goetia_Gloves_%2B1)
      - [ ] [Goetia Coat +1](https://www.bg-wiki.com/ffxi/Goetia_Coat_%2B1)
    - [ ] [Goetia Attire Set +2](https://www.bg-wiki.com/ffxi/Goetia_Attire_Set_%2B2)
      - [ ] [Goetia Sabots +2](https://www.bg-wiki.com/ffxi/Goetia_Sabots_%2B2)
      - [ ] [Goetia Chausses +2](https://www.bg-wiki.com/ffxi/Goetia_Chausses_%2B2)
      - [ ] [Goetia Petasos +2](https://www.bg-wiki.com/ffxi/Goetia_Petasos_%2B2)
      - [ ] [Goetia Gloves +2](https://www.bg-wiki.com/ffxi/Goetia_Gloves_%2B2)
      - [ ] [Goetia Coat +2](https://www.bg-wiki.com/ffxi/Goetia_Coat_%2B2)
    - [ ] [Wicce Attire Set](https://www.bg-wiki.com/ffxi/Wicce_Attire_Set)
      - [ ] [Wicce Petasos](https://www.bg-wiki.com/ffxi/Wicce_Petasos)
      - [ ] [Wicce Coat](https://www.bg-wiki.com/ffxi/Wicce_Coat)
      - [ ] [Wicce Gloves](https://www.bg-wiki.com/ffxi/Wicce_Gloves)
      - [ ] [Wicce Chausses](https://www.bg-wiki.com/ffxi/Wicce_Chausses)
      - [ ] [Wicce Sabots](https://www.bg-wiki.com/ffxi/Wicce_Sabots)
    - [ ] [Wicce Attire Set +1](https://www.bg-wiki.com/ffxi/Wicce_Attire_Set_%2B1)
      - [ ] [Wicce Petasos +1](https://www.bg-wiki.com/ffxi/Wicce_Petasos_%2B1)
      - [ ] [Wicce Coat +1](https://www.bg-wiki.com/ffxi/Wicce_Coat_%2B1)
      - [ ] [Wicce Gloves +1](https://www.bg-wiki.com/ffxi/Wicce_Gloves_%2B1)
      - [ ] [Wicce Chausses +1](https://www.bg-wiki.com/ffxi/Wicce_Chausses_%2B1)
      - [ ] [Wicce Sabots +1](https://www.bg-wiki.com/ffxi/Wicce_Sabots_%2B1)
    - [ ] [Wicce Attire Set +2](https://www.bg-wiki.com/ffxi/Wicce_Attire_Set_%2B2)
      - [ ] [Wicce Petasos +2](https://www.bg-wiki.com/ffxi/Wicce_Petasos_%2B2)
      - [ ] [Wicce Coat +2](https://www.bg-wiki.com/ffxi/Wicce_Coat_%2B2)
      - [ ] [Wicce Gloves +2](https://www.bg-wiki.com/ffxi/Wicce_Gloves_%2B2)
      - [ ] [Wicce Chausses +2](https://www.bg-wiki.com/ffxi/Wicce_Chausses_%2B2)
      - [ ] [Wicce Sabots +2](https://www.bg-wiki.com/ffxi/Wicce_Sabots_%2B2)
    - [ ] [Wicce Attire Set +3](https://www.bg-wiki.com/ffxi/Wicce_Attire_Set_%2B3)
      - [ ] [Wicce Petasos +3](https://www.bg-wiki.com/ffxi/Wicce_Petasos_%2B3)
      - [ ] [Wicce Coat +3](https://www.bg-wiki.com/ffxi/Wicce_Coat_%2B3)
      - [ ] [Wicce Gloves +3](https://www.bg-wiki.com/ffxi/Wicce_Gloves_%2B3)
      - [ ] [Wicce Chausses +3](https://www.bg-wiki.com/ffxi/Wicce_Chausses_%2B3)
      - [ ] [Wicce Sabots +3](https://www.bg-wiki.com/ffxi/Wicce_Sabots_%2B3)
    - [ ] Accessories
      - [ ] [Goetia Chain](https://www.bg-wiki.com/ffxi/Goetia_Chain)
      - [ ] [Goetia Mantle](https://www.bg-wiki.com/ffxi/Goetia_Mantle)
      - [ ] [Goetia Earring](https://www.bg-wiki.com/ffxi/Goetia_Earring)
      - [ ] [Wicce Earring](https://www.bg-wiki.com/ffxi/Wicce_Earring)
      - [ ] [Wicce Earring +1](https://www.bg-wiki.com/ffxi/Wicce_Earring_%2B1)
      - [ ] [Wicce Earring +2](https://www.bg-wiki.com/ffxi/Wicce_Earring_%2B2)
