### ISSUE TITLE
RDM JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4394]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [RDM](https://www.bg-wiki.com/ffxi/Red_Mage)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Warlock's Armor Set](https://www.bg-wiki.com/ffxi/Warlock%27s_Armor_Set)
      - [ ] [Warlock's Boots](https://www.bg-wiki.com/ffxi/Warlock%27s_Boots)
      - [ ] [Warlock's Gloves](https://www.bg-wiki.com/ffxi/Warlock%27s_Gloves)
      - [ ] [Warlock's Tights](https://www.bg-wiki.com/ffxi/Warlock%27s_Tights)
      - [ ] [Warlock's Tabard](https://www.bg-wiki.com/ffxi/Warlock%27s_Tabard)
      - [ ] [Warlock's Chapeau](https://www.bg-wiki.com/ffxi/Warlock%27s_Chapeau)
    - [ ] [Warlock's Armor Set +1](https://www.bg-wiki.com/ffxi/Warlock%27s_Armor_Set_%2B1)
      - [ ] [Warlock's Boots +1](https://www.bg-wiki.com/ffxi/Warlock%27s_Boots_%2B1)
      - [ ] [Warlock's Gloves +1](https://www.bg-wiki.com/ffxi/Warlock%27s_Gloves_%2B1)
      - [ ] [Warlock's Tights +1](https://www.bg-wiki.com/ffxi/Warlock%27s_Tights_%2B1)
      - [ ] [Warlock's Tabard +1](https://www.bg-wiki.com/ffxi/Warlock%27s_Tabard_%2B1)
      - [ ] [Warlock's Chapeau +1](https://www.bg-wiki.com/ffxi/Warlock%27s_Chapeau_%2B1)
    - [ ] [Atrophy Armor Set](https://www.bg-wiki.com/ffxi/Atrophy_Armor_Set)
      - [ ] [Atrophy Chapeau](https://www.bg-wiki.com/ffxi/Atrophy_Chapeau)
      - [ ] [Atrophy Tabard](https://www.bg-wiki.com/ffxi/Atrophy_Tabard)
      - [ ] [Atrophy Gloves](https://www.bg-wiki.com/ffxi/Atrophy_Gloves)
      - [ ] [Atrophy Tights](https://www.bg-wiki.com/ffxi/Atrophy_Tights)
      - [ ] [Atrophy Boots](https://www.bg-wiki.com/ffxi/Atrophy_Boots)
    - [ ] [Atrophy Armor Set +1](https://www.bg-wiki.com/ffxi/Atrophy_Armor_Set_%2B1)
      - [ ] [Atrophy Chapeau +1](https://www.bg-wiki.com/ffxi/Atrophy_Chapeau_%2B1)
      - [ ] [Atrophy Tabard +1](https://www.bg-wiki.com/ffxi/Atrophy_Tabard_%2B1)
      - [ ] [Atrophy Gloves +1](https://www.bg-wiki.com/ffxi/Atrophy_Gloves_%2B1)
      - [ ] [Atrophy Tights +1](https://www.bg-wiki.com/ffxi/Atrophy_Tights_%2B1)
      - [ ] [Atrophy Boots +1](https://www.bg-wiki.com/ffxi/Atrophy_Boots_%2B1)
    - [ ] [Atrophy Armor Set +2](https://www.bg-wiki.com/ffxi/Atrophy_Armor_Set_%2B2)
      - [ ] [Atrophy Chapeau +2](https://www.bg-wiki.com/ffxi/Atrophy_Chapeau_%2B2)
      - [ ] [Atrophy Tabard +2](https://www.bg-wiki.com/ffxi/Atrophy_Tabard_%2B2)
      - [ ] [Atrophy Gloves +2](https://www.bg-wiki.com/ffxi/Atrophy_Gloves_%2B2)
      - [ ] [Atrophy Tights +2](https://www.bg-wiki.com/ffxi/Atrophy_Tights_%2B2)
      - [ ] [Atrophy Boots +2](https://www.bg-wiki.com/ffxi/Atrophy_Boots_%2B2)
    - [ ] [Atrophy Armor Set +3](https://www.bg-wiki.com/ffxi/Atrophy_Armor_Set_%2B3)
      - [ ] [Atrophy Chapeau +3](https://www.bg-wiki.com/ffxi/Atrophy_Chapeau_%2B3)
      - [ ] [Atrophy Tabard +3](https://www.bg-wiki.com/ffxi/Atrophy_Tabard_%2B3)
      - [ ] [Atrophy Gloves +3](https://www.bg-wiki.com/ffxi/Atrophy_Gloves_%2B3)
      - [ ] [Atrophy Tights +3](https://www.bg-wiki.com/ffxi/Atrophy_Tights_%2B3)
      - [ ] [Atrophy Boots +3](https://www.bg-wiki.com/ffxi/Atrophy_Boots_%2B3)
    - [ ] [Fencing Degen](https://www.bg-wiki.com/ffxi/Fencing_Degen)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Duelist's Armor Set](https://www.bg-wiki.com/ffxi/Duelist%27s_Armor_Set)
      - [ ] [Duelist's Boots](https://www.bg-wiki.com/ffxi/Duelist%27s_Boots)
      - [ ] [Duelist's Gloves](https://www.bg-wiki.com/ffxi/Duelist%27s_Gloves)
      - [ ] [Duelist's Tights](https://www.bg-wiki.com/ffxi/Duelist%27s_Tights)
      - [ ] [Duelist's Tabard](https://www.bg-wiki.com/ffxi/Duelist%27s_Tabard)
      - [ ] [Duelist's Chapeau](https://www.bg-wiki.com/ffxi/Duelist%27s_Chapeau)
    - [ ] [Duelist's Armor Set +1](https://www.bg-wiki.com/ffxi/Duelist%27s_Armor_Set_%2B1)
      - [ ] [Duelist's Boots +1](https://www.bg-wiki.com/ffxi/Duelist%27s_Boots_%2B1)
      - [ ] [Duelist's Gloves +1](https://www.bg-wiki.com/ffxi/Duelist%27s_Gloves_%2B1)
      - [ ] [Duelist's Tights +1](https://www.bg-wiki.com/ffxi/Duelist%27s_Tights_%2B1)
      - [ ] [Duelist's Tabard +1](https://www.bg-wiki.com/ffxi/Duelist%27s_Tabard_%2B1)
      - [ ] [Duelist's Chapeau +1](https://www.bg-wiki.com/ffxi/Duelist%27s_Chapeau_%2B1)
    - [ ] [Duelist's Armor Set +2](https://www.bg-wiki.com/ffxi/Duelist%27s_Armor_Set_%2B2)
      - [ ] [Duelist's Boots +2](https://www.bg-wiki.com/ffxi/Duelist%27s_Boots_%2B2)
      - [ ] [Duelist's Gloves +2](https://www.bg-wiki.com/ffxi/Duelist%27s_Gloves_%2B2)
      - [ ] [Duelist's Tights +2](https://www.bg-wiki.com/ffxi/Duelist%27s_Tights_%2B2)
      - [ ] [Duelist's Tabard +2](https://www.bg-wiki.com/ffxi/Duelist%27s_Tabard_%2B2)
      - [ ] [Duelist's Chapeau +2](https://www.bg-wiki.com/ffxi/Duelist%27s_Chapeau_%2B2)
    - [ ] [Vitiation Armor Set](https://www.bg-wiki.com/ffxi/Vitiation_Armor_Set)
      - [ ] [Vitiation Chapeau](https://www.bg-wiki.com/ffxi/Vitiation_Chapeau)
      - [ ] [Vitiation Tabard](https://www.bg-wiki.com/ffxi/Vitiation_Tabard)
      - [ ] [Vitiation Gloves](https://www.bg-wiki.com/ffxi/Vitiation_Gloves)
      - [ ] [Vitiation Tights](https://www.bg-wiki.com/ffxi/Vitiation_Tights)
      - [ ] [Vitiation Boots](https://www.bg-wiki.com/ffxi/Vitiation_Boots)
    - [ ] [Vitiation Armor Set +1](https://www.bg-wiki.com/ffxi/Vitiation_Armor_Set_%2B1)
      - [ ] [Vitiation Chapeau +1](https://www.bg-wiki.com/ffxi/Vitiation_Chapeau_%2B1)
      - [ ] [Vitiation Tabard +1](https://www.bg-wiki.com/ffxi/Vitiation_Tabard_%2B1)
      - [ ] [Vitiation Gloves +1](https://www.bg-wiki.com/ffxi/Vitiation_Gloves_%2B1)
      - [ ] [Vitiation Tights +1](https://www.bg-wiki.com/ffxi/Vitiation_Tights_%2B1)
      - [ ] [Vitiation Boots +1](https://www.bg-wiki.com/ffxi/Vitiation_Boots_%2B1)
    - [ ] [Vitiation Armor Set +2](https://www.bg-wiki.com/ffxi/Vitiation_Armor_Set_%2B2)
      - [ ] [Vitiation Chapeau +2](https://www.bg-wiki.com/ffxi/Vitiation_Chapeau_%2B2)
      - [ ] [Vitiation Tabard +2](https://www.bg-wiki.com/ffxi/Vitiation_Tabard_%2B2)
      - [ ] [Vitiation Gloves +2](https://www.bg-wiki.com/ffxi/Vitiation_Gloves_%2B2)
      - [ ] [Vitiation Tights +2](https://www.bg-wiki.com/ffxi/Vitiation_Tights_%2B2)
      - [ ] [Vitiation Boots +2](https://www.bg-wiki.com/ffxi/Vitiation_Boots_%2B2)
    - [ ] [Vitiation Armor Set +3](https://www.bg-wiki.com/ffxi/Vitiation_Armor_Set_%2B3)
      - [ ] [Vitiation Chapeau +3](https://www.bg-wiki.com/ffxi/Vitiation_Chapeau_%2B3)
      - [ ] [Vitiation Tabard +3](https://www.bg-wiki.com/ffxi/Vitiation_Tabard_%2B3)
      - [ ] [Vitiation Gloves +3](https://www.bg-wiki.com/ffxi/Vitiation_Gloves_%2B3)
      - [ ] [Vitiation Tights +3](https://www.bg-wiki.com/ffxi/Vitiation_Tights_%2B3)
      - [ ] [Vitiation Boots +3](https://www.bg-wiki.com/ffxi/Vitiation_Boots_%2B3)
    - [ ] [Duelist's Belt](https://www.bg-wiki.com/ffxi/Duelist%27s_Belt)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Duelist's Torque](https://www.bg-wiki.com/ffxi/Duelist%27s_Torque)
      - [ ] [Duelist's Torque +1](https://www.bg-wiki.com/ffxi/Duelist%27s_Torque_%2B1)
      - [ ] [Duelist's Torque +2](https://www.bg-wiki.com/ffxi/Duelist%27s_Torque_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Duelist's Sword](https://www.bg-wiki.com/ffxi/Duelist%27s_Sword)
      - [ ] [Vitiation Sword](https://www.bg-wiki.com/ffxi/Vitiation_Sword)
      - [ ] [Crocea Mors](https://www.bg-wiki.com/ffxi/Crocea_Mors)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Estoqueur's Armor Set](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Armor_Set)
      - [ ] [Estoqueur's Houseaux](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Houseaux)
      - [ ] [Estoqueur's Fuseau](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Fuseau)
      - [ ] [Estoqueur's Chappel](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Chappel)
      - [ ] [Estoqueur's Gantherots](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Gantherots)
      - [ ] [Estoqueur's Sayon](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Sayon)
    - [ ] [Estoqueur's Armor Set +1](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Armor_Set_%2B1)
      - [ ] [Estoqueur's Houseaux +1](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Houseaux_%2B1)
      - [ ] [Estoqueur's Fuseau +1](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Fuseau_%2B1)
      - [ ] [Estoqueur's Chappel +1](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Chappel_%2B1)
      - [ ] [Estoqueur's Gantherots +1](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Gantherots_%2B1)
      - [ ] [Estoqueur's Sayon +1](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Sayon_%2B1)
    - [ ] [Estoqueur's Armor Set +2](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Armor_Set_%2B2)
      - [ ] [Estoqueur's Houseaux +2](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Houseaux_%2B2)
      - [ ] [Estoqueur's Fuseau +2](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Fuseau_%2B2)
      - [ ] [Estoqueur's Chappel +2](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Chappel_%2B2)
      - [ ] [Estoqueur's Gantherots +2](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Gantherots_%2B2)
      - [ ] [Estoqueur's Sayon +2](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Sayon_%2B2)
    - [ ] [Lethargy Armor Set](https://www.bg-wiki.com/ffxi/Lethargy_Armor_Set)
      - [ ] [Lethargy Chappel](https://www.bg-wiki.com/ffxi/Lethargy_Chappel)
      - [ ] [Lethargy Sayon](https://www.bg-wiki.com/ffxi/Lethargy_Sayon)
      - [ ] [Lethargy Gantherots](https://www.bg-wiki.com/ffxi/Lethargy_Gantherots)
      - [ ] [Lethargy Fuseau](https://www.bg-wiki.com/ffxi/Lethargy_Fuseau)
      - [ ] [Lethargy Houseaux](https://www.bg-wiki.com/ffxi/Lethargy_Houseaux)
    - [ ] [Lethargy Armor Set +1](https://www.bg-wiki.com/ffxi/Lethargy_Armor_Set_%2B1)
      - [ ] [Lethargy Chappel +1](https://www.bg-wiki.com/ffxi/Lethargy_Chappel_%2B1)
      - [ ] [Lethargy Sayon +1](https://www.bg-wiki.com/ffxi/Lethargy_Sayon_%2B1)
      - [ ] [Lethargy Gantherots +1](https://www.bg-wiki.com/ffxi/Lethargy_Gantherots_%2B1)
      - [ ] [Lethargy Fuseau +1](https://www.bg-wiki.com/ffxi/Lethargy_Fuseau_%2B1)
      - [ ] [Lethargy Houseaux +1](https://www.bg-wiki.com/ffxi/Lethargy_Houseaux_%2B1)
    - [ ] [Lethargy Armor Set +2](https://www.bg-wiki.com/ffxi/Lethargy_Armor_Set_%2B2)
      - [ ] [Lethargy Chappel +2](https://www.bg-wiki.com/ffxi/Lethargy_Chappel_%2B2)
      - [ ] [Lethargy Sayon +2](https://www.bg-wiki.com/ffxi/Lethargy_Sayon_%2B2)
      - [ ] [Lethargy Gantherots +2](https://www.bg-wiki.com/ffxi/Lethargy_Gantherots_%2B2)
      - [ ] [Lethargy Fuseau +2](https://www.bg-wiki.com/ffxi/Lethargy_Fuseau_%2B2)
      - [ ] [Lethargy Houseaux +2](https://www.bg-wiki.com/ffxi/Lethargy_Houseaux_%2B2)
    - [ ] [Lethargy Armor Set +3](https://www.bg-wiki.com/ffxi/Lethargy_Armor_Set_%2B3)
      - [ ] [Lethargy Chappel +3](https://www.bg-wiki.com/ffxi/Lethargy_Chappel_%2B3)
      - [ ] [Lethargy Sayon +3](https://www.bg-wiki.com/ffxi/Lethargy_Sayon_%2B3)
      - [ ] [Lethargy Gantherots +3](https://www.bg-wiki.com/ffxi/Lethargy_Gantherots_%2B3)
      - [ ] [Lethargy Fuseau +3](https://www.bg-wiki.com/ffxi/Lethargy_Fuseau_%2B3)
      - [ ] [Lethargy Houseaux +3](https://www.bg-wiki.com/ffxi/Lethargy_Houseaux_%2B3)
    - [ ] Accessories
      - [ ] [Estoqueur's Collar](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Collar)
      - [ ] [Estoqueur's Cape](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Cape)
      - [ ] [Estoqueur's Earring](https://www.bg-wiki.com/ffxi/Estoqueur%27s_Earring)
      - [ ] [Lethargy Earring](https://www.bg-wiki.com/ffxi/Lethargy_Earring)
      - [ ] [Lethargy Earring +1](https://www.bg-wiki.com/ffxi/Lethargy_Earring_%2B1)
      - [ ] [Lethargy Earring +2](https://www.bg-wiki.com/ffxi/Lethargy_Earring_%2B2)
