### ISSUE TITLE
THF JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4395]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [THF](https://www.bg-wiki.com/ffxi/Thief)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Rogue's Attire Set](https://www.bg-wiki.com/ffxi/Rogue%27s_Attire_Set)
      - [ ] [Rogue's Armlets](https://www.bg-wiki.com/ffxi/Rogue%27s_Armlets)
      - [ ] [Rogue's Bonnet](https://www.bg-wiki.com/ffxi/Rogue%27s_Bonnet)
      - [ ] [Rogue's Culottes](https://www.bg-wiki.com/ffxi/Rogue%27s_Culottes)
      - [ ] [Rogue's Vest](https://www.bg-wiki.com/ffxi/Rogue%27s_Vest)
      - [ ] [Rogue's Poulaines](https://www.bg-wiki.com/ffxi/Rogue%27s_Poulaines)
    - [ ] [Rogue's Attire Set +1](https://www.bg-wiki.com/ffxi/Rogue%27s_Attire_Set_%2B1)
      - [ ] [Rogue's Armlets +1](https://www.bg-wiki.com/ffxi/Rogue%27s_Armlets_%2B1)
      - [ ] [Rogue's Bonnet +1](https://www.bg-wiki.com/ffxi/Rogue%27s_Bonnet_%2B1)
      - [ ] [Rogue's Culottes +1](https://www.bg-wiki.com/ffxi/Rogue%27s_Culottes_%2B1)
      - [ ] [Rogue's Vest +1](https://www.bg-wiki.com/ffxi/Rogue%27s_Vest_%2B1)
      - [ ] [Rogue's Poulaines +1](https://www.bg-wiki.com/ffxi/Rogue%27s_Poulaines_%2B1)
    - [ ] [Pillager's Attire Set](https://www.bg-wiki.com/ffxi/Pillager%27s_Attire_Set)
      - [ ] [Pillager's Bonnet](https://www.bg-wiki.com/ffxi/Pillager%27s_Bonnet)
      - [ ] [Pillager's Vest](https://www.bg-wiki.com/ffxi/Pillager%27s_Vest)
      - [ ] [Pillager's Armlets](https://www.bg-wiki.com/ffxi/Pillager%27s_Armlets)
      - [ ] [Pillager's Culottes](https://www.bg-wiki.com/ffxi/Pillager%27s_Culottes)
      - [ ] [Pillager's Poulaines](https://www.bg-wiki.com/ffxi/Pillager%27s_Poulaines)
    - [ ] [Pillager's Attire Set +1](https://www.bg-wiki.com/ffxi/Pillager%27s_Attire_Set_%2B1)
      - [ ] [Pillager's Bonnet +1](https://www.bg-wiki.com/ffxi/Pillager%27s_Bonnet_%2B1)
      - [ ] [Pillager's Vest +1](https://www.bg-wiki.com/ffxi/Pillager%27s_Vest_%2B1)
      - [ ] [Pillager's Armlets +1](https://www.bg-wiki.com/ffxi/Pillager%27s_Armlets_%2B1)
      - [ ] [Pillager's Culottes +1](https://www.bg-wiki.com/ffxi/Pillager%27s_Culottes_%2B1)
      - [ ] [Pillager's Poulaines +1](https://www.bg-wiki.com/ffxi/Pillager%27s_Poulaines_%2B1)
    - [ ] [Pillager's Attire Set +2](https://www.bg-wiki.com/ffxi/Pillager%27s_Attire_Set_%2B2)
      - [ ] [Pillager's Bonnet +2](https://www.bg-wiki.com/ffxi/Pillager%27s_Bonnet_%2B2)
      - [ ] [Pillager's Vest +2](https://www.bg-wiki.com/ffxi/Pillager%27s_Vest_%2B2)
      - [ ] [Pillager's Armlets +2](https://www.bg-wiki.com/ffxi/Pillager%27s_Armlets_%2B2)
      - [ ] [Pillager's Culottes +2](https://www.bg-wiki.com/ffxi/Pillager%27s_Culottes_%2B2)
      - [ ] [Pillager's Poulaines +2](https://www.bg-wiki.com/ffxi/Pillager%27s_Poulaines_%2B2)
    - [ ] [Pillager's Attire Set +3](https://www.bg-wiki.com/ffxi/Pillager%27s_Attire_Set_%2B3)
      - [ ] [Pillager's Bonnet +3](https://www.bg-wiki.com/ffxi/Pillager%27s_Bonnet_%2B3)
      - [ ] [Pillager's Vest +3](https://www.bg-wiki.com/ffxi/Pillager%27s_Vest_%2B3)
      - [ ] [Pillager's Armlets +3](https://www.bg-wiki.com/ffxi/Pillager%27s_Armlets_%2B3)
      - [ ] [Pillager's Culottes +3](https://www.bg-wiki.com/ffxi/Pillager%27s_Culottes_%2B3)
      - [ ] [Pillager's Poulaines +3](https://www.bg-wiki.com/ffxi/Pillager%27s_Poulaines_%2B3)
    - [ ] [Marauder's Knife](https://www.bg-wiki.com/ffxi/Marauder%27s_Knife)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Assassin's Attire Set](https://www.bg-wiki.com/ffxi/Assassin%27s_Attire_Set)
      - [ ] [Assassin's Bonnet](https://www.bg-wiki.com/ffxi/Assassin%27s_Bonnet)
      - [ ] [Assassin's Vest](https://www.bg-wiki.com/ffxi/Assassin%27s_Vest)
      - [ ] [Assassin's Poulaines](https://www.bg-wiki.com/ffxi/Assassin%27s_Poulaines)
      - [ ] [Assassin's Culottes](https://www.bg-wiki.com/ffxi/Assassin%27s_Culottes)
      - [ ] [Assassin's Armlets](https://www.bg-wiki.com/ffxi/Assassin%27s_Armlets)
    - [ ] [Assassin's Attire Set +1](https://www.bg-wiki.com/ffxi/Assassin%27s_Attire_Set_%2B1)
      - [ ] [Assassin's Bonnet +1](https://www.bg-wiki.com/ffxi/Assassin%27s_Bonnet_%2B1)
      - [ ] [Assassin's Vest +1](https://www.bg-wiki.com/ffxi/Assassin%27s_Vest_%2B1)
      - [ ] [Assassin's Poulaines +1](https://www.bg-wiki.com/ffxi/Assassin%27s_Poulaines_%2B1)
      - [ ] [Assassin's Culottes +1](https://www.bg-wiki.com/ffxi/Assassin%27s_Culottes_%2B1)
      - [ ] [Assassin's Armlets +1](https://www.bg-wiki.com/ffxi/Assassin%27s_Armlets_%2B1)
    - [ ] [Assassin's Attire Set +2](https://www.bg-wiki.com/ffxi/Assassin%27s_Attire_Set_%2B2)
      - [ ] [Assassin's Bonnet +2](https://www.bg-wiki.com/ffxi/Assassin%27s_Bonnet_%2B2)
      - [ ] [Assassin's Vest +2](https://www.bg-wiki.com/ffxi/Assassin%27s_Vest_%2B2)
      - [ ] [Assassin's Poulaines +2](https://www.bg-wiki.com/ffxi/Assassin%27s_Poulaines_%2B2)
      - [ ] [Assassin's Culottes +2](https://www.bg-wiki.com/ffxi/Assassin%27s_Culottes_%2B2)
      - [ ] [Assassin's Armlets +2](https://www.bg-wiki.com/ffxi/Assassin%27s_Armlets_%2B2)
    - [ ] [Plunderer's Attire Set](https://www.bg-wiki.com/ffxi/Plunderer%27s_Attire_Set)
      - [ ] [Plunderer's Bonnet](https://www.bg-wiki.com/ffxi/Plunderer%27s_Bonnet)
      - [ ] [Plunderer's Vest](https://www.bg-wiki.com/ffxi/Plunderer%27s_Vest)
      - [ ] [Plunderer's Armlets](https://www.bg-wiki.com/ffxi/Plunderer%27s_Armlets)
      - [ ] [Plunderer's Culottes](https://www.bg-wiki.com/ffxi/Plunderer%27s_Culottes)
      - [ ] [Plunderer's Poulaines](https://www.bg-wiki.com/ffxi/Plunderer%27s_Poulaines)
    - [ ] [Plunderer's Attire Set +1](https://www.bg-wiki.com/ffxi/Plunderer%27s_Attire_Set_%2B1)
      - [ ] [Plunderer's Bonnet +1](https://www.bg-wiki.com/ffxi/Plunderer%27s_Bonnet_%2B1)
      - [ ] [Plunderer's Vest +1](https://www.bg-wiki.com/ffxi/Plunderer%27s_Vest_%2B1)
      - [ ] [Plunderer's Armlets +1](https://www.bg-wiki.com/ffxi/Plunderer%27s_Armlets_%2B1)
      - [ ] [Plunderer's Culottes +1](https://www.bg-wiki.com/ffxi/Plunderer%27s_Culottes_%2B1)
      - [ ] [Plunderer's Poulaines +1](https://www.bg-wiki.com/ffxi/Plunderer%27s_Poulaines_%2B1)
    - [ ] [Plunderer's Attire Set +2](https://www.bg-wiki.com/ffxi/Plunderer%27s_Attire_Set_%2B2)
      - [ ] [Plunderer's Bonnet +2](https://www.bg-wiki.com/ffxi/Plunderer%27s_Bonnet_%2B2)
      - [ ] [Plunderer's Vest +2](https://www.bg-wiki.com/ffxi/Plunderer%27s_Vest_%2B2)
      - [ ] [Plunderer's Armlets +2](https://www.bg-wiki.com/ffxi/Plunderer%27s_Armlets_%2B2)
      - [ ] [Plunderer's Culottes +2](https://www.bg-wiki.com/ffxi/Plunderer%27s_Culottes_%2B2)
      - [ ] [Plunderer's Poulaines +2](https://www.bg-wiki.com/ffxi/Plunderer%27s_Poulaines_%2B2)
    - [ ] [Plunderer's Attire Set +3](https://www.bg-wiki.com/ffxi/Plunderer%27s_Attire_Set_%2B3)
      - [ ] [Plunderer's Bonnet +3](https://www.bg-wiki.com/ffxi/Plunderer%27s_Bonnet_%2B3)
      - [ ] [Plunderer's Vest +3](https://www.bg-wiki.com/ffxi/Plunderer%27s_Vest_%2B3)
      - [ ] [Plunderer's Armlets +3](https://www.bg-wiki.com/ffxi/Plunderer%27s_Armlets_%2B3)
      - [ ] [Plunderer's Culottes +3](https://www.bg-wiki.com/ffxi/Plunderer%27s_Culottes_%2B3)
      - [ ] [Plunderer's Poulaines +3](https://www.bg-wiki.com/ffxi/Plunderer%27s_Poulaines_%2B3)
    - [ ] [Assassin's Cape](https://www.bg-wiki.com/ffxi/Assassin%27s_Cape)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Assassin's Gorget](https://www.bg-wiki.com/ffxi/Assassin%27s_Gorget)
      - [ ] [Assassin's Gorget +1](https://www.bg-wiki.com/ffxi/Assassin%27s_Gorget_%2B1)
      - [ ] [Assassin's Gorget +2](https://www.bg-wiki.com/ffxi/Assassin%27s_Gorget_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Assassin's Knife](https://www.bg-wiki.com/ffxi/Assassin%27s_Knife)
      - [ ] [Plunderer's Knife](https://www.bg-wiki.com/ffxi/Plunderer%27s_Knife)
      - [ ] [Gandring](https://www.bg-wiki.com/ffxi/Gandring)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Raider's Attire Set](https://www.bg-wiki.com/ffxi/Raider%27s_Attire_Set)
      - [ ] [Raider's Poulaines](https://www.bg-wiki.com/ffxi/Raider%27s_Poulaines)
      - [ ] [Raider's Culottes](https://www.bg-wiki.com/ffxi/Raider%27s_Culottes)
      - [ ] [Raider's Bonnet](https://www.bg-wiki.com/ffxi/Raider%27s_Bonnet)
      - [ ] [Raider's Armlets](https://www.bg-wiki.com/ffxi/Raider%27s_Armlets)
      - [ ] [Raider's Vest](https://www.bg-wiki.com/ffxi/Raider%27s_Vest)
    - [ ] [Raider's Attire Set +1](https://www.bg-wiki.com/ffxi/Raider%27s_Attire_Set_%2B1)
      - [ ] [Raider's Poulaines +1](https://www.bg-wiki.com/ffxi/Raider%27s_Poulaines_%2B1)
      - [ ] [Raider's Culottes +1](https://www.bg-wiki.com/ffxi/Raider%27s_Culottes_%2B1)
      - [ ] [Raider's Bonnet +1](https://www.bg-wiki.com/ffxi/Raider%27s_Bonnet_%2B1)
      - [ ] [Raider's Armlets +1](https://www.bg-wiki.com/ffxi/Raider%27s_Armlets_%2B1)
      - [ ] [Raider's Vest +1](https://www.bg-wiki.com/ffxi/Raider%27s_Vest_%2B1)
    - [ ] [Raider's Attire Set +2](https://www.bg-wiki.com/ffxi/Raider%27s_Attire_Set_%2B2)
      - [ ] [Raider's Poulaines +2](https://www.bg-wiki.com/ffxi/Raider%27s_Poulaines_%2B2)
      - [ ] [Raider's Culottes +2](https://www.bg-wiki.com/ffxi/Raider%27s_Culottes_%2B2)
      - [ ] [Raider's Bonnet +2](https://www.bg-wiki.com/ffxi/Raider%27s_Bonnet_%2B2)
      - [ ] [Raider's Armlets +2](https://www.bg-wiki.com/ffxi/Raider%27s_Armlets_%2B2)
      - [ ] [Raider's Vest +2](https://www.bg-wiki.com/ffxi/Raider%27s_Vest_%2B2)
    - [ ] [Skulker's Attire Set](https://www.bg-wiki.com/ffxi/Skulker%27s_Attire_Set)
      - [ ] [Skulker's Bonnet](https://www.bg-wiki.com/ffxi/Skulker%27s_Bonnet)
      - [ ] [Skulker's Vest](https://www.bg-wiki.com/ffxi/Skulker%27s_Vest)
      - [ ] [Skulker's Armlets](https://www.bg-wiki.com/ffxi/Skulker%27s_Armlets)
      - [ ] [Skulker's Culottes](https://www.bg-wiki.com/ffxi/Skulker%27s_Culottes)
      - [ ] [Skulker's Poulaines](https://www.bg-wiki.com/ffxi/Skulker%27s_Poulaines)
    - [ ] [Skulker's Attire Set +1](https://www.bg-wiki.com/ffxi/Skulker%27s_Attire_Set_%2B1)
      - [ ] [Skulker's Bonnet +1](https://www.bg-wiki.com/ffxi/Skulker%27s_Bonnet_%2B1)
      - [ ] [Skulker's Vest +1](https://www.bg-wiki.com/ffxi/Skulker%27s_Vest_%2B1)
      - [ ] [Skulker's Armlets +1](https://www.bg-wiki.com/ffxi/Skulker%27s_Armlets_%2B1)
      - [ ] [Skulker's Culottes +1](https://www.bg-wiki.com/ffxi/Skulker%27s_Culottes_%2B1)
      - [ ] [Skulker's Poulaines +1](https://www.bg-wiki.com/ffxi/Skulker%27s_Poulaines_%2B1)
    - [ ] [Skulker's Attire Set +2](https://www.bg-wiki.com/ffxi/Skulker%27s_Attire_Set_%2B2)
      - [ ] [Skulker's Bonnet +2](https://www.bg-wiki.com/ffxi/Skulker%27s_Bonnet_%2B2)
      - [ ] [Skulker's Vest +2](https://www.bg-wiki.com/ffxi/Skulker%27s_Vest_%2B2)
      - [ ] [Skulker's Armlets +2](https://www.bg-wiki.com/ffxi/Skulker%27s_Armlets_%2B2)
      - [ ] [Skulker's Culottes +2](https://www.bg-wiki.com/ffxi/Skulker%27s_Culottes_%2B2)
      - [ ] [Skulker's Poulaines +2](https://www.bg-wiki.com/ffxi/Skulker%27s_Poulaines_%2B2)
    - [ ] [Skulker's Attire Set +3](https://www.bg-wiki.com/ffxi/Skulker%27s_Attire_Set_%2B3)
      - [ ] [Skulker's Bonnet +3](https://www.bg-wiki.com/ffxi/Skulker%27s_Bonnet_%2B3)
      - [ ] [Skulker's Vest +3](https://www.bg-wiki.com/ffxi/Skulker%27s_Vest_%2B3)
      - [ ] [Skulker's Armlets +3](https://www.bg-wiki.com/ffxi/Skulker%27s_Armlets_%2B3)
      - [ ] [Skulker's Culottes +3](https://www.bg-wiki.com/ffxi/Skulker%27s_Culottes_%2B3)
      - [ ] [Skulker's Poulaines +3](https://www.bg-wiki.com/ffxi/Skulker%27s_Poulaines_%2B3)
    - [ ] Accessories
      - [ ] [Raider's Belt](https://www.bg-wiki.com/ffxi/Raider%27s_Belt)
      - [ ] [Raider's Boomerang](https://www.bg-wiki.com/ffxi/Raider%27s_Boomerang)
      - [ ] [Raider's Earring](https://www.bg-wiki.com/ffxi/Raider%27s_Earring)
      - [ ] [Skulker's Earring](https://www.bg-wiki.com/ffxi/Skulker%27s_Earring)
      - [ ] [Skulker's Earring +1](https://www.bg-wiki.com/ffxi/Skulker%27s_Earring_%2B1)
      - [ ] [Skulker's Earring +2](https://www.bg-wiki.com/ffxi/Skulker%27s_Earring_%2B2)
