### ISSUE TITLE
PLD JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4396]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [PLD](https://www.bg-wiki.com/ffxi/Paladin)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Gallant Armor Set](https://www.bg-wiki.com/ffxi/Gallant_Armor_Set)
      - [ ] [Gallant Leggings](https://www.bg-wiki.com/ffxi/Gallant_Leggings)
      - [ ] [Gallant Gauntlets](https://www.bg-wiki.com/ffxi/Gallant_Gauntlets)
      - [ ] [][Gallant Coronet](https://www.bg-wiki.com/ffxi/Gallant_Coronet)
      - [ ] [Gallant Breeches](https://www.bg-wiki.com/ffxi/Gallant_Breeches)
      - [ ] [Gallant Surcoat](https://www.bg-wiki.com/ffxi/Gallant_Surcoat)
    - [ ] [Gallant Armor Set +1](https://www.bg-wiki.com/ffxi/Gallant_Armor_Set_%2B1)
      - [ ] [Gallant Leggings +1](https://www.bg-wiki.com/ffxi/Gallant_Leggings_%2B1)
      - [ ] [Gallant Gauntlets +1](https://www.bg-wiki.com/ffxi/Gallant_Gauntlets_%2B1)
      - [ ] [Gallant Coronet +1](https://www.bg-wiki.com/ffxi/Gallant_Coronet_%2B1)
      - [ ] [Gallant Breeches +1](https://www.bg-wiki.com/ffxi/Gallant_Breeches_%2B1)
      - [ ] [Gallant Surcoat +1](https://www.bg-wiki.com/ffxi/Gallant_Surcoat_%2B1)
    - [ ] [Reverence Armor Set](https://www.bg-wiki.com/ffxi/Reverence_Armor_Set)
      - [ ] [Reverence Coronet](https://www.bg-wiki.com/ffxi/Reverence_Coronet)
      - [ ] [Reverence Surcoat](https://www.bg-wiki.com/ffxi/Reverence_Surcoat)
      - [ ] [Reverence Gauntlets](https://www.bg-wiki.com/ffxi/Reverence_Gauntlets)
      - [ ] [Reverence Breeches](https://www.bg-wiki.com/ffxi/Reverence_Breeches)
      - [ ] [Reverence Leggings](https://www.bg-wiki.com/ffxi/Reverence_Leggings)
    - [ ] [Reverence Armor Set +1](https://www.bg-wiki.com/ffxi/Reverence_Armor_Set_%2B1)
      - [ ] [Reverence Coronet +1](https://www.bg-wiki.com/ffxi/Reverence_Coronet_%2B1)
      - [ ] [Reverence Surcoat +1](https://www.bg-wiki.com/ffxi/Reverence_Surcoat_%2B1)
      - [ ] [Reverence Gauntlets +1](https://www.bg-wiki.com/ffxi/Reverence_Gauntlets_%2B1)
      - [ ] [Reverence Breeches +1](https://www.bg-wiki.com/ffxi/Reverence_Breeches_%2B1)
      - [ ] [Reverence Leggings +1](https://www.bg-wiki.com/ffxi/Reverence_Leggings_%2B1)
    - [ ] [Reverence Armor Set +2](https://www.bg-wiki.com/ffxi/Reverence_Armor_Set_%2B2)
      - [ ] [Reverence Coronet +2](https://www.bg-wiki.com/ffxi/Reverence_Coronet_%2B2)
      - [ ] [Reverence Surcoat +2](https://www.bg-wiki.com/ffxi/Reverence_Surcoat_%2B2)
      - [ ] [Reverence Gauntlets +2](https://www.bg-wiki.com/ffxi/Reverence_Gauntlets_%2B2)
      - [ ] [Reverence Breeches +2](https://www.bg-wiki.com/ffxi/Reverence_Breeches_%2B2)
      - [ ] [Reverence Leggings +2](https://www.bg-wiki.com/ffxi/Reverence_Leggings_%2B2)
    - [ ] [Reverence Armor Set +3](https://www.bg-wiki.com/ffxi/Reverence_Armor_Set_%2B3)
      - [ ] [Reverence Coronet +3](https://www.bg-wiki.com/ffxi/Reverence_Coronet_%2B3)
      - [ ] [Reverence Surcoat +3](https://www.bg-wiki.com/ffxi/Reverence_Surcoat_%2B3)
      - [ ] [Reverence Gauntlets +3](https://www.bg-wiki.com/ffxi/Reverence_Gauntlets_%2B3)
      - [ ] [Reverence Breeches +3](https://www.bg-wiki.com/ffxi/Reverence_Breeches_%2B3)
      - [ ] [Reverence Leggings +3](https://www.bg-wiki.com/ffxi/Reverence_Leggings_%2B3)
    - [ ] [Honor Sword](https://www.bg-wiki.com/ffxi/Honor_Sword)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Valor Armor Set](https://www.bg-wiki.com/ffxi/Valor_Armor_Set)
      - [ ] [Valor Leggings](https://www.bg-wiki.com/ffxi/Valor_Leggings)
      - [ ] [Valor Gauntlets](https://www.bg-wiki.com/ffxi/Valor_Gauntlets)
      - [ ] [Valor Coronet](https://www.bg-wiki.com/ffxi/Valor_Coronet)
      - [ ] [Valor Breeches](https://www.bg-wiki.com/ffxi/Valor_Breeches)
      - [ ] [Valor Surcoat](https://www.bg-wiki.com/ffxi/Valor_Surcoat)
    - [ ] [Valor Armor Set +1](https://www.bg-wiki.com/ffxi/Valor_Armor_Set_%2B1)
      - [ ] [Valor Leggings +1](https://www.bg-wiki.com/ffxi/Valor_Leggings_%2B1)
      - [ ] [Valor Gauntlets +1](https://www.bg-wiki.com/ffxi/Valor_Gauntlets_%2B1)
      - [ ] [Valor Coronet +1](https://www.bg-wiki.com/ffxi/Valor_Coronet)_%2B1)
      - [ ] [Valor Breeches +1](https://www.bg-wiki.com/ffxi/Valor_Breeches_%2B1)
      - [ ] [Valor Surcoat +1](https://www.bg-wiki.com/ffxi/Valor_Surcoat_%2B1)
    - [ ] [Valor Armor Set +2](https://www.bg-wiki.com/ffxi/Valor_Armor_Set_%2B2)
      - [ ] [Valor Leggings +2](https://www.bg-wiki.com/ffxi/Valor_Leggings_%2B2)
      - [ ] [Valor Gauntlets +2](https://www.bg-wiki.com/ffxi/Valor_Gauntlets_%2B2)
      - [ ] [Valor Coronet +2](https://www.bg-wiki.com/ffxi/Valor_Coronet_%2B2)
      - [ ] [Valor Breeches +2](https://www.bg-wiki.com/ffxi/Valor_Breeches_%2B2)
      - [ ] [Valor Surcoat +2](https://www.bg-wiki.com/ffxi/Valor_Surcoat_%2B2)
    - [ ] [Caballarius Armor Set](https://www.bg-wiki.com/ffxi/Caballarius_Armor_Set)
      - [ ] [Caballarius Coronet](https://www.bg-wiki.com/ffxi/Caballarius_Coronet)
      - [ ] [Caballarius Surcoat](https://www.bg-wiki.com/ffxi/Caballarius_Surcoat)
      - [ ] [Caballarius Gauntlets](https://www.bg-wiki.com/ffxi/Caballarius_Gauntlets)
      - [ ] [Caballarius Breeches](https://www.bg-wiki.com/ffxi/Caballarius_Breeches)
      - [ ] [Caballarius Leggings](https://www.bg-wiki.com/ffxi/Caballarius_Leggings)
    - [ ] [Caballarius Armor Set +1](https://www.bg-wiki.com/ffxi/Caballarius_Armor_Set_%2B1)
      - [ ] [Caballarius Coronet +1](https://www.bg-wiki.com/ffxi/Caballarius_Coronet_%2B1)
      - [ ] [Caballarius Surcoat +1](https://www.bg-wiki.com/ffxi/Caballarius_Surcoat_%2B1)
      - [ ] [Caballarius Gauntlets +1](https://www.bg-wiki.com/ffxi/Caballarius_Gauntlets_%2B1)
      - [ ] [Caballarius Breeches +1](https://www.bg-wiki.com/ffxi/Caballarius_Breeches_%2B1)
      - [ ] [Caballarius Leggings +1](https://www.bg-wiki.com/ffxi/Caballarius_Leggings_%2B1)
    - [ ] [Caballarius Armor Set +2](https://www.bg-wiki.com/ffxi/Caballarius_Armor_Set_%2B2)
      - [ ] [Caballarius Coronet +2](https://www.bg-wiki.com/ffxi/Caballarius_Coronet_%2B2)
      - [ ] [Caballarius Surcoat +2](https://www.bg-wiki.com/ffxi/Caballarius_Surcoat_%2B2)
      - [ ] [Caballarius Gauntlets +2](https://www.bg-wiki.com/ffxi/Caballarius_Gauntlets_%2B2)
      - [ ] [Caballarius Breeches +2](https://www.bg-wiki.com/ffxi/Caballarius_Breeches_%2B2)
      - [ ] [Caballarius Leggings +2](https://www.bg-wiki.com/ffxi/Caballarius_Leggings_%2B2)
    - [ ] [Caballarius Armor Set +3](https://www.bg-wiki.com/ffxi/Caballarius_Armor_Set_%2B3)
      - [ ] [Caballarius Coronet +3](https://www.bg-wiki.com/ffxi/Caballarius_Coronet_%2B3)
      - [ ] [Caballarius Surcoat +3](https://www.bg-wiki.com/ffxi/Caballarius_Surcoat_%2B3)
      - [ ] [Caballarius Gauntlets +3](https://www.bg-wiki.com/ffxi/Caballarius_Gauntlets_%2B3)
      - [ ] [Caballarius Breeches +3](https://www.bg-wiki.com/ffxi/Caballarius_Breeches_%2B3)
      - [ ] [Caballarius Leggings +3](https://www.bg-wiki.com/ffxi/Caballarius_Leggings_%2B3)
    - [ ] [Valor Cape](https://www.bg-wiki.com/ffxi/Valor_Cape)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Knight's Beads](https://www.bg-wiki.com/ffxi/Knight%27s_Beads)
      - [ ] [Knight's Beads +1](https://www.bg-wiki.com/ffxi/Knight%27s_Beads_%2B1)
      - [ ] [Knight's Beads +2](https://www.bg-wiki.com/ffxi/Knight%27s_Beads_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Valor Sword](https://www.bg-wiki.com/ffxi/Valor_Sword)
      - [ ] [Caballarius Sword](https://www.bg-wiki.com/ffxi/Caballarius_Sword)
      - [ ] [Moralltach](https://www.bg-wiki.com/ffxi/Moralltach)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Creed Armor Set](https://www.bg-wiki.com/ffxi/Creed_Armor_Set)
      - [ ] [Creed Sabatons](https://www.bg-wiki.com/ffxi/Creed_Sabatons)
      - [ ] [Creed Cuisses](https://www.bg-wiki.com/ffxi/Creed_Cuisses)
      - [ ] [Creed Armet](https://www.bg-wiki.com/ffxi/Creed_Armet)
      - [ ] [Creed Gauntlets](https://www.bg-wiki.com/ffxi/Creed_Gauntlets)
      - [ ] [Creed Cuirass](https://www.bg-wiki.com/ffxi/Creed_Cuirass)
    - [ ] [Creed Armor Set +1](https://www.bg-wiki.com/ffxi/Creed_Armor_Set_%2B1)
      - [ ] [Creed Sabatons +1](https://www.bg-wiki.com/ffxi/Creed_Sabatons_%2B1)
      - [ ] [Creed Cuisses +1](https://www.bg-wiki.com/ffxi/Creed_Cuisses_%2B1)
      - [ ] [Creed Armet +1](https://www.bg-wiki.com/ffxi/Creed_Armet_%2B1)
      - [ ] [Creed Gauntlets +1](https://www.bg-wiki.com/ffxi/Creed_Gauntlets_%2B1)
      - [ ] [Creed Cuirass +1](https://www.bg-wiki.com/ffxi/Creed_Cuirass_%2B1)
    - [ ] [Creed Armor Set +2](https://www.bg-wiki.com/ffxi/Creed_Armor_Set_%2B2)
      - [ ] [Creed Sabatons +2](https://www.bg-wiki.com/ffxi/Creed_Sabatons_%2B2)
      - [ ] [Creed Cuisses +2](https://www.bg-wiki.com/ffxi/Creed_Cuisses_%2B2)
      - [ ] [Creed Armet +2](https://www.bg-wiki.com/ffxi/Creed_Armet_%2B2)
      - [ ] [Creed Gauntlets +2](https://www.bg-wiki.com/ffxi/Creed_Gauntlets_%2B2)
      - [ ] [Creed Cuirass +2](https://www.bg-wiki.com/ffxi/Creed_Cuirass_%2B2)
    - [ ] [Chevalier's Armor Set](https://www.bg-wiki.com/ffxi/Chevalier%27s_Armor_Set)
      - [ ] [Chevalier's Armet](https://www.bg-wiki.com/ffxi/Chevalier%27s_Armet)
      - [ ] [Chevalier's Cuirass](https://www.bg-wiki.com/ffxi/Chevalier%27s_Cuirass)
      - [ ] [Chevalier's Gauntlets](https://www.bg-wiki.com/ffxi/Chevalier%27s_Gauntlets)
      - [ ] [Chevalier's Cuisses](https://www.bg-wiki.com/ffxi/Chevalier%27s_Cuisses)
      - [ ] [Chevalier's Sabatons](https://www.bg-wiki.com/ffxi/Chevalier%27s_Sabatons)
    - [ ] [Chevalier's Armor Set +1](https://www.bg-wiki.com/ffxi/Chevalier%27s_Armor_Set_%2B1)
      - [ ] [Chevalier's Armet +1](https://www.bg-wiki.com/ffxi/Chevalier%27s_Armet_%2B1)
      - [ ] [Chevalier's Cuirass +1](https://www.bg-wiki.com/ffxi/Chevalier%27s_Cuirass_%2B1)
      - [ ] [Chevalier's Gauntlets +1](https://www.bg-wiki.com/ffxi/Chevalier%27s_Gauntlets_%2B1)
      - [ ] [Chevalier's Cuisses +1](https://www.bg-wiki.com/ffxi/Chevalier%27s_Cuisses_%2B1)
      - [ ] [Chevalier's Sabatons +1](https://www.bg-wiki.com/ffxi/Chevalier%27s_Sabatons_%2B1)
    - [ ] [Chevalier's Armor Set +2](https://www.bg-wiki.com/ffxi/Chevalier%27s_Armor_Set_%2B2)
      - [ ] [Chevalier's Armet +2](https://www.bg-wiki.com/ffxi/Chevalier%27s_Armet_%2B2)
      - [ ] [Chevalier's Cuirass +2](https://www.bg-wiki.com/ffxi/Chevalier%27s_Cuirass_%2B2)
      - [ ] [Chevalier's Gauntlets +2](https://www.bg-wiki.com/ffxi/Chevalier%27s_Gauntlets_%2B2)
      - [ ] [Chevalier's Cuisses +2](https://www.bg-wiki.com/ffxi/Chevalier%27s_Cuisses_%2B2)
      - [ ] [Chevalier's Sabatons +2](https://www.bg-wiki.com/ffxi/Chevalier%27s_Sabatons_%2B2)
    - [ ] [Chevalier's Armor Set +3](https://www.bg-wiki.com/ffxi/Chevalier%27s_Armor_Set_%2B3)
      - [ ] [Chevalier's Armet +3](https://www.bg-wiki.com/ffxi/Chevalier%27s_Armet_%2B3)
      - [ ] [Chevalier's Cuirass +3](https://www.bg-wiki.com/ffxi/Chevalier%27s_Cuirass_%2B3)
      - [ ] [Chevalier's Gauntlets +3](https://www.bg-wiki.com/ffxi/Chevalier%27s_Gauntlets_%2B3)
      - [ ] [Chevalier's Cuisses +3](https://www.bg-wiki.com/ffxi/Chevalier%27s_Cuisses_%2B3)
      - [ ] [Chevalier's Sabatons +3](https://www.bg-wiki.com/ffxi/Chevalier%27s_Sabatons_%2B3)
    - [ ] Accessories
      - [ ] [Creed Collar](https://www.bg-wiki.com/ffxi/Creed_Collar)
      - [ ] [Creed Baudrier](https://www.bg-wiki.com/ffxi/Creed_Baudrier)
      - [ ] [Creed Earring](https://www.bg-wiki.com/ffxi/Creed_Earring)
      - [ ] [Chevalier's Earring](https://www.bg-wiki.com/ffxi/Chevalier%27s_Earring)
      - [ ] [Chevalier's Earring +1](https://www.bg-wiki.com/ffxi/Chevalier%27s_Earring_%2B1)
      - [ ] [Chevalier's Earring +2](https://www.bg-wiki.com/ffxi/Chevalier%27s_Earring_%2B2)
