### ISSUE TITLE
DRK JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4397]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [DRK](https://www.bg-wiki.com/ffxi/Dark_Knight)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Chaos Armor Set](https://www.bg-wiki.com/ffxi/Chaos_Armor_Set)
      - [ ] [Chaos Sollerets](https://www.bg-wiki.com/ffxi/Chaos_Sollerets)
      - [ ] [Chaos Gauntlets](https://www.bg-wiki.com/ffxi/Chaos_Gauntlets)
      - [ ] [Chaos Flanchard](https://www.bg-wiki.com/ffxi/Chaos_Flanchard)
      - [ ] [Chaos Cuirass](https://www.bg-wiki.com/ffxi/Chaos_Cuirass)
      - [ ] [Chaos Burgeonet](https://www.bg-wiki.com/ffxi/Chaos_Burgeonet)
    - [ ] [Chaos Armor Set +1](https://www.bg-wiki.com/ffxi/Chaos_Armor_Set_%2B1)
      - [ ] [Chaos Sollerets +1](https://www.bg-wiki.com/ffxi/Chaos_Sollerets_%2B1)
      - [ ] [Chaos Gauntlets +1](https://www.bg-wiki.com/ffxi/Chaos_Gauntlets_%2B1)
      - [ ] [Chaos Flanchard +1](https://www.bg-wiki.com/ffxi/Chaos_Flanchard_%2B1)
      - [ ] [Chaos Cuirass +1](https://www.bg-wiki.com/ffxi/Chaos_Cuirass_%2B1)
      - [ ] [Chaos Burgeonet +1](https://www.bg-wiki.com/ffxi/Chaos_Burgeonet_%2B1)
    - [ ] [Ignominy Armor Set](https://www.bg-wiki.com/ffxi/Ignominy_Armor_Set)
      - [ ] [Ignominy Burgeonet](https://www.bg-wiki.com/ffxi/Ignominy_Burgeonet)
      - [ ] [Ignominy Cuirass](https://www.bg-wiki.com/ffxi/Ignominy_Cuirass)
      - [ ] [Ignominy Gauntlets](https://www.bg-wiki.com/ffxi/Ignominy_Gauntlets)
      - [ ] [Ignominy Flanchard](https://www.bg-wiki.com/ffxi/Ignominy_Flanchard)
      - [ ] [Ignominy Sollerets](https://www.bg-wiki.com/ffxi/Ignominy_Sollerets)
    - [ ] [Ignominy Armor Set +1](https://www.bg-wiki.com/ffxi/Ignominy_Armor_Set_%2B1)
      - [ ] [Ignominy Burgeonet +1](https://www.bg-wiki.com/ffxi/Ignominy_Burgeonet_%2B1)
      - [ ] [Ignominy Cuirass +1](https://www.bg-wiki.com/ffxi/Ignominy_Cuirass_%2B1)
      - [ ] [Ignominy Gauntlets +1](https://www.bg-wiki.com/ffxi/Ignominy_Gauntlets_%2B1)
      - [ ] [Ignominy Flanchard +1](https://www.bg-wiki.com/ffxi/Ignominy_Flanchard_%2B1)
      - [ ] [Ignominy Sollerets +1](https://www.bg-wiki.com/ffxi/Ignominy_Sollerets_%2B1)
    - [ ] [Ignominy Armor Set +2](https://www.bg-wiki.com/ffxi/Ignominy_Armor_Set_%2B2)
      - [ ] [Ignominy Burgeonet +2](https://www.bg-wiki.com/ffxi/Ignominy_Burgeonet_%2B2)
      - [ ] [Ignominy Cuirass +2](https://www.bg-wiki.com/ffxi/Ignominy_Cuirass_%2B2)
      - [ ] [Ignominy Gauntlets +2](https://www.bg-wiki.com/ffxi/Ignominy_Gauntlets_%2B2)
      - [ ] [Ignominy Flanchard +2](https://www.bg-wiki.com/ffxi/Ignominy_Flanchard_%2B2)
      - [ ] [Ignominy Sollerets +2](https://www.bg-wiki.com/ffxi/Ignominy_Sollerets_%2B2)
    - [ ] [Ignominy Armor Set +3](https://www.bg-wiki.com/ffxi/Ignominy_Armor_Set_%2B3)
      - [ ] [Ignominy Burgeonet +3](https://www.bg-wiki.com/ffxi/Ignominy_Burgeonet_%2B3)
      - [ ] [Ignominy Cuirass +3](https://www.bg-wiki.com/ffxi/Ignominy_Cuirass_%2B3)
      - [ ] [Ignominy Gauntlets +3](https://www.bg-wiki.com/ffxi/Ignominy_Gauntlets_%2B3)
      - [ ] [Ignominy Flanchard +3](https://www.bg-wiki.com/ffxi/Ignominy_Flanchard_%2B3)
      - [ ] [Ignominy Sollerets +3](https://www.bg-wiki.com/ffxi/Ignominy_Sollerets_%2B3)
    - [ ] [Raven Scythe](https://www.bg-wiki.com/ffxi/Raven_Scythe)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Abyss Armor Set](https://www.bg-wiki.com/ffxi/Abyss_Armor_Set)
      - [ ] [Abyss Sollerets](https://www.bg-wiki.com/ffxi/Abyss_Sollerets)
      - [ ] [Abyss Gauntlets](https://www.bg-wiki.com/ffxi/Abyss_Gauntlets)
      - [ ] [Abyss Flanchard](https://www.bg-wiki.com/ffxi/Abyss_Flanchard)
      - [ ] [Abyss Cuirass](https://www.bg-wiki.com/ffxi/Abyss_Cuirass)
      - [ ] [Abyss Burgeonet](https://www.bg-wiki.com/ffxi/Abyss_Burgeonet)
    - [ ] [Abyss Armor Set +1](https://www.bg-wiki.com/ffxi/Abyss_Armor_Set_%2B1)
      - [ ] [Abyss Sollerets +1](https://www.bg-wiki.com/ffxi/Abyss_Sollerets_%2B1)
      - [ ] [Abyss Gauntlets +1](https://www.bg-wiki.com/ffxi/Abyss_Gauntlets_%2B1)
      - [ ] [Abyss Flanchard +1](https://www.bg-wiki.com/ffxi/Abyss_Flanchard_%2B1)
      - [ ] [Abyss Cuirass +1](https://www.bg-wiki.com/ffxi/Abyss_Cuirass_%2B1)
      - [ ] [Abyss Burgeonet +1](https://www.bg-wiki.com/ffxi/Abyss_Burgeonet_%2B1)
    - [ ] [Abyss Armor Set +2](https://www.bg-wiki.com/ffxi/Abyss_Armor_Set_%2B2)
      - [ ] [Abyss Sollerets +2](https://www.bg-wiki.com/ffxi/Abyss_Sollerets_%2B2)
      - [ ] [Abyss Gauntlets +2](https://www.bg-wiki.com/ffxi/Abyss_Gauntlets_%2B2)
      - [ ] [Abyss Flanchard +2](https://www.bg-wiki.com/ffxi/Abyss_Flanchard_%2B2)
      - [ ] [Abyss Cuirass +2](https://www.bg-wiki.com/ffxi/Abyss_Cuirass_%2B2)
      - [ ] [Abyss Burgeonet +2](https://www.bg-wiki.com/ffxi/Abyss_Burgeonet_%2B2)
    - [ ] [Fallen's Armor Set](https://www.bg-wiki.com/ffxi/Fallen%27s_Armor_Set)
      - [ ] [Fallen's Burgeonet](https://www.bg-wiki.com/ffxi/Fallen%27s_Burgeonet)
      - [ ] [Fallen's Cuirass](https://www.bg-wiki.com/ffxi/Fallen%27s_Cuirass)
      - [ ] [Fallen's Finger Gauntlets](https://www.bg-wiki.com/ffxi/Fallen%27s_Finger_Gauntlets)
      - [ ] [Fallen's Flanchard](https://www.bg-wiki.com/ffxi/Fallen%27s_Flanchard)
      - [ ] [Fallen's Sollerets](https://www.bg-wiki.com/ffxi/Fallen%27s_Sollerets)
    - [ ] [Fallen's Armor Set +1](https://www.bg-wiki.com/ffxi/Fallen%27s_Armor_Set_%2B1)
      - [ ] [Fallen's Burgeonet +1](https://www.bg-wiki.com/ffxi/Fallen%27s_Burgeonet_%2B1)
      - [ ] [Fallen's Cuirass +1](https://www.bg-wiki.com/ffxi/Fallen%27s_Cuirass_%2B1)
      - [ ] [Fallen's Finger Gauntlets +1](https://www.bg-wiki.com/ffxi/Fallen%27s_Finger_Gauntlets_%2B1)
      - [ ] [Fallen's Flanchard +1](https://www.bg-wiki.com/ffxi/Fallen%27s_Flanchard_%2B1)
      - [ ] [Fallen's Sollerets +1](https://www.bg-wiki.com/ffxi/Fallen%27s_Sollerets_%2B1)
    - [ ] [Fallen's Armor Set +2](https://www.bg-wiki.com/ffxi/Fallen%27s_Armor_Set_%2B2)
      - [ ] [Fallen's Burgeonet +2](https://www.bg-wiki.com/ffxi/Fallen%27s_Burgeonet_%2B2)
      - [ ] [Fallen's Cuirass +2](https://www.bg-wiki.com/ffxi/Fallen%27s_Cuirass_%2B2)
      - [ ] [Fallen's Finger Gauntlets +2](https://www.bg-wiki.com/ffxi/Fallen%27s_Finger_Gauntlets_%2B2)
      - [ ] [Fallen's Flanchard +2](https://www.bg-wiki.com/ffxi/Fallen%27s_Flanchard_%2B2)
      - [ ] [Fallen's Sollerets +2](https://www.bg-wiki.com/ffxi/Fallen%27s_Sollerets_%2B2)
    - [ ] [Fallen's Armor Set +3](https://www.bg-wiki.com/ffxi/Fallen%27s_Armor_Set_%2B3)
      - [ ] [Fallen's Burgeonet +3](https://www.bg-wiki.com/ffxi/Fallen%27s_Burgeonet_%2B3)
      - [ ] [Fallen's Cuirass +3](https://www.bg-wiki.com/ffxi/Fallen%27s_Cuirass_%2B3)
      - [ ] [Fallen's Finger Gauntlets +3](https://www.bg-wiki.com/ffxi/Fallen%27s_Finger_Gauntlets_%2B3)
      - [ ] [Fallen's Flanchard +3](https://www.bg-wiki.com/ffxi/Fallen%27s_Flanchard_%2B3)
      - [ ] [Fallen's Sollerets +3](https://www.bg-wiki.com/ffxi/Fallen%27s_Sollerets_%2B3)
    - [ ] [Abyss Cape](https://www.bg-wiki.com/ffxi/Abyss_Cape)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Abyssal Beads](https://www.bg-wiki.com/ffxi/Abyssal_Beads)
      - [ ] [Abyssal Beads +1](https://www.bg-wiki.com/ffxi/Abyssal_Beads_%2B1)
      - [ ] [Abyssal Beads +2](https://www.bg-wiki.com/ffxi/Abyssal_Beads_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Abyss Scythe](https://www.bg-wiki.com/ffxi/Abyss_Scythe)
      - [ ] [Fallen's Scythe](https://www.bg-wiki.com/ffxi/Fallen%27s_Scythe)
      - [ ] [Father Time](https://www.bg-wiki.com/ffxi/Father_Time)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Bale Armor Set](https://www.bg-wiki.com/ffxi/Bale_Armor_Set)
      - [ ] [Bale Sollerets](https://www.bg-wiki.com/ffxi/Bale_Sollerets)
      - [ ] [Bale Flanchard](https://www.bg-wiki.com/ffxi/Bale_Flanchard)
      - [ ] [Bale Burgeonet](https://www.bg-wiki.com/ffxi/Bale_Burgeonet)
      - [ ] [Bale Gauntlets](https://www.bg-wiki.com/ffxi/Bale_Gauntlets)
      - [ ] [Bale Cuirass](https://www.bg-wiki.com/ffxi/Bale_Cuirass)
    - [ ] [Bale Armor Set +1](https://www.bg-wiki.com/ffxi/Bale_Armor_Set_%2B1)
      - [ ] [Bale Sollerets +1](https://www.bg-wiki.com/ffxi/Bale_Sollerets_%2B1)
      - [ ] [Bale Flanchard +1](https://www.bg-wiki.com/ffxi/Bale_Flanchard_%2B1)
      - [ ] [Bale Burgeonet +1](https://www.bg-wiki.com/ffxi/Bale_Burgeonet_%2B1)
      - [ ] [Bale Gauntlets +1](https://www.bg-wiki.com/ffxi/Bale_Gauntlets_%2B1)
      - [ ] [Bale Cuirass +1](https://www.bg-wiki.com/ffxi/Bale_Cuirass_%2B1)
    - [ ] [Bale Armor Set +2](https://www.bg-wiki.com/ffxi/Bale_Armor_Set_%2B2)
      - [ ] [Bale Sollerets +2](https://www.bg-wiki.com/ffxi/Bale_Sollerets_%2B2)
      - [ ] [Bale Flanchard +2](https://www.bg-wiki.com/ffxi/Bale_Flanchard_%2B2)
      - [ ] [Bale Burgeonet +2](https://www.bg-wiki.com/ffxi/Bale_Burgeonet_%2B2)
      - [ ] [Bale Gauntlets +2](https://www.bg-wiki.com/ffxi/Bale_Gauntlets_%2B2)
      - [ ] [Bale Cuirass +2](https://www.bg-wiki.com/ffxi/Bale_Cuirass_%2B2)
    - [ ] [Heathen's Armor Set](https://www.bg-wiki.com/ffxi/Heathen%27s_Armor_Set)
      - [ ] [Heathen's Burgeonet](https://www.bg-wiki.com/ffxi/Heathen%27s_Burgeonet)
      - [ ] [Heathen's Cuirass](https://www.bg-wiki.com/ffxi/Heathen%27s_Cuirass)
      - [ ] [Heathen's Gauntlets](https://www.bg-wiki.com/ffxi/Heathen%27s_Gauntlets)
      - [ ] [Heathen's Flanchard](https://www.bg-wiki.com/ffxi/Heathen%27s_Flanchard)
      - [ ] [Heathen's Sollerets](https://www.bg-wiki.com/ffxi/Heathen%27s_Sollerets)
    - [ ] [Heathen's Armor Set +1](https://www.bg-wiki.com/ffxi/Heathen%27s_Armor_Set_%2B1)
      - [ ] [Heathen's Burgeonet +1](https://www.bg-wiki.com/ffxi/Heathen%27s_Burgeonet_%2B1)
      - [ ] [Heathen's Cuirass +1](https://www.bg-wiki.com/ffxi/Heathen%27s_Cuirass_%2B1)
      - [ ] [Heathen's Gauntlets +1](https://www.bg-wiki.com/ffxi/Heathen%27s_Gauntlets_%2B1)
      - [ ] [Heathen's Flanchard +1](https://www.bg-wiki.com/ffxi/Heathen%27s_Flanchard_%2B1)
      - [ ] [Heathen's Sollerets +1](https://www.bg-wiki.com/ffxi/Heathen%27s_Sollerets_%2B1)
    - [ ] [Heathen's Armor Set +2](https://www.bg-wiki.com/ffxi/Heathen%27s_Armor_Set_%2B2)
      - [ ] [Heathen's Burgeonet +2](https://www.bg-wiki.com/ffxi/Heathen%27s_Burgeonet_%2B2)
      - [ ] [Heathen's Cuirass +2](https://www.bg-wiki.com/ffxi/Heathen%27s_Cuirass_%2B2)
      - [ ] [Heathen's Gauntlets +2](https://www.bg-wiki.com/ffxi/Heathen%27s_Gauntlets_%2B2)
      - [ ] [Heathen's Flanchard +2](https://www.bg-wiki.com/ffxi/Heathen%27s_Flanchard_%2B2)
      - [ ] [Heathen's Sollerets +2](https://www.bg-wiki.com/ffxi/Heathen%27s_Sollerets_%2B2)
    - [ ] [Heathen's Armor Set +3](https://www.bg-wiki.com/ffxi/Heathen%27s_Armor_Set_%2B3)
      - [ ] [Heathen's Burgeonet +3](https://www.bg-wiki.com/ffxi/Heathen%27s_Burgeonet_%2B3)
      - [ ] [Heathen's Cuirass +3](https://www.bg-wiki.com/ffxi/Heathen%27s_Cuirass_%2B3)
      - [ ] [Heathen's Gauntlets +3](https://www.bg-wiki.com/ffxi/Heathen%27s_Gauntlets_%2B3)
      - [ ] [Heathen's Flanchard +3](https://www.bg-wiki.com/ffxi/Heathen%27s_Flanchard_%2B3)
      - [ ] [Heathen's Sollerets +3](https://www.bg-wiki.com/ffxi/Heathen%27s_Sollerets_%2B3)
    - [ ] Accessories
      - [ ] [Bale Belt](https://www.bg-wiki.com/ffxi/Bale_Belt)
      - [ ] [Bale Choker](https://www.bg-wiki.com/ffxi/Bale_Choker)
      - [ ] [Bale Earring](https://www.bg-wiki.com/ffxi/Bale_Earring)
      - [ ] [Heathen's Earring](https://www.bg-wiki.com/ffxi/Heathen%27s_Earring)
      - [ ] [Heathen's Earring +1](https://www.bg-wiki.com/ffxi/Heathen%27s_Earring_%2B1)
      - [ ] [Heathen's Earring +2](https://www.bg-wiki.com/ffxi/Heathen%27s_Earring_%2B2)
