### ISSUE TITLE
BST JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4398]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [BST](https://www.bg-wiki.com/ffxi/Beastmaster)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Beast Armor Set](https://www.bg-wiki.com/ffxi/Beast_Armor_Set)
      - [ ] [Beast Gaiters](https://www.bg-wiki.com/ffxi/Beast_Gaiters)
      - [ ] [Beast Gloves](https://www.bg-wiki.com/ffxi/Beast_Gloves)
      - [ ] [Beast Helm](https://www.bg-wiki.com/ffxi/Beast_Helm)
      - [ ] [Beast Jackcoat](https://www.bg-wiki.com/ffxi/Beast_Jackcoat)
      - [ ] [Beast Trousers](https://www.bg-wiki.com/ffxi/Beast_Trousers)
    - [ ] [Beast Armor Set +1](https://www.bg-wiki.com/ffxi/Beast_Armor_Set_%2B1)
      - [ ] [Beast Gaiters +1](https://www.bg-wiki.com/ffxi/Beast_Gaiters_%2B1)
      - [ ] [Beast Gloves +1](https://www.bg-wiki.com/ffxi/Beast_Gloves_%2B1)
      - [ ] [Beast Helm +1](https://www.bg-wiki.com/ffxi/Beast_Helm_%2B1)
      - [ ] [Beast Jackcoat +1](https://www.bg-wiki.com/ffxi/Beast_Jackcoat_%2B1)
      - [ ] [Beast Trousers +1](https://www.bg-wiki.com/ffxi/Beast_Trousers_%2B1)
    - [ ] [Totemic Armor Set](https://www.bg-wiki.com/ffxi/Totemic_Armor_Set)
      - [ ] [Totemic Helm](https://www.bg-wiki.com/ffxi/Totemic_Helm)
      - [ ] [Totemic Jackcoat](https://www.bg-wiki.com/ffxi/Totemic_Jackcoat)
      - [ ] [Totemic Gloves](https://www.bg-wiki.com/ffxi/Totemic_Gloves)
      - [ ] [Totemic Trousers](https://www.bg-wiki.com/ffxi/Totemic_Trousers)
      - [ ] [Totemic Gaiters](https://www.bg-wiki.com/ffxi/Totemic_Gaiters)
    - [ ] [Totemic Armor Set +1](https://www.bg-wiki.com/ffxi/Totemic_Armor_Set_%2B1)
      - [ ] [Totemic Helm +1](https://www.bg-wiki.com/ffxi/Totemic_Helm_%2B1)
      - [ ] [Totemic Jackcoat +1](https://www.bg-wiki.com/ffxi/Totemic_Jackcoat_%2B1)
      - [ ] [Totemic Gloves +1](https://www.bg-wiki.com/ffxi/Totemic_Gloves_%2B1)
      - [ ] [Totemic Trousers +1](https://www.bg-wiki.com/ffxi/Totemic_Trousers_%2B1)
      - [ ] [Totemic Gaiters +1](https://www.bg-wiki.com/ffxi/Totemic_Gaiters_%2B1)
    - [ ] [Totemic Armor Set +2](https://www.bg-wiki.com/ffxi/Totemic_Armor_Set_%2B2)
      - [ ] [Totemic Helm +2](https://www.bg-wiki.com/ffxi/Totemic_Helm_%2B2)
      - [ ] [Totemic Jackcoat +2](https://www.bg-wiki.com/ffxi/Totemic_Jackcoat_%2B2)
      - [ ] [Totemic Gloves +2](https://www.bg-wiki.com/ffxi/Totemic_Gloves_%2B2)
      - [ ] [Totemic Trousers +2](https://www.bg-wiki.com/ffxi/Totemic_Trousers_%2B2)
      - [ ] [Totemic Gaiters +2](https://www.bg-wiki.com/ffxi/Totemic_Gaiters_%2B2)
    - [ ] [Totemic Armor Set +3](https://www.bg-wiki.com/ffxi/Totemic_Armor_Set_%2B3)
      - [ ] [Totemic Helm +3](https://www.bg-wiki.com/ffxi/Totemic_Helm_%2B3)
      - [ ] [Totemic Jackcoat +3](https://www.bg-wiki.com/ffxi/Totemic_Jackcoat_%2B3)
      - [ ] [Totemic Gloves +3](https://www.bg-wiki.com/ffxi/Totemic_Gloves_%2B3)
      - [ ] [Totemic Trousers +3](https://www.bg-wiki.com/ffxi/Totemic_Trousers_%2B3)
      - [ ] [Totemic Gaiters +3](https://www.bg-wiki.com/ffxi/Totemic_Gaiters_%2B3)
    - [ ] [Barbaroi Axe](https://www.bg-wiki.com/ffxi/Barbaroi_Axe)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Monster Armor Set](https://www.bg-wiki.com/ffxi/Monster_Armor_Set)
      - [ ] [Monster Helm](https://www.bg-wiki.com/ffxi/Monster_Helm)
      - [ ] [Monster Jackcoat](https://www.bg-wiki.com/ffxi/Monster_Jackcoat)
      - [ ] [Monster Trousers](https://www.bg-wiki.com/ffxi/Monster_Trousers)
      - [ ] [Monster Gaiters](https://www.bg-wiki.com/ffxi/Monster_Gaiters)
      - [ ] [Monster Gloves](https://www.bg-wiki.com/ffxi/Monster_Gloves)
    - [ ] [Monster Armor Set +1](https://www.bg-wiki.com/ffxi/Monster_Armor_Set_%2B1)
      - [ ] [Monster Helm +1](https://www.bg-wiki.com/ffxi/Monster_Helm_%2B1)
      - [ ] [Monster Jackcoat +1](https://www.bg-wiki.com/ffxi/Monster_Jackcoat_%2B1)
      - [ ] [Monster Trousers +1](https://www.bg-wiki.com/ffxi/Monster_Trousers_%2B1)
      - [ ] [Monster Gaiters +1](https://www.bg-wiki.com/ffxi/Monster_Gaiters_%2B1)
      - [ ] [Monster Gloves +1](https://www.bg-wiki.com/ffxi/Monster_Gloves_%2B1)
    - [ ] [Monster Armor Set +2](https://www.bg-wiki.com/ffxi/Monster_Armor_Set_%2B2)
      - [ ] [Monster Helm +2](https://www.bg-wiki.com/ffxi/Monster_Helm_%2B2)
      - [ ] [Monster Jackcoat +2](https://www.bg-wiki.com/ffxi/Monster_Jackcoat_%2B2)
      - [ ] [Monster Trousers +2](https://www.bg-wiki.com/ffxi/Monster_Trousers_%2B2)
      - [ ] [Monster Gaiters +2](https://www.bg-wiki.com/ffxi/Monster_Gaiters_%2B2)
      - [ ] [Monster Gloves +2](https://www.bg-wiki.com/ffxi/Monster_Gloves_%2B2)
    - [ ] [Ankusa Armor Set](https://www.bg-wiki.com/ffxi/Ankusa_Armor_Set)
      - [ ] [Ankusa Helm](https://www.bg-wiki.com/ffxi/Ankusa_Helm)
      - [ ] [Ankusa Jackcoat](https://www.bg-wiki.com/ffxi/Ankusa_Jackcoat)
      - [ ] [Ankusa Gloves](https://www.bg-wiki.com/ffxi/Ankusa_Gloves)
      - [ ] [Ankusa Trousers](https://www.bg-wiki.com/ffxi/Ankusa_Trousers)
      - [ ] [Ankusa Gaiters](https://www.bg-wiki.com/ffxi/Ankusa_Gaiters)
    - [ ] [Ankusa Armor Set +1](https://www.bg-wiki.com/ffxi/Ankusa_Armor_Set_%2B1)
      - [ ] [Ankusa Helm +1](https://www.bg-wiki.com/ffxi/Ankusa_Helm_%2B1)
      - [ ] [Ankusa Jackcoat +1](https://www.bg-wiki.com/ffxi/Ankusa_Jackcoat_%2B1)
      - [ ] [Ankusa Gloves +1](https://www.bg-wiki.com/ffxi/Ankusa_Gloves_%2B1)
      - [ ] [Ankusa Trousers +1](https://www.bg-wiki.com/ffxi/Ankusa_Trousers_%2B1)
      - [ ] [Ankusa Gaiters +1](https://www.bg-wiki.com/ffxi/Ankusa_Gaiters_%2B1)
    - [ ] [Ankusa Armor Set +2](https://www.bg-wiki.com/ffxi/Ankusa_Armor_Set_%2B2)
      - [ ] [Ankusa Helm +2](https://www.bg-wiki.com/ffxi/Ankusa_Helm_%2B2)
      - [ ] [Ankusa Jackcoat +2](https://www.bg-wiki.com/ffxi/Ankusa_Jackcoat_%2B2)
      - [ ] [Ankusa Gloves +2](https://www.bg-wiki.com/ffxi/Ankusa_Gloves_%2B2)
      - [ ] [Ankusa Trousers +2](https://www.bg-wiki.com/ffxi/Ankusa_Trousers_%2B2)
      - [ ] [Ankusa Gaiters +2](https://www.bg-wiki.com/ffxi/Ankusa_Gaiters_%2B2)
    - [ ] [Ankusa Armor Set +3](https://www.bg-wiki.com/ffxi/Ankusa_Armor_Set_%2B3)
      - [ ] [Ankusa Helm +3](https://www.bg-wiki.com/ffxi/Ankusa_Helm_%2B3)
      - [ ] [Ankusa Jackcoat +3](https://www.bg-wiki.com/ffxi/Ankusa_Jackcoat_%2B3)
      - [ ] [Ankusa Gloves +3](https://www.bg-wiki.com/ffxi/Ankusa_Gloves_%2B3)
      - [ ] [Ankusa Trousers +3](https://www.bg-wiki.com/ffxi/Ankusa_Trousers_%2B3)
      - [ ] [Ankusa Gaiters +3](https://www.bg-wiki.com/ffxi/Ankusa_Gaiters_%2B3)
    - [ ] [Monster Belt](https://www.bg-wiki.com/ffxi/Monster_Belt)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Beastmaster Collar](https://www.bg-wiki.com/ffxi/Beastmaster_Collar)
      - [ ] [Beastmaster Collar +1](https://www.bg-wiki.com/ffxi/Beastmaster_Collar_%2B1)
      - [ ] [Beastmaster Collar +2](https://www.bg-wiki.com/ffxi/Beastmaster_Collar_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Monster Axe](https://www.bg-wiki.com/ffxi/Monster_Axe)
      - [ ] [Ankusa Axe](https://www.bg-wiki.com/ffxi/Ankusa_Axe)
      - [ ] [Pangu](https://www.bg-wiki.com/ffxi/Pangu)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Ferine Armor Set](https://www.bg-wiki.com/ffxi/Ferine_Armor_Set)
      - [ ] [Ferine Ocreae](https://www.bg-wiki.com/ffxi/Ferine_Ocreae)
      - [ ] [Ferine Quijotes](https://www.bg-wiki.com/ffxi/Ferine_Quijotes)
      - [ ] [Ferine Cabasset](https://www.bg-wiki.com/ffxi/Ferine_Cabasset)
      - [ ] [Ferine Manoplas](https://www.bg-wiki.com/ffxi/Ferine_Manoplas)
      - [ ] [Ferine Gausape](https://www.bg-wiki.com/ffxi/Ferine_Gausape)
    - [ ] [Ferine Armor Set +1](https://www.bg-wiki.com/ffxi/Ferine_Armor_Set_%2B1)
      - [ ] [Ferine Ocreae +1](https://www.bg-wiki.com/ffxi/Ferine_Ocreae_%2B1)
      - [ ] [Ferine Quijotes +1](https://www.bg-wiki.com/ffxi/Ferine_Quijotes_%2B1)
      - [ ] [Ferine Cabasset +1](https://www.bg-wiki.com/ffxi/Ferine_Cabasset_%2B1)
      - [ ] [Ferine Manoplas +1](https://www.bg-wiki.com/ffxi/Ferine_Manoplas_%2B1)
      - [ ] [Ferine Gausape +1](https://www.bg-wiki.com/ffxi/Ferine_Gausape_%2B1)
    - [ ] [Ferine Armor Set +2](https://www.bg-wiki.com/ffxi/Ferine_Armor_Set_%2B2)
      - [ ] [Ferine Ocreae +2](https://www.bg-wiki.com/ffxi/Ferine_Ocreae_%2B2)
      - [ ] [Ferine Quijotes +2](https://www.bg-wiki.com/ffxi/Ferine_Quijotes_%2B2)
      - [ ] [Ferine Cabasset +2](https://www.bg-wiki.com/ffxi/Ferine_Cabasset_%2B2)
      - [ ] [Ferine Manoplas +2](https://www.bg-wiki.com/ffxi/Ferine_Manoplas_%2B2)
      - [ ] [Ferine Gausape +2](https://www.bg-wiki.com/ffxi/Ferine_Gausape_%2B2)
    - [ ] [Nukumi Armor Set](https://www.bg-wiki.com/ffxi/Nukumi_Armor_Set)
      - [ ] [Nukumi Cabasset](https://www.bg-wiki.com/ffxi/Nukumi_Cabasset)
      - [ ] [Nukumi Gausape](https://www.bg-wiki.com/ffxi/Nukumi_Gausape)
      - [ ] [Nukumi Manoplas](https://www.bg-wiki.com/ffxi/Nukumi_Manoplas)
      - [ ] [Nukumi Quijotes](https://www.bg-wiki.com/ffxi/Nukumi_Quijotes)
      - [ ] [Nukumi Ocreae](https://www.bg-wiki.com/ffxi/Nukumi_Ocreae)
    - [ ] [Nukumi Armor Set +1](https://www.bg-wiki.com/ffxi/Nukumi_Armor_Set_%2B1)
      - [ ] [Nukumi Cabasset +1](https://www.bg-wiki.com/ffxi/Nukumi_Cabasset_%2B1)
      - [ ] [Nukumi Gausape +1](https://www.bg-wiki.com/ffxi/Nukumi_Gausape_%2B1)
      - [ ] [Nukumi Manoplas +1](https://www.bg-wiki.com/ffxi/Nukumi_Manoplas_%2B1)
      - [ ] [Nukumi Quijotes +1](https://www.bg-wiki.com/ffxi/Nukumi_Quijotes_%2B1)
      - [ ] [Nukumi Ocreae +1](https://www.bg-wiki.com/ffxi/Nukumi_Ocreae_%2B1)
    - [ ] [Nukumi Armor Set +2](https://www.bg-wiki.com/ffxi/Nukumi_Armor_Set_%2B2)
      - [ ] [Nukumi Cabasset +2](https://www.bg-wiki.com/ffxi/Nukumi_Cabasset_%2B2)
      - [ ] [Nukumi Gausape +2](https://www.bg-wiki.com/ffxi/Nukumi_Gausape_%2B2)
      - [ ] [Nukumi Manoplas +2](https://www.bg-wiki.com/ffxi/Nukumi_Manoplas_%2B2)
      - [ ] [Nukumi Quijotes +2](https://www.bg-wiki.com/ffxi/Nukumi_Quijotes_%2B2)
      - [ ] [Nukumi Ocreae +2](https://www.bg-wiki.com/ffxi/Nukumi_Ocreae_%2B2)
    - [ ] [Nukumi Armor Set +3](https://www.bg-wiki.com/ffxi/Nukumi_Armor_Set_%2B3)
      - [ ] [Nukumi Cabasset +3](https://www.bg-wiki.com/ffxi/Nukumi_Cabasset_%2B3)
      - [ ] [Nukumi Gausape +3](https://www.bg-wiki.com/ffxi/Nukumi_Gausape_%2B3)
      - [ ] [Nukumi Manoplas +3](https://www.bg-wiki.com/ffxi/Nukumi_Manoplas_%2B3)
      - [ ] [Nukumi Quijotes +3](https://www.bg-wiki.com/ffxi/Nukumi_Quijotes_%2B3)
      - [ ] [Nukumi Ocreae +3](https://www.bg-wiki.com/ffxi/Nukumi_Ocreae_%2B3)
    - [ ] Accessories
      - [ ] [Ferine Mantle](https://www.bg-wiki.com/ffxi/Ferine_Mantle)
      - [ ] [Ferine Necklace](https://www.bg-wiki.com/ffxi/Ferine_Necklace)
      - [ ] [Ferine Earring](https://www.bg-wiki.com/ffxi/Ferine_Earring)
      - [ ] [Nukumi Earring](https://www.bg-wiki.com/ffxi/Nukumi_Earring)
      - [ ] [Nukumi Earring +1](https://www.bg-wiki.com/ffxi/Nukumi_Earring_%2B1)
      - [ ] [Nukumi Earring +2](https://www.bg-wiki.com/ffxi/Nukumi_Earring_%2B2)
