### ISSUE TITLE
BRD JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4399]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [BRD](https://www.bg-wiki.com/ffxi/Bard)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Choral Attire Set](https://www.bg-wiki.com/ffxi/Choral_Attire_Set)
      - [ ] [Choral Slippers](https://www.bg-wiki.com/ffxi/Choral_Slippers)
      - [ ] [Choral Roundlet](https://www.bg-wiki.com/ffxi/Choral_Roundlet)
      - [ ] [Choral Cannions](https://www.bg-wiki.com/ffxi/Choral_Cannions)
      - [ ] [Choral Justaucorps](https://www.bg-wiki.com/ffxi/Choral_Justaucorps)
      - [ ] [Choral Cuffs](https://www.bg-wiki.com/ffxi/Choral_Cuffs)
    - [ ] [Choral Attire Set +1](https://www.bg-wiki.com/ffxi/Choral_Attire_Set_%2B1)
      - [ ] [Choral Slippers +1](https://www.bg-wiki.com/ffxi/Choral_Slippers_%2B1)
      - [ ] [Choral Roundlet +1](https://www.bg-wiki.com/ffxi/Choral_Roundlet_%2B1)
      - [ ] [Choral Cannions +1](https://www.bg-wiki.com/ffxi/Choral_Cannions_%2B1)
      - [ ] [Choral Justaucorps +1](https://www.bg-wiki.com/ffxi/Choral_Justaucorps_%2B1)
      - [ ] [Choral Cuffs +1](https://www.bg-wiki.com/ffxi/Choral_Cuffs_%2B1)
    - [ ] [Brioso Attire Set](https://www.bg-wiki.com/ffxi/Brioso_Attire_Set)
      - [ ] [Brioso Roundlet](https://www.bg-wiki.com/ffxi/Brioso_Roundlet)
      - [ ] [Brioso Justaucorps](https://www.bg-wiki.com/ffxi/Brioso_Justaucorps)
      - [ ] [Brioso Cuffs](https://www.bg-wiki.com/ffxi/Brioso_Cuffs)
      - [ ] [Brioso Cannions](https://www.bg-wiki.com/ffxi/Brioso_Cannions)
      - [ ] [Brioso Slippers](https://www.bg-wiki.com/ffxi/Brioso_Slippers)
    - [ ] [Brioso Attire Set +1](https://www.bg-wiki.com/ffxi/Brioso_Attire_Set_%2B1)
      - [ ] [Brioso Roundlet +1](https://www.bg-wiki.com/ffxi/Brioso_Roundlet_%2B1)
      - [ ] [Brioso Justaucorps +1](https://www.bg-wiki.com/ffxi/Brioso_Justaucorps_%2B1)
      - [ ] [Brioso Cuffs +1](https://www.bg-wiki.com/ffxi/Brioso_Cuffs_%2B1)
      - [ ] [Brioso Cannions +1](https://www.bg-wiki.com/ffxi/Brioso_Cannions_%2B1)
      - [ ] [Brioso Slippers +1](https://www.bg-wiki.com/ffxi/Brioso_Slippers_%2B1)
    - [ ] [Brioso Attire Set +2](https://www.bg-wiki.com/ffxi/Brioso_Attire_Set_%2B2)
      - [ ] [Brioso Roundlet +2](https://www.bg-wiki.com/ffxi/Brioso_Roundlet_%2B2)
      - [ ] [Brioso Justaucorps +2](https://www.bg-wiki.com/ffxi/Brioso_Justaucorps_%2B2)
      - [ ] [Brioso Cuffs +2](https://www.bg-wiki.com/ffxi/Brioso_Cuffs_%2B2)
      - [ ] [Brioso Cannions +2](https://www.bg-wiki.com/ffxi/Brioso_Cannions_%2B2)
      - [ ] [Brioso Slippers +2](https://www.bg-wiki.com/ffxi/Brioso_Slippers_%2B2)
    - [ ] [Brioso Attire Set +3](https://www.bg-wiki.com/ffxi/Brioso_Attire_Set_%2B3)
      - [ ] [Brioso Roundlet +3](https://www.bg-wiki.com/ffxi/Brioso_Roundlet_%2B3)
      - [ ] [Brioso Justaucorps +3](https://www.bg-wiki.com/ffxi/Brioso_Justaucorps_%2B3)
      - [ ] [Brioso Cuffs +3](https://www.bg-wiki.com/ffxi/Brioso_Cuffs_%2B3)
      - [ ] [Brioso Cannions +3](https://www.bg-wiki.com/ffxi/Brioso_Cannions_%2B3)
      - [ ] [Brioso Slippers +3](https://www.bg-wiki.com/ffxi/Brioso_Slippers_%2B3)
    - [ ] [Paper Knife](https://www.bg-wiki.com/ffxi/Paper_Knife)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Bard's Attire Set](https://www.bg-wiki.com/ffxi/Bard%27s_Attire_Set)
      - [ ] [Bard's Slippers](https://www.bg-wiki.com/ffxi/Bard%27s_Slippers)
      - [ ] [Bard's Roundlet](https://www.bg-wiki.com/ffxi/Bard%27s_Roundlet)
      - [ ] [Bard's Cuffs](https://www.bg-wiki.com/ffxi/Bard%27s_Cuffs)
      - [ ] [Bard's Justaucorps](https://www.bg-wiki.com/ffxi/Bard%27s_Justaucorps)
      - [ ] [Bard's Cannions](https://www.bg-wiki.com/ffxi/Bard%27s_Cannions)
    - [ ] [Bard's Attire Set +1](https://www.bg-wiki.com/ffxi/Bard%27s_Attire_Set_%2B1)
      - [ ] [Bard's Slippers +1](https://www.bg-wiki.com/ffxi/Bard%27s_Slippers_%2B1)
      - [ ] [Bard's Roundlet +1](https://www.bg-wiki.com/ffxi/Bard%27s_Roundlet_%2B1)
      - [ ] [Bard's Cuffs +1](https://www.bg-wiki.com/ffxi/Bard%27s_Cuffs_%2B1)
      - [ ] [Bard's Justaucorps +1](https://www.bg-wiki.com/ffxi/Bard%27s_Justaucorps_%2B1)
      - [ ] [Bard's Cannions +1](https://www.bg-wiki.com/ffxi/Bard%27s_Cannions_%2B1)
    - [ ] [Bard's Attire Set +2](https://www.bg-wiki.com/ffxi/Bard%27s_Attire_Set_%2B2)
      - [ ] [Bard's Slippers +2](https://www.bg-wiki.com/ffxi/Bard%27s_Slippers_%2B2)
      - [ ] [Bard's Roundlet +2](https://www.bg-wiki.com/ffxi/Bard%27s_Roundlet_%2B2)
      - [ ] [Bard's Cuffs +2](https://www.bg-wiki.com/ffxi/Bard%27s_Cuffs_%2B2)
      - [ ] [Bard's Justaucorps +2](https://www.bg-wiki.com/ffxi/Bard%27s_Justaucorps_%2B2)
      - [ ] [Bard's Cannions +2](https://www.bg-wiki.com/ffxi/Bard%27s_Cannions_%2B2)
    - [ ] [Bihu Attire Set](https://www.bg-wiki.com/ffxi/Bihu_Attire_Set)
      - [ ] [Bihu Roundlet](https://www.bg-wiki.com/ffxi/Bihu_Roundlet)
      - [ ] [Bihu Justaucorps](https://www.bg-wiki.com/ffxi/Bihu_Justaucorps)
      - [ ] [Bihu Cuffs](https://www.bg-wiki.com/ffxi/Bihu_Cuffs)
      - [ ] [Bihu Cannions](https://www.bg-wiki.com/ffxi/Bihu_Cannions)
      - [ ] [Bihu Slippers](https://www.bg-wiki.com/ffxi/Bihu_Slippers)
    - [ ] [Bihu Attire Set +1](https://www.bg-wiki.com/ffxi/Bihu_Attire_Set_%2B1)
      - [ ] [Bihu Roundlet +1](https://www.bg-wiki.com/ffxi/Bihu_Roundlet_%2B1)
      - [ ] [Bihu Justaucorps +1](https://www.bg-wiki.com/ffxi/Bihu_Justaucorps_%2B1)
      - [ ] [Bihu Cuffs +1](https://www.bg-wiki.com/ffxi/Bihu_Cuffs_%2B1)
      - [ ] [Bihu Cannions +1](https://www.bg-wiki.com/ffxi/Bihu_Cannions_%2B1)
      - [ ] [Bihu Slippers +1](https://www.bg-wiki.com/ffxi/Bihu_Slippers_%2B1)
    - [ ] [Bihu Attire Set +2](https://www.bg-wiki.com/ffxi/Bihu_Attire_Set_%2B2)
      - [ ] [Bihu Roundlet +2](https://www.bg-wiki.com/ffxi/Bihu_Roundlet_%2B2)
      - [ ] [Bihu Justaucorps +2](https://www.bg-wiki.com/ffxi/Bihu_Justaucorps_%2B2)
      - [ ] [Bihu Cuffs +2](https://www.bg-wiki.com/ffxi/Bihu_Cuffs_%2B2)
      - [ ] [Bihu Cannions +2](https://www.bg-wiki.com/ffxi/Bihu_Cannions_%2B2)
      - [ ] [Bihu Slippers +2](https://www.bg-wiki.com/ffxi/Bihu_Slippers_%2B2)
    - [ ] [Bihu Attire Set +3](https://www.bg-wiki.com/ffxi/Bihu_Attire_Set_%2B3)
      - [ ] [Bihu Roundlet +3](https://www.bg-wiki.com/ffxi/Bihu_Roundlet_%2B3)
      - [ ] [Bihu Justaucorps +3](https://www.bg-wiki.com/ffxi/Bihu_Justaucorps_%2B3)
      - [ ] [Bihu Cuffs +3](https://www.bg-wiki.com/ffxi/Bihu_Cuffs_%2B3)
      - [ ] [Bihu Cannions +3](https://www.bg-wiki.com/ffxi/Bihu_Cannions_%2B3)
      - [ ] [Bihu Slippers +3](https://www.bg-wiki.com/ffxi/Bihu_Slippers_%2B3)
    - [ ] [Bard's Cape](https://www.bg-wiki.com/ffxi/Bard%27s_Cape)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Bard's Charm](https://www.bg-wiki.com/ffxi/Bard%27s_Charm)
      - [ ] [Bard's Charm +1](https://www.bg-wiki.com/ffxi/Bard%27s_Charm_%2B1)
      - [ ] [Bard's Charm +2](https://www.bg-wiki.com/ffxi/Bard%27s_Charm_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Bard's Knife](https://www.bg-wiki.com/ffxi/Bard%27s_Knife)
      - [ ] [Bihu Knife](https://www.bg-wiki.com/ffxi/Bihu_Knife)
      - [ ] [Barfawc](https://www.bg-wiki.com/ffxi/Barfawc)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Aoidos' Attire Set](https://www.bg-wiki.com/ffxi/Aoidos%27_Attire_Set)
      - [ ] [Aoidos' Cothurnes](https://www.bg-wiki.com/ffxi/Aoidos%27_Cothurnes)
      - [ ] [Aoidos' Rhingrave](https://www.bg-wiki.com/ffxi/Aoidos%27_Rhingrave)
      - [ ] [Aoidos' Calot](https://www.bg-wiki.com/ffxi/Aoidos%27_Calot)
      - [ ] [Aoidos' Manchettes](https://www.bg-wiki.com/ffxi/Aoidos%27_Manchettes)
      - [ ] [Aoidos' Hongreline](https://www.bg-wiki.com/ffxi/Aoidos%27_Hongreline)
    - [ ] [Aoidos' Attire Set +1](https://www.bg-wiki.com/ffxi/Aoidos%27_Attire_Set_%2B1)
      - [ ] [Aoidos' Cothurnes +1](https://www.bg-wiki.com/ffxi/Aoidos%27_Cothurnes_%2B1)
      - [ ] [Aoidos' Rhingrave +1](https://www.bg-wiki.com/ffxi/Aoidos%27_Rhingrave_%2B1)
      - [ ] [Aoidos' Calot +1](https://www.bg-wiki.com/ffxi/Aoidos%27_Calot_%2B1)
      - [ ] [Aoidos' Manchettes +1](https://www.bg-wiki.com/ffxi/Aoidos%27_Manchettes_%2B1)
      - [ ] [Aoidos' Hongreline +1](https://www.bg-wiki.com/ffxi/Aoidos%27_Hongreline_%2B1)
    - [ ] [Aoidos' Attire Set +2](https://www.bg-wiki.com/ffxi/Aoidos%27_Attire_Set_%2B2)
      - [ ] [Aoidos' Cothurnes +2](https://www.bg-wiki.com/ffxi/Aoidos%27_Cothurnes_%2B2)
      - [ ] [Aoidos' Rhingrave +2](https://www.bg-wiki.com/ffxi/Aoidos%27_Rhingrave_%2B2)
      - [ ] [Aoidos' Calot +2](https://www.bg-wiki.com/ffxi/Aoidos%27_Calot_%2B2)
      - [ ] [Aoidos' Manchettes +2](https://www.bg-wiki.com/ffxi/Aoidos%27_Manchettes_%2B2)
      - [ ] [Aoidos' Hongreline +2](https://www.bg-wiki.com/ffxi/Aoidos%27_Hongreline_%2B2)
    - [ ] [Fili Attire Set](https://www.bg-wiki.com/ffxi/Fili_Attire_Set)
      - [ ] [Fili Calot](https://www.bg-wiki.com/ffxi/Fili_Calot)
      - [ ] [Fili Hongreline](https://www.bg-wiki.com/ffxi/Fili_Hongreline)
      - [ ] [Fili Manchettes](https://www.bg-wiki.com/ffxi/Fili_Manchettes)
      - [ ] [Fili Rhingrave](https://www.bg-wiki.com/ffxi/Fili_Rhingrave)
      - [ ] [Fili Cothurnes](https://www.bg-wiki.com/ffxi/Fili_Cothurnes)
    - [ ] [Fili Attire Set +1](https://www.bg-wiki.com/ffxi/Fili_Attire_Set_%2B1)
      - [ ] [Fili Calot +1](https://www.bg-wiki.com/ffxi/Fili_Calot_%2B1)
      - [ ] [Fili Hongreline +1](https://www.bg-wiki.com/ffxi/Fili_Hongreline_%2B1)
      - [ ] [Fili Manchettes +1](https://www.bg-wiki.com/ffxi/Fili_Manchettes_%2B1)
      - [ ] [Fili Rhingrave +1](https://www.bg-wiki.com/ffxi/Fili_Rhingrave_%2B1)
      - [ ] [Fili Cothurnes +1](https://www.bg-wiki.com/ffxi/Fili_Cothurnes_%2B1)
    - [ ] [Fili Attire Set +2](https://www.bg-wiki.com/ffxi/Fili_Attire_Set_%2B2)
      - [ ] [Fili Calot +2](https://www.bg-wiki.com/ffxi/Fili_Calot_%2B2)
      - [ ] [Fili Hongreline +2](https://www.bg-wiki.com/ffxi/Fili_Hongreline_%2B2)
      - [ ] [Fili Manchettes +2](https://www.bg-wiki.com/ffxi/Fili_Manchettes_%2B2)
      - [ ] [Fili Rhingrave +2](https://www.bg-wiki.com/ffxi/Fili_Rhingrave_%2B2)
      - [ ] [Fili Cothurnes +2](https://www.bg-wiki.com/ffxi/Fili_Cothurnes_%2B2)
    - [ ] [Fili Attire Set +3](https://www.bg-wiki.com/ffxi/Fili_Attire_Set_%2B3)
      - [ ] [Fili Calot +3](https://www.bg-wiki.com/ffxi/Fili_Calot_%2B3)
      - [ ] [Fili Hongreline +3](https://www.bg-wiki.com/ffxi/Fili_Hongreline_%2B3)
      - [ ] [Fili Manchettes +3](https://www.bg-wiki.com/ffxi/Fili_Manchettes_%2B3)
      - [ ] [Fili Rhingrave +3](https://www.bg-wiki.com/ffxi/Fili_Rhingrave_%2B3)
      - [ ] [Fili Cothurnes +3](https://www.bg-wiki.com/ffxi/Fili_Cothurnes_%2B3)
    - [ ] Accessories
      - [ ] [Aoidos' Belt](https://www.bg-wiki.com/ffxi/Aoidos%27_Belt)
      - [ ] [Aoidos' Matinee](https://www.bg-wiki.com/ffxi/Aoidos%27_Matinee)
      - [ ] [Aoidos' Earring](https://www.bg-wiki.com/ffxi/Aoidos%27_Earring)
      - [ ] [Fili Earring](https://www.bg-wiki.com/ffxi/Fili_Earring)
      - [ ] [Fili Earring +1](https://www.bg-wiki.com/ffxi/Fili_Earring_%2B1)
      - [ ] [Fili Earring +2](https://www.bg-wiki.com/ffxi/Fili_Earring_%2B2)
