### ISSUE TITLE
RNG JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4400]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [RNG](https://www.bg-wiki.com/ffxi/Ranger)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Hunter's Attire Set](https://www.bg-wiki.com/ffxi/Hunter%27s_Attire_Set)
      - [ ] [Hunter's Bracers](https://www.bg-wiki.com/ffxi/Hunter%27s_Bracers)
      - [ ] [Hunter's Beret](https://www.bg-wiki.com/ffxi/Hunter%27s_Beret)
      - [ ] [Hunter's Braccae](https://www.bg-wiki.com/ffxi/Hunter%27s_Braccae)
      - [ ] [Hunter's Jerkin](https://www.bg-wiki.com/ffxi/Hunter%27s_Jerkin)
      - [ ] [Hunter's Socks](https://www.bg-wiki.com/ffxi/Hunter%27s_Socks)
    - [ ] [Hunter's Attire Set +1](https://www.bg-wiki.com/ffxi/Hunter%27s_Attire_Set_%2B1)
      - [ ] [Hunter's Bracers +1](https://www.bg-wiki.com/ffxi/Hunter%27s_Bracers_%2B1)
      - [ ] [Hunter's Beret +1](https://www.bg-wiki.com/ffxi/Hunter%27s_Beret_%2B1)
      - [ ] [Hunter's Braccae +1](https://www.bg-wiki.com/ffxi/Hunter%27s_Braccae_%2B1)
      - [ ] [Hunter's Jerkin +1](https://www.bg-wiki.com/ffxi/Hunter%27s_Jerkin_%2B1)
      - [ ] [Hunter's Socks +1](https://www.bg-wiki.com/ffxi/Hunter%27s_Socks_%2B1)
    - [ ] [Orion Attire Set](https://www.bg-wiki.com/ffxi/Orion_Attire_Set)
      - [ ] [Orion Beret](https://www.bg-wiki.com/ffxi/Orion_Beret)
      - [ ] [Orion Jerkin](https://www.bg-wiki.com/ffxi/Orion_Jerkin)
      - [ ] [Orion Bracers](https://www.bg-wiki.com/ffxi/Orion_Bracers)
      - [ ] [Orion Braccae](https://www.bg-wiki.com/ffxi/Orion_Braccae)
      - [ ] [Orion Socks](https://www.bg-wiki.com/ffxi/Orion_Socks)
    - [ ] [Orion Attire Set +1](https://www.bg-wiki.com/ffxi/Orion_Attire_Set_%2B1)
      - [ ] [Orion Beret +1](https://www.bg-wiki.com/ffxi/Orion_Beret_%2B1)
      - [ ] [Orion Jerkin +1](https://www.bg-wiki.com/ffxi/Orion_Jerkin_%2B1)
      - [ ] [Orion Bracers +1](https://www.bg-wiki.com/ffxi/Orion_Bracers_%2B1)
      - [ ] [Orion Braccae +1](https://www.bg-wiki.com/ffxi/Orion_Braccae_%2B1)
      - [ ] [Orion Socks +1](https://www.bg-wiki.com/ffxi/Orion_Socks_%2B1)
    - [ ] [Orion Attire Set +2](https://www.bg-wiki.com/ffxi/Orion_Attire_Set_%2B2)
      - [ ] [Orion Beret +2](https://www.bg-wiki.com/ffxi/Orion_Beret_%2B2)
      - [ ] [Orion Jerkin +2](https://www.bg-wiki.com/ffxi/Orion_Jerkin_%2B2)
      - [ ] [Orion Bracers +2](https://www.bg-wiki.com/ffxi/Orion_Bracers_%2B2)
      - [ ] [Orion Braccae +2](https://www.bg-wiki.com/ffxi/Orion_Braccae_%2B2)
      - [ ] [Orion Socks +2](https://www.bg-wiki.com/ffxi/Orion_Socks_%2B2)
    - [ ] [Orion Attire Set +3](https://www.bg-wiki.com/ffxi/Orion_Attire_Set_%2B3)
      - [ ] [Orion Beret +3](https://www.bg-wiki.com/ffxi/Orion_Beret_%2B3)
      - [ ] [Orion Jerkin +3](https://www.bg-wiki.com/ffxi/Orion_Jerkin_%2B3)
      - [ ] [Orion Bracers +3](https://www.bg-wiki.com/ffxi/Orion_Bracers_%2B3)
      - [ ] [Orion Braccae +3](https://www.bg-wiki.com/ffxi/Orion_Braccae_%2B3)
      - [ ] [Orion Socks +3](https://www.bg-wiki.com/ffxi/Orion_Socks_%2B3)
    - [ ] [Sniping Bow](https://www.bg-wiki.com/ffxi/Sniping_Bow)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Scout's Attire Set](https://www.bg-wiki.com/ffxi/Scout%27s_Attire_Set)
      - [ ] [Scout's Bracers](https://www.bg-wiki.com/ffxi/Scout%27s_Bracers)
      - [ ] [Scout's Braccae](https://www.bg-wiki.com/ffxi/Scout%27s_Braccae)
      - [ ] [Scout's Beret](https://www.bg-wiki.com/ffxi/Scout%27s_Beret)
      - [ ] [Scout's Socks](https://www.bg-wiki.com/ffxi/Scout%27s_Socks)
      - [ ] [Scout's Jerkin](https://www.bg-wiki.com/ffxi/Scout%27s_Jerkin)
    - [ ] [Scout's Attire Set +1](https://www.bg-wiki.com/ffxi/Scout%27s_Attire_Set_%2B1)
      - [ ] [Scout's Bracers +1](https://www.bg-wiki.com/ffxi/Scout%27s_Bracers_%2B1)
      - [ ] [Scout's Braccae +1](https://www.bg-wiki.com/ffxi/Scout%27s_Braccae_%2B1)
      - [ ] [Scout's Beret +1](https://www.bg-wiki.com/ffxi/Scout%27s_Beret_%2B1)
      - [ ] [Scout's Socks +1](https://www.bg-wiki.com/ffxi/Scout%27s_Socks_%2B1)
      - [ ] [Scout's Jerkin +1](https://www.bg-wiki.com/ffxi/Scout%27s_Jerkin_%2B1)
    - [ ] [Scout's Attire Set +2](https://www.bg-wiki.com/ffxi/Scout%27s_Attire_Set_%2B2)
      - [ ] [Scout's Bracers +2](https://www.bg-wiki.com/ffxi/Scout%27s_Bracers_%2B2)
      - [ ] [Scout's Braccae +2](https://www.bg-wiki.com/ffxi/Scout%27s_Braccae_%2B2)
      - [ ] [Scout's Beret +2](https://www.bg-wiki.com/ffxi/Scout%27s_Beret_%2B2)
      - [ ] [Scout's Socks +2](https://www.bg-wiki.com/ffxi/Scout%27s_Socks_%2B2)
      - [ ] [Scout's Jerkin +2](https://www.bg-wiki.com/ffxi/Scout%27s_Jerkin_%2B2)
    - [ ] [Arcadian Attire Set](https://www.bg-wiki.com/ffxi/Arcadian_Attire_Set)
      - [ ] [Arcadian Beret](https://www.bg-wiki.com/ffxi/Arcadian_Beret)
      - [ ] [Arcadian Jerkin](https://www.bg-wiki.com/ffxi/Arcadian_Jerkin)
      - [ ] [Arcadian Bracers](https://www.bg-wiki.com/ffxi/Arcadian_Bracers)
      - [ ] [Arcadian Braccae](https://www.bg-wiki.com/ffxi/Arcadian_Braccae)
      - [ ] [Arcadian Socks](https://www.bg-wiki.com/ffxi/Arcadian_Socks)
    - [ ] [Arcadian Attire Set +1](https://www.bg-wiki.com/ffxi/Arcadian_Attire_Set_%2B1)
      - [ ] [Arcadian Beret +1](https://www.bg-wiki.com/ffxi/Arcadian_Beret_%2B1)
      - [ ] [Arcadian Jerkin +1](https://www.bg-wiki.com/ffxi/Arcadian_Jerkin_%2B1)
      - [ ] [Arcadian Bracers +1](https://www.bg-wiki.com/ffxi/Arcadian_Bracers_%2B1)
      - [ ] [Arcadian Braccae +1](https://www.bg-wiki.com/ffxi/Arcadian_Braccae_%2B1)
      - [ ] [Arcadian Socks +1](https://www.bg-wiki.com/ffxi/Arcadian_Socks_%2B1)
    - [ ] [Arcadian Attire Set +2](https://www.bg-wiki.com/ffxi/Arcadian_Attire_Set_%2B2)
      - [ ] [Arcadian Beret +2](https://www.bg-wiki.com/ffxi/Arcadian_Beret_%2B2)
      - [ ] [Arcadian Jerkin +2](https://www.bg-wiki.com/ffxi/Arcadian_Jerkin_%2B2)
      - [ ] [Arcadian Bracers +2](https://www.bg-wiki.com/ffxi/Arcadian_Bracers_%2B2)
      - [ ] [Arcadian Braccae +2](https://www.bg-wiki.com/ffxi/Arcadian_Braccae_%2B2)
      - [ ] [Arcadian Socks +2](https://www.bg-wiki.com/ffxi/Arcadian_Socks_%2B2)
    - [ ] [Arcadian Attire Set +3](https://www.bg-wiki.com/ffxi/Arcadian_Attire_Set_%2B3)
      - [ ] [Arcadian Beret +3](https://www.bg-wiki.com/ffxi/Arcadian_Beret_%2B3)
      - [ ] [Arcadian Jerkin +3](https://www.bg-wiki.com/ffxi/Arcadian_Jerkin_%2B3)
      - [ ] [Arcadian Bracers +3](https://www.bg-wiki.com/ffxi/Arcadian_Bracers_%2B3)
      - [ ] [Arcadian Braccae +3](https://www.bg-wiki.com/ffxi/Arcadian_Braccae_%2B3)
      - [ ] [Arcadian Socks +3](https://www.bg-wiki.com/ffxi/Arcadian_Socks_%2B3)
    - [ ] [Scout's Belt](https://www.bg-wiki.com/ffxi/Scout%27s_Belt)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Scout's Gorget](https://www.bg-wiki.com/ffxi/Scout%27s_Gorget)
      - [ ] [Scout's Gorget +1](https://www.bg-wiki.com/ffxi/Scout%27s_Gorget_%2B1)
      - [ ] [Scout's Gorget +2](https://www.bg-wiki.com/ffxi/Scout%27s_Gorget_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Scout's Crossbow](https://www.bg-wiki.com/ffxi/Scout%27s_Crossbow)
      - [ ] [Arke Crossbow](https://www.bg-wiki.com/ffxi/Arke_Crossbow)
      - [ ] [Sharanga](https://www.bg-wiki.com/ffxi/Sharanga)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Sylvan Attire Set](https://www.bg-wiki.com/ffxi/Sylvan_Attire_Set)
      - [ ] [Sylvan Bottillons](https://www.bg-wiki.com/ffxi/Sylvan_Bottillons)
      - [ ] [Sylvan Bragues](https://www.bg-wiki.com/ffxi/Sylvan_Bragues)
      - [ ] [Sylvan Gapette](https://www.bg-wiki.com/ffxi/Sylvan_Gapette)
      - [ ] [Sylvan Glovelettes](https://www.bg-wiki.com/ffxi/Sylvan_Glovelettes)
      - [ ] [Sylvan Caban](https://www.bg-wiki.com/ffxi/Sylvan_Caban)
    - [ ] [Sylvan Attire Set +1](https://www.bg-wiki.com/ffxi/Sylvan_Attire_Set_%2B1)
      - [ ] [Sylvan Bottillons +1](https://www.bg-wiki.com/ffxi/Sylvan_Bottillons_%2B1)
      - [ ] [Sylvan Bragues +1](https://www.bg-wiki.com/ffxi/Sylvan_Bragues_%2B1)
      - [ ] [Sylvan Gapette +1](https://www.bg-wiki.com/ffxi/Sylvan_Gapette_%2B1)
      - [ ] [Sylvan Glovelettes +1](https://www.bg-wiki.com/ffxi/Sylvan_Glovelettes_%2B1)
      - [ ] [Sylvan Caban +1](https://www.bg-wiki.com/ffxi/Sylvan_Caban_%2B1)
    - [ ] [Sylvan Attire Set +2](https://www.bg-wiki.com/ffxi/Sylvan_Attire_Set_%2B2)
      - [ ] [Sylvan Bottillons +2](https://www.bg-wiki.com/ffxi/Sylvan_Bottillons_%2B2)
      - [ ] [Sylvan Bragues +2](https://www.bg-wiki.com/ffxi/Sylvan_Bragues_%2B2)
      - [ ] [Sylvan Gapette +2](https://www.bg-wiki.com/ffxi/Sylvan_Gapette_%2B2)
      - [ ] [Sylvan Glovelettes +2](https://www.bg-wiki.com/ffxi/Sylvan_Glovelettes_%2B2)
      - [ ] [Sylvan Caban +2](https://www.bg-wiki.com/ffxi/Sylvan_Caban_%2B2)
    - [ ] [Amini Attire Set](https://www.bg-wiki.com/ffxi/Amini_Attire_Set)
      - [ ] [Amini Gapette](https://www.bg-wiki.com/ffxi/Amini_Gapette)
      - [ ] [Amini Caban](https://www.bg-wiki.com/ffxi/Amini_Caban)
      - [ ] [Amini Glovelettes](https://www.bg-wiki.com/ffxi/Amini_Glovelettes)
      - [ ] [Amini Brague](https://www.bg-wiki.com/ffxi/Amini_Brague)
      - [ ] [Amini Bottillons](https://www.bg-wiki.com/ffxi/Amini_Bottillons)
    - [ ] [Amini Attire Set +1](https://www.bg-wiki.com/ffxi/Amini_Attire_Set_%2B1)
      - [ ] [Amini Gapette +1](https://www.bg-wiki.com/ffxi/Amini_Gapette_%2B1)
      - [ ] [Amini Caban +1](https://www.bg-wiki.com/ffxi/Amini_Caban_%2B1)
      - [ ] [Amini Glovelettes +1](https://www.bg-wiki.com/ffxi/Amini_Glovelettes_%2B1)
      - [ ] [Amini Brague +1](https://www.bg-wiki.com/ffxi/Amini_Brague_%2B1)
      - [ ] [Amini Bottillons +1](https://www.bg-wiki.com/ffxi/Amini_Bottillons_%2B1)
    - [ ] [Amini Attire Set +2](https://www.bg-wiki.com/ffxi/Amini_Attire_Set_%2B2)
      - [ ] [Amini Gapette +2](https://www.bg-wiki.com/ffxi/Amini_Gapette_%2B2)
      - [ ] [Amini Caban +2](https://www.bg-wiki.com/ffxi/Amini_Caban_%2B2)
      - [ ] [Amini Glovelettes +2](https://www.bg-wiki.com/ffxi/Amini_Glovelettes_%2B2)
      - [ ] [Amini Brague +2](https://www.bg-wiki.com/ffxi/Amini_Brague_%2B2)
      - [ ] [Amini Bottillons +2](https://www.bg-wiki.com/ffxi/Amini_Bottillons_%2B2)
    - [ ] [Amini Attire Set +3](https://www.bg-wiki.com/ffxi/Amini_Attire_Set_%2B3)
      - [ ] [Amini Gapette +3](https://www.bg-wiki.com/ffxi/Amini_Gapette_%2B3)
      - [ ] [Amini Caban +3](https://www.bg-wiki.com/ffxi/Amini_Caban_%2B3)
      - [ ] [Amini Glovelettes +3](https://www.bg-wiki.com/ffxi/Amini_Glovelettes_%2B3)
      - [ ] [Amini Brague +3](https://www.bg-wiki.com/ffxi/Amini_Brague_%2B3)
      - [ ] [Amini Bottillons +3](https://www.bg-wiki.com/ffxi/Amini_Bottillons_%2B3)
    - [ ] Accessories
      - [ ] [Sylvan Scarf](https://www.bg-wiki.com/ffxi/Sylvan_Scarf)
      - [ ] [Sylvan Chlamys](https://www.bg-wiki.com/ffxi/Sylvan_Chlamys)
      - [ ] [Sylvan Earring](https://www.bg-wiki.com/ffxi/Sylvan_Earring)
      - [ ] [Amini Earring](https://www.bg-wiki.com/ffxi/Amini_Earring)
      - [ ] [Amini Earring +1](https://www.bg-wiki.com/ffxi/Amini_Earring_%2B1)
      - [ ] [Amini Earring +2](https://www.bg-wiki.com/ffxi/Amini_Earring_%2B2)
