### ISSUE TITLE
SMN JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4401]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [SMN](https://www.bg-wiki.com/ffxi/Summoner)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Evoker's Attire Set](https://www.bg-wiki.com/ffxi/Evoker%27s_Attire_Set)
      - [ ] [Evoker's Spats](https://www.bg-wiki.com/ffxi/Evoker%27s_Spats)
      - [ ] [Evoker's Bracers](https://www.bg-wiki.com/ffxi/Evoker%27s_Bracers)
      - [ ] [Evoker's Pigaches](https://www.bg-wiki.com/ffxi/Evoker%27s_Pigaches)
      - [ ] [Evoker's Doublet](https://www.bg-wiki.com/ffxi/Evoker%27s_Doublet)
      - [ ] [Evoker's Horn](https://www.bg-wiki.com/ffxi/Evoker%27s_Horn)
    - [ ] [Evoker's Attire Set +1](https://www.bg-wiki.com/ffxi/Evoker%27s_Attire_Set_%2B1)
      - [ ] [Evoker's Spats +1](https://www.bg-wiki.com/ffxi/Evoker%27s_Spats_%2B1)
      - [ ] [Evoker's Bracers +1](https://www.bg-wiki.com/ffxi/Evoker%27s_Bracers_%2B1)
      - [ ] [Evoker's Pigaches +1](https://www.bg-wiki.com/ffxi/Evoker%27s_Pigaches_%2B1)
      - [ ] [Evoker's Doublet +1](https://www.bg-wiki.com/ffxi/Evoker%27s_Doublet_%2B1)
      - [ ] [Evoker's Horn +1](https://www.bg-wiki.com/ffxi/Evoker%27s_Horn_%2B1)
    - [ ] [Convoker's Attire Set](https://www.bg-wiki.com/ffxi/Convoker%27s_Attire_Set)
      - [ ] [Convoker's Horn](https://www.bg-wiki.com/ffxi/Convoker%27s_Horn)
      - [ ] [Convoker's Doublet](https://www.bg-wiki.com/ffxi/Convoker%27s_Doublet)
      - [ ] [Convoker's Bracers](https://www.bg-wiki.com/ffxi/Convoker%27s_Bracers)
      - [ ] [Convoker's Spats](https://www.bg-wiki.com/ffxi/Convoker%27s_Spats)
      - [ ] [Convoker's Pigaches](https://www.bg-wiki.com/ffxi/Convoker%27s_Pigaches)
    - [ ] [Convoker's Attire Set +1](https://www.bg-wiki.com/ffxi/Convoker%27s_Attire_Set_%2B1)
      - [ ] [Convoker's Horn +1](https://www.bg-wiki.com/ffxi/Convoker%27s_Horn_%2B1)
      - [ ] [Convoker's Doublet +1](https://www.bg-wiki.com/ffxi/Convoker%27s_Doublet_%2B1)
      - [ ] [Convoker's Bracers +1](https://www.bg-wiki.com/ffxi/Convoker%27s_Bracers_%2B1)
      - [ ] [Convoker's Spats +1](https://www.bg-wiki.com/ffxi/Convoker%27s_Spats_%2B1)
      - [ ] [Convoker's Pigaches +1](https://www.bg-wiki.com/ffxi/Convoker%27s_Pigaches_%2B1)
    - [ ] [Convoker's Attire Set +2](https://www.bg-wiki.com/ffxi/Convoker%27s_Attire_Set_%2B2)
      - [ ] [Convoker's Horn +2](https://www.bg-wiki.com/ffxi/Convoker%27s_Horn_%2B2)
      - [ ] [Convoker's Doublet +2](https://www.bg-wiki.com/ffxi/Convoker%27s_Doublet_%2B2)
      - [ ] [Convoker's Bracers +2](https://www.bg-wiki.com/ffxi/Convoker%27s_Bracers_%2B2)
      - [ ] [Convoker's Spats +2](https://www.bg-wiki.com/ffxi/Convoker%27s_Spats_%2B2)
      - [ ] [Convoker's Pigaches +2](https://www.bg-wiki.com/ffxi/Convoker%27s_Pigaches_%2B2)
    - [ ] [Convoker's Attire Set +3](https://www.bg-wiki.com/ffxi/Convoker%27s_Attire_Set_%2B3)
      - [ ] [Convoker's Horn +3](https://www.bg-wiki.com/ffxi/Convoker%27s_Horn_%2B3)
      - [ ] [Convoker's Doublet +3](https://www.bg-wiki.com/ffxi/Convoker%27s_Doublet_%2B3)
      - [ ] [Convoker's Bracers +3](https://www.bg-wiki.com/ffxi/Convoker%27s_Bracers_%2B3)
      - [ ] [Convoker's Spats +3](https://www.bg-wiki.com/ffxi/Convoker%27s_Spats_%2B3)
      - [ ] [Convoker's Pigaches +3](https://www.bg-wiki.com/ffxi/Convoker%27s_Pigaches_%2B3)
    - [ ] [Kukulcan's Staff](https://www.bg-wiki.com/ffxi/Kukulcan%27s_Staff)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Summoner's Attire Set](https://www.bg-wiki.com/ffxi/Summoner%27s_Attire_Set)
      - [ ] [Summoner's Spats](https://www.bg-wiki.com/ffxi/Summoner%27s_Spats)
      - [ ] [Summoner's Bracers](https://www.bg-wiki.com/ffxi/Summoner%27s_Bracers)
      - [ ] [Summoner's Pigaches](https://www.bg-wiki.com/ffxi/Summoner%27s_Pigaches)
      - [ ] [Summoner's Doublet](https://www.bg-wiki.com/ffxi/Summoner%27s_Doublet)
      - [ ] [Summoner's Horn](https://www.bg-wiki.com/ffxi/Summoner%27s_Horn)
    - [ ] [Summoner's Attire Set +1](https://www.bg-wiki.com/ffxi/Summoner%27s_Attire_Set_%2B1)
      - [ ] [Summoner's Spats +1](https://www.bg-wiki.com/ffxi/Summoner%27s_Spats_%2B1)
      - [ ] [Summoner's Bracers +1](https://www.bg-wiki.com/ffxi/Summoner%27s_Bracers_%2B1)
      - [ ] [Summoner's Pigaches +1](https://www.bg-wiki.com/ffxi/Summoner%27s_Pigaches_%2B1)
      - [ ] [Summoner's Doublet +1](https://www.bg-wiki.com/ffxi/Summoner%27s_Doublet_%2B1)
      - [ ] [Summoner's Horn +1](https://www.bg-wiki.com/ffxi/Summoner%27s_Horn_%2B1)
    - [ ] [Summoner's Attire Set +2](https://www.bg-wiki.com/ffxi/Summoner%27s_Attire_Set_%2B2)
      - [ ] [Summoner's Spats +2](https://www.bg-wiki.com/ffxi/Summoner%27s_Spats_%2B2)
      - [ ] [Summoner's Bracers +2](https://www.bg-wiki.com/ffxi/Summoner%27s_Bracers_%2B2)
      - [ ] [Summoner's Pigaches +2](https://www.bg-wiki.com/ffxi/Summoner%27s_Pigaches_%2B2)
      - [ ] [Summoner's Doublet +2](https://www.bg-wiki.com/ffxi/Summoner%27s_Doublet_%2B2)
      - [ ] [Summoner's Horn +2](https://www.bg-wiki.com/ffxi/Summoner%27s_Horn_%2B2)
    - [ ] [Glyphic Attire Set](https://www.bg-wiki.com/ffxi/Glyphic_Attire_Set)
      - [ ] [Glyphic Horn](https://www.bg-wiki.com/ffxi/Glyphic_Horn)
      - [ ] [Glyphic Doublet](https://www.bg-wiki.com/ffxi/Glyphic_Doublet)
      - [ ] [Glyphic Bracers](https://www.bg-wiki.com/ffxi/Glyphic_Bracers)
      - [ ] [Glyphic Spats](https://www.bg-wiki.com/ffxi/Glyphic_Spats)
      - [ ] [Glyphic Pigaches](https://www.bg-wiki.com/ffxi/Glyphic_Pigaches)
    - [ ] [Glyphic Attire Set +1](https://www.bg-wiki.com/ffxi/Glyphic_Attire_Set_%2B1)
      - [ ] [Glyphic Horn +1](https://www.bg-wiki.com/ffxi/Glyphic_Horn_%2B1)
      - [ ] [Glyphic Doublet +1](https://www.bg-wiki.com/ffxi/Glyphic_Doublet_%2B1)
      - [ ] [Glyphic Bracers +1](https://www.bg-wiki.com/ffxi/Glyphic_Bracers_%2B1)
      - [ ] [Glyphic Spats +1](https://www.bg-wiki.com/ffxi/Glyphic_Spats_%2B1)
      - [ ] [Glyphic Pigaches +1](https://www.bg-wiki.com/ffxi/Glyphic_Pigaches_%2B1)
    - [ ] [Glyphic Attire Set +2](https://www.bg-wiki.com/ffxi/Glyphic_Attire_Set_%2B2)
      - [ ] [Glyphic Horn +2](https://www.bg-wiki.com/ffxi/Glyphic_Horn_%2B2)
      - [ ] [Glyphic Doublet +2](https://www.bg-wiki.com/ffxi/Glyphic_Doublet_%2B2)
      - [ ] [Glyphic Bracers +2](https://www.bg-wiki.com/ffxi/Glyphic_Bracers_%2B2)
      - [ ] [Glyphic Spats +2](https://www.bg-wiki.com/ffxi/Glyphic_Spats_%2B2)
      - [ ] [Glyphic Pigaches +2](https://www.bg-wiki.com/ffxi/Glyphic_Pigaches_%2B2)
    - [ ] [Glyphic Attire Set +3](https://www.bg-wiki.com/ffxi/Glyphic_Attire_Set_%2B3)
      - [ ] [Glyphic Horn +3](https://www.bg-wiki.com/ffxi/Glyphic_Horn_%2B3)
      - [ ] [Glyphic Doublet +3](https://www.bg-wiki.com/ffxi/Glyphic_Doublet_%2B3)
      - [ ] [Glyphic Bracers +3](https://www.bg-wiki.com/ffxi/Glyphic_Bracers_%2B3)
      - [ ] [Glyphic Spats +3](https://www.bg-wiki.com/ffxi/Glyphic_Spats_%2B3)
      - [ ] [Glyphic Pigaches +3](https://www.bg-wiki.com/ffxi/Glyphic_Pigaches_%2B3)
    - [ ] [Summoner's Cape](https://www.bg-wiki.com/ffxi/Summoner%27s_Cape)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Summoner's Collar](https://www.bg-wiki.com/ffxi/Summoner%27s_Collar)
      - [ ] [Summoner's Collar +1](https://www.bg-wiki.com/ffxi/Summoner%27s_Collar_%2B1)
      - [ ] [Summoner's Collar +2](https://www.bg-wiki.com/ffxi/Summoner%27s_Collar_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Summoner's Staff](https://www.bg-wiki.com/ffxi/Summoner%27s_Staff)
      - [ ] [Glyphic Staff](https://www.bg-wiki.com/ffxi/Glyphic_Staff)
      - [ ] [Draumstafir](https://www.bg-wiki.com/ffxi/Draumstafir)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Caller's Attire Set](https://www.bg-wiki.com/ffxi/Caller%27s_Attire_Set)
      - [ ] [Caller's Pigaches](https://www.bg-wiki.com/ffxi/Caller%27s_Pigaches)
      - [ ] [Caller's Spats](https://www.bg-wiki.com/ffxi/Caller%27s_Spats)
      - [ ] [Caller's Horn](https://www.bg-wiki.com/ffxi/Caller%27s_Horn)
      - [ ] [Caller's Bracers](https://www.bg-wiki.com/ffxi/Caller%27s_Bracers)
      - [ ] [Caller's Doublet](https://www.bg-wiki.com/ffxi/Caller%27s_Doublet)
    - [ ] [Caller's Attire Set +1](https://www.bg-wiki.com/ffxi/Caller%27s_Attire_Set_%2B1)
      - [ ] [Caller's Pigaches +1](https://www.bg-wiki.com/ffxi/Caller%27s_Pigaches_%2B1)
      - [ ] [Caller's Spats +1](https://www.bg-wiki.com/ffxi/Caller%27s_Spats_%2B1)
      - [ ] [Caller's Horn +1](https://www.bg-wiki.com/ffxi/Caller%27s_Horn_%2B1)
      - [ ] [Caller's Bracers +1](https://www.bg-wiki.com/ffxi/Caller%27s_Bracers_%2B1)
      - [ ] [Caller's Doublet +1](https://www.bg-wiki.com/ffxi/Caller%27s_Doublet_%2B1)
    - [ ] [Caller's Attire Set +2](https://www.bg-wiki.com/ffxi/Caller%27s_Attire_Set_%2B2)
      - [ ] [Caller's Pigaches +2](https://www.bg-wiki.com/ffxi/Caller%27s_Pigaches_%2B2)
      - [ ] [Caller's Spats +2](https://www.bg-wiki.com/ffxi/Caller%27s_Spats_%2B2)
      - [ ] [Caller's Horn +2](https://www.bg-wiki.com/ffxi/Caller%27s_Horn_%2B2)
      - [ ] [Caller's Bracers +2](https://www.bg-wiki.com/ffxi/Caller%27s_Bracers_%2B2)
      - [ ] [Caller's Doublet +2](https://www.bg-wiki.com/ffxi/Caller%27s_Doublet_%2B2)
    - [ ] [Beckoner's Attire Set](https://www.bg-wiki.com/ffxi/Beckoner%27s_Attire_Set)
      - [ ] [Beckoner's Horn](https://www.bg-wiki.com/ffxi/Beckoner%27s_Horn)
      - [ ] [Beckoner's Doublet](https://www.bg-wiki.com/ffxi/Beckoner%27s_Doublet)
      - [ ] [Beckoner's Bracers](https://www.bg-wiki.com/ffxi/Beckoner%27s_Bracers)
      - [ ] [Beckoner's Spats](https://www.bg-wiki.com/ffxi/Beckoner%27s_Spats)
      - [ ] [Beckoner's Pigaches](https://www.bg-wiki.com/ffxi/Beckoner%27s_Pigaches)
    - [ ] [Beckoner's Attire Set +1](https://www.bg-wiki.com/ffxi/Beckoner%27s_Attire_Set_%2B1)
      - [ ] [Beckoner's Horn +1](https://www.bg-wiki.com/ffxi/Beckoner%27s_Horn_%2B1)
      - [ ] [Beckoner's Doublet +1](https://www.bg-wiki.com/ffxi/Beckoner%27s_Doublet_%2B1)
      - [ ] [Beckoner's Bracers +1](https://www.bg-wiki.com/ffxi/Beckoner%27s_Bracers_%2B1)
      - [ ] [Beckoner's Spats +1](https://www.bg-wiki.com/ffxi/Beckoner%27s_Spats_%2B1)
      - [ ] [Beckoner's Pigaches +1](https://www.bg-wiki.com/ffxi/Beckoner%27s_Pigaches_%2B1)
    - [ ] [Beckoner's Attire Set +2](https://www.bg-wiki.com/ffxi/Beckoner%27s_Attire_Set_%2B2)
      - [ ] [Beckoner's Horn +2](https://www.bg-wiki.com/ffxi/Beckoner%27s_Horn_%2B2)
      - [ ] [Beckoner's Doublet +2](https://www.bg-wiki.com/ffxi/Beckoner%27s_Doublet_%2B2)
      - [ ] [Beckoner's Bracers +2](https://www.bg-wiki.com/ffxi/Beckoner%27s_Bracers_%2B2)
      - [ ] [Beckoner's Spats +2](https://www.bg-wiki.com/ffxi/Beckoner%27s_Spats_%2B2)
      - [ ] [Beckoner's Pigaches +2](https://www.bg-wiki.com/ffxi/Beckoner%27s_Pigaches_%2B2)
    - [ ] [Beckoner's Attire Set +3](https://www.bg-wiki.com/ffxi/Beckoner%27s_Attire_Set_%2B3)
      - [ ] [Beckoner's Horn +3](https://www.bg-wiki.com/ffxi/Beckoner%27s_Horn_%2B3)
      - [ ] [Beckoner's Doublet +3](https://www.bg-wiki.com/ffxi/Beckoner%27s_Doublet_%2B3)
      - [ ] [Beckoner's Bracers +3](https://www.bg-wiki.com/ffxi/Beckoner%27s_Bracers_%2B3)
      - [ ] [Beckoner's Spats +3](https://www.bg-wiki.com/ffxi/Beckoner%27s_Spats_%2B3)
      - [ ] [Beckoner's Pigaches +3](https://www.bg-wiki.com/ffxi/Beckoner%27s_Pigaches_%2B3)
    - [ ] Accessories
      - [ ] [Caller's Sash](https://www.bg-wiki.com/ffxi/Caller%27s_Sash)
      - [ ] [Caller's Pendant](https://www.bg-wiki.com/ffxi/Caller%27s_Pendant)
      - [ ] [Caller's Earring](https://www.bg-wiki.com/ffxi/Caller%27s_Earring)
      - [ ] [Beckoner's Earring](https://www.bg-wiki.com/ffxi/Beckoner%27s_Earring)
      - [ ] [Beckoner's Earring +1](https://www.bg-wiki.com/ffxi/Beckoner%27s_Earring_%2B1)
      - [ ] [Beckoner's Earring +2](https://www.bg-wiki.com/ffxi/Beckoner%27s_Earring_%2B2)
