### ISSUE TITLE
SAM JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4402]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [SAM](https://www.bg-wiki.com/ffxi/Samurai)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Myochin Armor Set](https://www.bg-wiki.com/ffxi/Myochin_Armor_Set)
      - [ ] [Myochin Sune-Ate](https://www.bg-wiki.com/ffxi/Myochin_Sune-Ate)
      - [ ] [Myochin Haidate](https://www.bg-wiki.com/ffxi/Myochin_Haidate)
      - [ ] [Myochin Kote](https://www.bg-wiki.com/ffxi/Myochin_Kote)
      - [ ] [Myochin Domaru](https://www.bg-wiki.com/ffxi/Myochin_Domaru)
      - [ ] [Myochin Kabuto](https://www.bg-wiki.com/ffxi/Myochin_Kabuto)
    - [ ] [Myochin Armor Set +1](https://www.bg-wiki.com/ffxi/Myochin_Armor_Set_%2B1)
      - [ ] [Myochin Sune-Ate +1](https://www.bg-wiki.com/ffxi/Myochin_Sune-Ate_%2B1)
      - [ ] [Myochin Haidate +1](https://www.bg-wiki.com/ffxi/Myochin_Haidate_%2B1)
      - [ ] [Myochin Kote +1](https://www.bg-wiki.com/ffxi/Myochin_Kote_%2B1)
      - [ ] [Myochin Domaru +1](https://www.bg-wiki.com/ffxi/Myochin_Domaru_%2B1)
      - [ ] [Myochin Kabuto +1](https://www.bg-wiki.com/ffxi/Myochin_Kabuto_%2B1)
    - [ ] [Wakido Armor Set](https://www.bg-wiki.com/ffxi/Wakido_Armor_Set)
      - [ ] [Wakido Kabuto](https://www.bg-wiki.com/ffxi/Wakido_Kabuto)
      - [ ] [Wakido Domaru](https://www.bg-wiki.com/ffxi/Wakido_Domaru)
      - [ ] [Wakido Kote](https://www.bg-wiki.com/ffxi/Wakido_Kote)
      - [ ] [Wakido Haidate](https://www.bg-wiki.com/ffxi/Wakido_Haidate)
      - [ ] [Wakido Sune-Ate](https://www.bg-wiki.com/ffxi/Wakido_Sune-Ate)
    - [ ] [Wakido Armor Set +1](https://www.bg-wiki.com/ffxi/Wakido_Armor_Set_%2B1)
      - [ ] [Wakido Kabuto +1](https://www.bg-wiki.com/ffxi/Wakido_Kabuto_%2B1)
      - [ ] [Wakido Domaru +1](https://www.bg-wiki.com/ffxi/Wakido_Domaru_%2B1)
      - [ ] [Wakido Kote +1](https://www.bg-wiki.com/ffxi/Wakido_Kote_%2B1)
      - [ ] [Wakido Haidate +1](https://www.bg-wiki.com/ffxi/Wakido_Haidate_%2B1)
      - [ ] [Wakido Sune-Ate +1](https://www.bg-wiki.com/ffxi/Wakido_Sune-Ate_%2B1)
    - [ ] [Wakido Armor Set +2](https://www.bg-wiki.com/ffxi/Wakido_Armor_Set_%2B2)
      - [ ] [Wakido Kabuto +2](https://www.bg-wiki.com/ffxi/Wakido_Kabuto_%2B2)
      - [ ] [Wakido Domaru +2](https://www.bg-wiki.com/ffxi/Wakido_Domaru_%2B2)
      - [ ] [Wakido Kote +2](https://www.bg-wiki.com/ffxi/Wakido_Kote_%2B2)
      - [ ] [Wakido Haidate +2](https://www.bg-wiki.com/ffxi/Wakido_Haidate_%2B2)
      - [ ] [Wakido Sune-Ate +2](https://www.bg-wiki.com/ffxi/Wakido_Sune-Ate_%2B2)
    - [ ] [Wakido Armor Set +3](https://www.bg-wiki.com/ffxi/Wakido_Armor_Set_%2B3)
      - [ ] [Wakido Kabuto +3](https://www.bg-wiki.com/ffxi/Wakido_Kabuto_%2B3)
      - [ ] [Wakido Domaru +3](https://www.bg-wiki.com/ffxi/Wakido_Domaru_%2B3)
      - [ ] [Wakido Kote +3](https://www.bg-wiki.com/ffxi/Wakido_Kote_%2B3)
      - [ ] [Wakido Haidate +3](https://www.bg-wiki.com/ffxi/Wakido_Haidate_%2B3)
      - [ ] [Wakido Sune-Ate +3](https://www.bg-wiki.com/ffxi/Wakido_Sune-Ate_%2B3)
    - [ ] [Magoroku](https://www.bg-wiki.com/ffxi/Magoroku)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Saotome Armor Set](https://www.bg-wiki.com/ffxi/Saotome_Armor_Set)
      - [ ] [Saotome Sune-Ate](https://www.bg-wiki.com/ffxi/Saotome_Sune-Ate)
      - [ ] [Saotome Haidate](https://www.bg-wiki.com/ffxi/Saotome_Haidate)
      - [ ] [Saotome Kote](https://www.bg-wiki.com/ffxi/Saotome_Kote)
      - [ ] [Saotome Domaru](https://www.bg-wiki.com/ffxi/Saotome_Domaru)
      - [ ] [Saotome Kabuto](https://www.bg-wiki.com/ffxi/Saotome_Kabuto)
    - [ ] [Saotome Armor Set +1](https://www.bg-wiki.com/ffxi/Saotome_Armor_Set_%2B1)
      - [ ] [Saotome Sune-Ate +1](https://www.bg-wiki.com/ffxi/Saotome_Sune-Ate_%2B1)
      - [ ] [Saotome Haidate +1](https://www.bg-wiki.com/ffxi/Saotome_Haidate_%2B1)
      - [ ] [Saotome Kote +1](https://www.bg-wiki.com/ffxi/Saotome_Kote_%2B1)
      - [ ] [Saotome Domaru +1](https://www.bg-wiki.com/ffxi/Saotome_Domaru_%2B1)
      - [ ] [Saotome Kabuto +1](https://www.bg-wiki.com/ffxi/Saotome_Kabuto_%2B1)
    - [ ] [Saotome Armor Set +2](https://www.bg-wiki.com/ffxi/Saotome_Armor_Set_%2B2)
      - [ ] [Saotome Sune-Ate +2](https://www.bg-wiki.com/ffxi/Saotome_Sune-Ate_%2B2)
      - [ ] [Saotome Haidate +2](https://www.bg-wiki.com/ffxi/Saotome_Haidate_%2B2)
      - [ ] [Saotome Kote +2](https://www.bg-wiki.com/ffxi/Saotome_Kote_%2B2)
      - [ ] [Saotome Domaru +2](https://www.bg-wiki.com/ffxi/Saotome_Domaru_%2B2)
      - [ ] [Saotome Kabuto +2](https://www.bg-wiki.com/ffxi/Saotome_Kabuto_%2B2)
    - [ ] [Sakonji Armor Set](https://www.bg-wiki.com/ffxi/Sakonji_Armor_Set)
      - [ ] [Sakonji Kabuto](https://www.bg-wiki.com/ffxi/Sakonji_Kabuto)
      - [ ] [Sakonji Domaru](https://www.bg-wiki.com/ffxi/Sakonji_Domaru)
      - [ ] [Sakonji Kote](https://www.bg-wiki.com/ffxi/Sakonji_Kote)
      - [ ] [Sakonji Haidate](https://www.bg-wiki.com/ffxi/Sakonji_Haidate)
      - [ ] [Sakonji Sune-Ate](https://www.bg-wiki.com/ffxi/Sakonji_Sune-Ate)
    - [ ] [Sakonji Armor Set +1](https://www.bg-wiki.com/ffxi/Sakonji_Armor_Set_%2B1)
      - [ ] [Sakonji Kabuto +1](https://www.bg-wiki.com/ffxi/Sakonji_Kabuto_%2B1)
      - [ ] [Sakonji Domaru +1](https://www.bg-wiki.com/ffxi/Sakonji_Domaru_%2B1)
      - [ ] [Sakonji Kote +1](https://www.bg-wiki.com/ffxi/Sakonji_Kote_%2B1)
      - [ ] [Sakonji Haidate +1](https://www.bg-wiki.com/ffxi/Sakonji_Haidate_%2B1)
      - [ ] [Sakonji Sune-Ate +1](https://www.bg-wiki.com/ffxi/Sakonji_Sune-Ate_%2B1)
    - [ ] [Sakonji Armor Set +2](https://www.bg-wiki.com/ffxi/Sakonji_Armor_Set_%2B2)
      - [ ] [Sakonji Kabuto +2](https://www.bg-wiki.com/ffxi/Sakonji_Kabuto_%2B2)
      - [ ] [Sakonji Domaru +2](https://www.bg-wiki.com/ffxi/Sakonji_Domaru_%2B2)
      - [ ] [Sakonji Kote +2](https://www.bg-wiki.com/ffxi/Sakonji_Kote_%2B2)
      - [ ] [Sakonji Haidate +2](https://www.bg-wiki.com/ffxi/Sakonji_Haidate_%2B2)
      - [ ] [Sakonji Sune-Ate +2](https://www.bg-wiki.com/ffxi/Sakonji_Sune-Ate_%2B2)
    - [ ] [Sakonji Armor Set +3](https://www.bg-wiki.com/ffxi/Sakonji_Armor_Set_%2B3)
      - [ ] [Sakonji Kabuto +3](https://www.bg-wiki.com/ffxi/Sakonji_Kabuto_%2B3)
      - [ ] [Sakonji Domaru +3](https://www.bg-wiki.com/ffxi/Sakonji_Domaru_%2B3)
      - [ ] [Sakonji Kote +3](https://www.bg-wiki.com/ffxi/Sakonji_Kote_%2B3)
      - [ ] [Sakonji Haidate +3](https://www.bg-wiki.com/ffxi/Sakonji_Haidate_%2B3)
      - [ ] [Sakonji Sune-Ate +3](https://www.bg-wiki.com/ffxi/Sakonji_Sune-Ate_%2B3)
    - [ ] [Saotome Koshi-Ate](https://www.bg-wiki.com/ffxi/Saotome_Koshi-Ate)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Samurai's Nodowa](https://www.bg-wiki.com/ffxi/Samurai%27s_Nodowa)
      - [ ] [Samurai's Nodowa +1](https://www.bg-wiki.com/ffxi/Samurai%27s_Nodowa_%2B1)
      - [ ] [Samurai's Nodowa +2](https://www.bg-wiki.com/ffxi/Samurai%27s_Nodowa_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Saotome-no-tachi](https://www.bg-wiki.com/ffxi/Saotome-no-tachi)
      - [ ] [Sakonji-no-tachi](https://www.bg-wiki.com/ffxi/Sakonji-no-tachi)
      - [ ] [Fusenaikyo](https://www.bg-wiki.com/ffxi/Fusenaikyo)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Unkai Armor Set](https://www.bg-wiki.com/ffxi/Unkai_Armor_Set)
      - [ ] [Unkai Sune-Ate](https://www.bg-wiki.com/ffxi/Unkai_Sune-Ate)
      - [ ] [Unkai Haidate](https://www.bg-wiki.com/ffxi/Unkai_Haidate)
      - [ ] [Unkai Kabuto](https://www.bg-wiki.com/ffxi/Unkai_Kabuto)
      - [ ] [Unkai Kote](https://www.bg-wiki.com/ffxi/Unkai_Kote)
      - [ ] [Unkai Domaru](https://www.bg-wiki.com/ffxi/Unkai_Domaru)
    - [ ] [Unkai Armor Set +1](https://www.bg-wiki.com/ffxi/Unkai_Armor_Set_%2B1)
      - [ ] [Unkai Sune-Ate +1](https://www.bg-wiki.com/ffxi/Unkai_Sune-Ate_%2B1)
      - [ ] [Unkai Haidate +1](https://www.bg-wiki.com/ffxi/Unkai_Haidate_%2B1)
      - [ ] [Unkai Kabuto +1](https://www.bg-wiki.com/ffxi/Unkai_Kabuto_%2B1)
      - [ ] [Unkai Kote +1](https://www.bg-wiki.com/ffxi/Unkai_Kote_%2B1)
      - [ ] [Unkai Domaru +1](https://www.bg-wiki.com/ffxi/Unkai_Domaru_%2B1)
    - [ ] [Unkai Armor Set +2](https://www.bg-wiki.com/ffxi/Unkai_Armor_Set_%2B2)
      - [ ] [Unkai Sune-Ate +2](https://www.bg-wiki.com/ffxi/Unkai_Sune-Ate_%2B2)
      - [ ] [Unkai Haidate +2](https://www.bg-wiki.com/ffxi/Unkai_Haidate_%2B2)
      - [ ] [Unkai Kabuto +2](https://www.bg-wiki.com/ffxi/Unkai_Kabuto_%2B2)
      - [ ] [Unkai Kote +2](https://www.bg-wiki.com/ffxi/Unkai_Kote_%2B2)
      - [ ] [Unkai Domaru +2](https://www.bg-wiki.com/ffxi/Unkai_Domaru_%2B2)
    - [ ] [Kasuga Armor Set](https://www.bg-wiki.com/ffxi/Kasuga_Armor_Set)
      - [ ] [Kasuga Kabuto](https://www.bg-wiki.com/ffxi/Kasuga_Kabuto)
      - [ ] [Kasuga Domaru](https://www.bg-wiki.com/ffxi/Kasuga_Domaru)
      - [ ] [Kasuga Kote](https://www.bg-wiki.com/ffxi/Kasuga_Kote)
      - [ ] [Kasuga Haidate](https://www.bg-wiki.com/ffxi/Kasuga_Haidate)
      - [ ] [Kasuga Sune-Ate](https://www.bg-wiki.com/ffxi/Kasuga_Sune-Ate)
    - [ ] [Kasuga Armor Set +1](https://www.bg-wiki.com/ffxi/Kasuga_Armor_Set_%2B1)
      - [ ] [Kasuga Kabuto +1](https://www.bg-wiki.com/ffxi/Kasuga_Kabuto_%2B1)
      - [ ] [Kasuga Domaru +1](https://www.bg-wiki.com/ffxi/Kasuga_Domaru_%2B1)
      - [ ] [Kasuga Kote +1](https://www.bg-wiki.com/ffxi/Kasuga_Kote_%2B1)
      - [ ] [Kasuga Haidate +1](https://www.bg-wiki.com/ffxi/Kasuga_Haidate_%2B1)
      - [ ] [Kasuga Sune-Ate +1](https://www.bg-wiki.com/ffxi/Kasuga_Sune-Ate_%2B1)
    - [ ] [Kasuga Armor Set +2](https://www.bg-wiki.com/ffxi/Kasuga_Armor_Set_%2B2)
      - [ ] [Kasuga Kabuto +2](https://www.bg-wiki.com/ffxi/Kasuga_Kabuto_%2B2)
      - [ ] [Kasuga Domaru +2](https://www.bg-wiki.com/ffxi/Kasuga_Domaru_%2B2)
      - [ ] [Kasuga Kote +2](https://www.bg-wiki.com/ffxi/Kasuga_Kote_%2B2)
      - [ ] [Kasuga Haidate +2](https://www.bg-wiki.com/ffxi/Kasuga_Haidate_%2B2)
      - [ ] [Kasuga Sune-Ate +2](https://www.bg-wiki.com/ffxi/Kasuga_Sune-Ate_%2B2)
    - [ ] [Kasuga Armor Set +3](https://www.bg-wiki.com/ffxi/Kasuga_Armor_Set_%2B3)
      - [ ] [Kasuga Kabuto +3](https://www.bg-wiki.com/ffxi/Kasuga_Kabuto_%2B3)
      - [ ] [Kasuga Domaru +3](https://www.bg-wiki.com/ffxi/Kasuga_Domaru_%2B3)
      - [ ] [Kasuga Kote +3](https://www.bg-wiki.com/ffxi/Kasuga_Kote_%2B3)
      - [ ] [Kasuga Haidate +3](https://www.bg-wiki.com/ffxi/Kasuga_Haidate_%2B3)
      - [ ] [Kasuga Sune-Ate +3](https://www.bg-wiki.com/ffxi/Kasuga_Sune-Ate_%2B3)
    - [ ] Accessories
      - [ ] [Unkai Nodowa](https://www.bg-wiki.com/ffxi/Unkai_Nodowa)
      - [ ] [Unkai Sugemino](https://www.bg-wiki.com/ffxi/Unkai_Sugemino)
      - [ ] [Unkai Mimikazari](https://www.bg-wiki.com/ffxi/Unkai_Mimikazari)
      - [ ] [Kasuga Earring](https://www.bg-wiki.com/ffxi/Kasuga_Earring)
      - [ ] [Kasuga Earring +1](https://www.bg-wiki.com/ffxi/Kasuga_Earring_%2B1)
      - [ ] [Kasuga Earring +2](https://www.bg-wiki.com/ffxi/Kasuga_Earring_%2B2)
