### ISSUE TITLE
NIN JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4403]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [NIN](https://www.bg-wiki.com/ffxi/Ninja)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Ninja Garb Set](https://www.bg-wiki.com/ffxi/Ninja_Garb_Set)
      - [ ] [Ninja Hakama](https://www.bg-wiki.com/ffxi/Ninja_Hakama)
      - [ ] [Ninja Kyahan](https://www.bg-wiki.com/ffxi/Ninja_Kyahan)
      - [ ] [Ninja Tekko](https://www.bg-wiki.com/ffxi/Ninja_Tekko)
      - [ ] [Ninja Chainmail](https://www.bg-wiki.com/ffxi/Ninja_Chainmail)
      - [ ] [Ninja Hatsuburi](https://www.bg-wiki.com/ffxi/Ninja_Hatsuburi)
    - [ ] [Ninja Garb Set +1](https://www.bg-wiki.com/ffxi/Ninja_Garb_Set_%2B1)
      - [ ] [Ninja Hakama +1](https://www.bg-wiki.com/ffxi/Ninja_Hakama_%2B1)
      - [ ] [Ninja Kyahan +1](https://www.bg-wiki.com/ffxi/Ninja_Kyahan_%2B1)
      - [ ] [Ninja Tekko +1](https://www.bg-wiki.com/ffxi/Ninja_Tekko_%2B1)
      - [ ] [Ninja Chainmail +1](https://www.bg-wiki.com/ffxi/Ninja_Chainmail_%2B1)
      - [ ] [Ninja Hatsuburi +1](https://www.bg-wiki.com/ffxi/Ninja_Hatsuburi_%2B1)
    - [ ] [Hachiya Garb Set](https://www.bg-wiki.com/ffxi/Hachiya_Garb_Set)
      - [ ] [Hachiya Hatsuburi](https://www.bg-wiki.com/ffxi/Hachiya_Hatsuburi)
      - [ ] [Hachiya Chainmail](https://www.bg-wiki.com/ffxi/Hachiya_Chainmail)
      - [ ] [Hachiya Tekko](https://www.bg-wiki.com/ffxi/Hachiya_Tekko)
      - [ ] [Hachiya Hakama](https://www.bg-wiki.com/ffxi/Hachiya_Hakama)
      - [ ] [Hachiya Kyahan](https://www.bg-wiki.com/ffxi/Hachiya_Kyahan)
    - [ ] [Hachiya Garb Set +1](https://www.bg-wiki.com/ffxi/Hachiya_Garb_Set_%2B1)
      - [ ] [Hachiya Hatsuburi +1](https://www.bg-wiki.com/ffxi/Hachiya_Hatsuburi_%2B1)
      - [ ] [Hachiya Chainmail +1](https://www.bg-wiki.com/ffxi/Hachiya_Chainmail_%2B1)
      - [ ] [Hachiya Tekko +1](https://www.bg-wiki.com/ffxi/Hachiya_Tekko_%2B1)
      - [ ] [Hachiya Hakama +1](https://www.bg-wiki.com/ffxi/Hachiya_Hakama_%2B1)
      - [ ] [Hachiya Kyahan +1](https://www.bg-wiki.com/ffxi/Hachiya_Kyahan_%2B1)
    - [ ] [Hachiya Garb Set +2](https://www.bg-wiki.com/ffxi/Hachiya_Garb_Set_%2B2)
      - [ ] [Hachiya Hatsuburi +2](https://www.bg-wiki.com/ffxi/Hachiya_Hatsuburi_%2B2)
      - [ ] [Hachiya Chainmail +2](https://www.bg-wiki.com/ffxi/Hachiya_Chainmail_%2B2)
      - [ ] [Hachiya Tekko +2](https://www.bg-wiki.com/ffxi/Hachiya_Tekko_%2B2)
      - [ ] [Hachiya Hakama +2](https://www.bg-wiki.com/ffxi/Hachiya_Hakama_%2B2)
      - [ ] [Hachiya Kyahan +2](https://www.bg-wiki.com/ffxi/Hachiya_Kyahan_%2B2)
    - [ ] [Hachiya Garb Set +3](https://www.bg-wiki.com/ffxi/Hachiya_Garb_Set_%2B3)
      - [ ] [Hachiya Hatsuburi +3](https://www.bg-wiki.com/ffxi/Hachiya_Hatsuburi_%2B3)
      - [ ] [Hachiya Chainmail +3](https://www.bg-wiki.com/ffxi/Hachiya_Chainmail_%2B3)
      - [ ] [Hachiya Tekko +3](https://www.bg-wiki.com/ffxi/Hachiya_Tekko_%2B3)
      - [ ] [Hachiya Hakama +3](https://www.bg-wiki.com/ffxi/Hachiya_Hakama_%2B3)
      - [ ] [Hachiya Kyahan +3](https://www.bg-wiki.com/ffxi/Hachiya_Kyahan_%2B3)
    - [ ] [Anju](https://www.bg-wiki.com/ffxi/Anju)
    - [ ] [Zushio](https://www.bg-wiki.com/ffxi/Zushio)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Koga Garb Set](https://www.bg-wiki.com/ffxi/Koga_Garb_Set)
      - [ ] [Koga Kyahan](https://www.bg-wiki.com/ffxi/Koga_Kyahan)
      - [ ] [Koga Tekko](https://www.bg-wiki.com/ffxi/Koga_Tekko)
      - [ ] [Koga Hakama](https://www.bg-wiki.com/ffxi/Koga_Hakama)
      - [ ] [Koga Chainmail](https://www.bg-wiki.com/ffxi/Koga_Chainmail)
      - [ ] [Koga Hatsuburi](https://www.bg-wiki.com/ffxi/Koga_Hatsuburi)
    - [ ] [Koga Garb Set +1](https://www.bg-wiki.com/ffxi/Koga_Garb_Set_%2B1)
      - [ ] [Koga Kyahan +1](https://www.bg-wiki.com/ffxi/Koga_Kyahan_%2B1)
      - [ ] [Koga Tekko +1](https://www.bg-wiki.com/ffxi/Koga_Tekko_%2B1)
      - [ ] [Koga Hakama +1](https://www.bg-wiki.com/ffxi/Koga_Hakama_%2B1)
      - [ ] [Koga Chainmail +1](https://www.bg-wiki.com/ffxi/Koga_Chainmail_%2B1)
      - [ ] [Koga Hatsuburi +1](https://www.bg-wiki.com/ffxi/Koga_Hatsuburi_%2B1)
    - [ ] [Koga Garb Set +2](https://www.bg-wiki.com/ffxi/Koga_Garb_Set_%2B2)
      - [ ] [Koga Kyahan +2](https://www.bg-wiki.com/ffxi/Koga_Kyahan_%2B2)
      - [ ] [Koga Tekko +2](https://www.bg-wiki.com/ffxi/Koga_Tekko_%2B2)
      - [ ] [Koga Hakama +2](https://www.bg-wiki.com/ffxi/Koga_Hakama_%2B2)
      - [ ] [Koga Chainmail +2](https://www.bg-wiki.com/ffxi/Koga_Chainmail_%2B2)
      - [ ] [Koga Hatsuburi +2](https://www.bg-wiki.com/ffxi/Koga_Hatsuburi_%2B2)
    - [ ] [Mochizuki Garb Set](https://www.bg-wiki.com/ffxi/Mochizuki_Garb_Set)
      - [ ] [Mochizuki Hatsuburi](https://www.bg-wiki.com/ffxi/Mochizuki_Hatsuburi)
      - [ ] [Mochizuki Chainmail](https://www.bg-wiki.com/ffxi/Mochizuki_Chainmail)
      - [ ] [Mochizuki Tekko](https://www.bg-wiki.com/ffxi/Mochizuki_Tekko)
      - [ ] [Mochizuki Hakama](https://www.bg-wiki.com/ffxi/Mochizuki_Hakama)
      - [ ] [Mochizuki Kyahan](https://www.bg-wiki.com/ffxi/Mochizuki_Kyahan)
    - [ ] [Mochizuki Garb Set +1](https://www.bg-wiki.com/ffxi/Mochizuki_Garb_Set_%2B1)
      - [ ] [Mochizuki Hatsuburi +1](https://www.bg-wiki.com/ffxi/Mochizuki_Hatsuburi_%2B1)
      - [ ] [Mochizuki Chainmail +1](https://www.bg-wiki.com/ffxi/Mochizuki_Chainmail_%2B1)
      - [ ] [Mochizuki Tekko +1](https://www.bg-wiki.com/ffxi/Mochizuki_Tekko_%2B1)
      - [ ] [Mochizuki Hakama +1](https://www.bg-wiki.com/ffxi/Mochizuki_Hakama_%2B1)
      - [ ] [Mochizuki Kyahan +1](https://www.bg-wiki.com/ffxi/Mochizuki_Kyahan_%2B1)
    - [ ] [Mochizuki Garb Set +2](https://www.bg-wiki.com/ffxi/Mochizuki_Garb_Set_%2B2)
      - [ ] [Mochizuki Hatsuburi +2](https://www.bg-wiki.com/ffxi/Mochizuki_Hatsuburi_%2B2)
      - [ ] [Mochizuki Chainmail +2](https://www.bg-wiki.com/ffxi/Mochizuki_Chainmail_%2B2)
      - [ ] [Mochizuki Tekko +2](https://www.bg-wiki.com/ffxi/Mochizuki_Tekko_%2B2)
      - [ ] [Mochizuki Hakama +2](https://www.bg-wiki.com/ffxi/Mochizuki_Hakama_%2B2)
      - [ ] [Mochizuki Kyahan +2](https://www.bg-wiki.com/ffxi/Mochizuki_Kyahan_%2B2)
    - [ ] [Mochizuki Garb Set +3](https://www.bg-wiki.com/ffxi/Mochizuki_Garb_Set_%2B3)
      - [ ] [Mochizuki Hatsuburi +3](https://www.bg-wiki.com/ffxi/Mochizuki_Hatsuburi_%2B3)
      - [ ] [Mochizuki Chainmail +3](https://www.bg-wiki.com/ffxi/Mochizuki_Chainmail_%2B3)
      - [ ] [Mochizuki Tekko +3](https://www.bg-wiki.com/ffxi/Mochizuki_Tekko_%2B3)
      - [ ] [Mochizuki Hakama +3](https://www.bg-wiki.com/ffxi/Mochizuki_Hakama_%2B3)
      - [ ] [Mochizuki Kyahan +3](https://www.bg-wiki.com/ffxi/Mochizuki_Kyahan_%2B3)
    - [ ] [Koga Sarashi](https://www.bg-wiki.com/ffxi/Koga_Sarashi)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Ninja Nodowa](https://www.bg-wiki.com/ffxi/Ninja_Nodowa)
      - [ ] [Ninja Nodowa +1](https://www.bg-wiki.com/ffxi/Ninja_Nodowa_%2B1)
      - [ ] [Ninja Nodowa +2](https://www.bg-wiki.com/ffxi/Ninja_Nodowa_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Koga Shinobi-Gatana](https://www.bg-wiki.com/ffxi/Koga_Shinobi-Gatana)
      - [ ] [Mochizuki Shinobi-Gatana](https://www.bg-wiki.com/ffxi/Mochizuki_Shinobi-Gatana)
      - [ ] [Fudo Masamune](https://www.bg-wiki.com/ffxi/Fudo_Masamune)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Iga Garb Set](https://www.bg-wiki.com/ffxi/Iga_Garb_Set)
      - [ ] [Iga Kyahan](https://www.bg-wiki.com/ffxi/Iga_Kyahan)
      - [ ] [Iga Hakama](https://www.bg-wiki.com/ffxi/Iga_Hakama)
      - [ ] [Iga Zukin](https://www.bg-wiki.com/ffxi/Iga_Zukin)
      - [ ] [Iga Tekko](https://www.bg-wiki.com/ffxi/Iga_Tekko)
      - [ ] [Iga Ningi](https://www.bg-wiki.com/ffxi/Iga_Ningi)
    - [ ] [Iga Garb Set +1](https://www.bg-wiki.com/ffxi/Iga_Garb_Set_%2B1)
      - [ ] [Iga Kyahan +1](https://www.bg-wiki.com/ffxi/Iga_Kyahan_%2B1)
      - [ ] [Iga Hakama +1](https://www.bg-wiki.com/ffxi/Iga_Hakama_%2B1)
      - [ ] [Iga Zukin +1](https://www.bg-wiki.com/ffxi/Iga_Zukin_%2B1)
      - [ ] [Iga Tekko +1](https://www.bg-wiki.com/ffxi/Iga_Tekko_%2B1)
      - [ ] [Iga Ningi +1](https://www.bg-wiki.com/ffxi/Iga_Ningi_%2B1)
    - [ ] [Iga Garb Set +2](https://www.bg-wiki.com/ffxi/Iga_Garb_Set_%2B2)
      - [ ] [Iga Kyahan +2](https://www.bg-wiki.com/ffxi/Iga_Kyahan_%2B2)
      - [ ] [Iga Hakama +2](https://www.bg-wiki.com/ffxi/Iga_Hakama_%2B2)
      - [ ] [Iga Zukin +2](https://www.bg-wiki.com/ffxi/Iga_Zukin_%2B2)
      - [ ] [Iga Tekko +2](https://www.bg-wiki.com/ffxi/Iga_Tekko_%2B2)
      - [ ] [Iga Ningi +2](https://www.bg-wiki.com/ffxi/Iga_Ningi_%2B2)
    - [ ] [Hattori Garb Set](https://www.bg-wiki.com/ffxi/Hattori_Garb_Set)
      - [ ] [Hattori Zukin](https://www.bg-wiki.com/ffxi/Hattori_Zukin)
      - [ ] [Hattori Ningi](https://www.bg-wiki.com/ffxi/Hattori_Ningi)
      - [ ] [Hattori Tekko](https://www.bg-wiki.com/ffxi/Hattori_Tekko)
      - [ ] [Hattori Hakama](https://www.bg-wiki.com/ffxi/Hattori_Hakama)
      - [ ] [Hattori Kyahan](https://www.bg-wiki.com/ffxi/Hattori_Kyahan)
    - [ ] [Hattori Garb Set +1](https://www.bg-wiki.com/ffxi/Hattori_Garb_Set_%2B1)
      - [ ] [Hattori Zukin +1](https://www.bg-wiki.com/ffxi/Hattori_Zukin_%2B1)
      - [ ] [Hattori Ningi +1](https://www.bg-wiki.com/ffxi/Hattori_Ningi_%2B1)
      - [ ] [Hattori Tekko +1](https://www.bg-wiki.com/ffxi/Hattori_Tekko_%2B1)
      - [ ] [Hattori Hakama +1](https://www.bg-wiki.com/ffxi/Hattori_Hakama_%2B1)
      - [ ] [Hattori Kyahan +1](https://www.bg-wiki.com/ffxi/Hattori_Kyahan_%2B1)
    - [ ] [Hattori Garb Set +2](https://www.bg-wiki.com/ffxi/Hattori_Garb_Set_%2B2)
      - [ ] [Hattori Zukin +2](https://www.bg-wiki.com/ffxi/Hattori_Zukin_%2B2)
      - [ ] [Hattori Ningi +2](https://www.bg-wiki.com/ffxi/Hattori_Ningi_%2B2)
      - [ ] [Hattori Tekko +2](https://www.bg-wiki.com/ffxi/Hattori_Tekko_%2B2)
      - [ ] [Hattori Hakama +2](https://www.bg-wiki.com/ffxi/Hattori_Hakama_%2B2)
      - [ ] [Hattori Kyahan +2](https://www.bg-wiki.com/ffxi/Hattori_Kyahan_%2B2)
    - [ ] [Hattori Garb Set +3](https://www.bg-wiki.com/ffxi/Hattori_Garb_Set_%2B3)
      - [ ] [Hattori Zukin +3](https://www.bg-wiki.com/ffxi/Hattori_Zukin_%2B3)
      - [ ] [Hattori Ningi +3](https://www.bg-wiki.com/ffxi/Hattori_Ningi_%2B3)
      - [ ] [Hattori Tekko +3](https://www.bg-wiki.com/ffxi/Hattori_Tekko_%2B3)
      - [ ] [Hattori Hakama +3](https://www.bg-wiki.com/ffxi/Hattori_Hakama_%2B3)
      - [ ] [Hattori Kyahan +3](https://www.bg-wiki.com/ffxi/Hattori_Kyahan_%2B3)
    - [ ] Accessories
      - [ ] [Iga Erimaki](https://www.bg-wiki.com/ffxi/Iga_Erimaki)
      - [ ] [Iga Dochugappa](https://www.bg-wiki.com/ffxi/Iga_Dochugappa)
      - [ ] [Iga Mimikazari](https://www.bg-wiki.com/ffxi/Iga_Mimikazari)
      - [ ] [Hattori Earring](https://www.bg-wiki.com/ffxi/Hattori_Earring)
      - [ ] [Hattori Earring +1](https://www.bg-wiki.com/ffxi/Hattori_Earring_%2B1)
      - [ ] [Hattori Earring +2](https://www.bg-wiki.com/ffxi/Hattori_Earring_%2B2)
