### ISSUE TITLE
DRG JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4404]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [DRG](https://www.bg-wiki.com/ffxi/Dragoon)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Drachen Armor Set](https://www.bg-wiki.com/ffxi/Drachen_Armor_Set)
      - [ ] [Drachen Brais](https://www.bg-wiki.com/ffxi/Drachen_Brais)
      - [ ] [Drachen Greaves](https://www.bg-wiki.com/ffxi/Drachen_Greaves)
      - [ ] [Drachen Finger Gauntlets](https://www.bg-wiki.com/ffxi/Drachen_Finger_Gauntlets)
      - [ ] [Drachen Mail](https://www.bg-wiki.com/ffxi/Drachen_Mail)
      - [ ] [Drachen Armet](https://www.bg-wiki.com/ffxi/Drachen_Armet)
    - [ ] [Drachen Armor Set +1](https://www.bg-wiki.com/ffxi/Drachen_Armor_Set_%2B1)
      - [ ] [Drachen Brais +1](https://www.bg-wiki.com/ffxi/Drachen_Brais_%2B1)
      - [ ] [Drachen Greaves +1](https://www.bg-wiki.com/ffxi/Drachen_Greaves_%2B1)
      - [ ] [Drachen Finger Gauntlets +1](https://www.bg-wiki.com/ffxi/Drachen_Finger_Gauntlets_%2B1)
      - [ ] [Drachen Mail +1](https://www.bg-wiki.com/ffxi/Drachen_Mail_%2B1)
      - [ ] [Drachen Armet +1](https://www.bg-wiki.com/ffxi/Drachen_Armet_%2B1)
    - [ ] [Vishap Armor Set](https://www.bg-wiki.com/ffxi/Vishap_Armor_Set)
      - [ ] [Vishap Armet](https://www.bg-wiki.com/ffxi/Vishap_Armet)
      - [ ] [Vishap Mail](https://www.bg-wiki.com/ffxi/Vishap_Mail)
      - [ ] [Vishap Finger Gauntlets](https://www.bg-wiki.com/ffxi/Vishap_Finger_Gauntlets)
      - [ ] [Vishap Brais](https://www.bg-wiki.com/ffxi/Vishap_Brais)
      - [ ] [Vishap Greaves](https://www.bg-wiki.com/ffxi/Vishap_Greaves)
    - [ ] [Vishap Armor Set +1](https://www.bg-wiki.com/ffxi/Vishap_Armor_Set_%2B1)
      - [ ] [Vishap Armet +1](https://www.bg-wiki.com/ffxi/Vishap_Armet_%2B1)
      - [ ] [Vishap Mail +1](https://www.bg-wiki.com/ffxi/Vishap_Mail_%2B1)
      - [ ] [Vishap Finger Gauntlets +1](https://www.bg-wiki.com/ffxi/Vishap_Finger_Gauntlets_%2B1)
      - [ ] [Vishap Brais +1](https://www.bg-wiki.com/ffxi/Vishap_Brais_%2B1)
      - [ ] [Vishap Greaves +1](https://www.bg-wiki.com/ffxi/Vishap_Greaves_%2B1)
    - [ ] [Vishap Armor Set +2](https://www.bg-wiki.com/ffxi/Vishap_Armor_Set_%2B2)
      - [ ] [Vishap Armet +2](https://www.bg-wiki.com/ffxi/Vishap_Armet_%2B2)
      - [ ] [Vishap Mail +2](https://www.bg-wiki.com/ffxi/Vishap_Mail_%2B2)
      - [ ] [Vishap Finger Gauntlets +2](https://www.bg-wiki.com/ffxi/Vishap_Finger_Gauntlets_%2B2)
      - [ ] [Vishap Brais +2](https://www.bg-wiki.com/ffxi/Vishap_Brais_%2B2)
      - [ ] [Vishap Greaves +2](https://www.bg-wiki.com/ffxi/Vishap_Greaves_%2B2)
    - [ ] [Vishap Armor Set +3](https://www.bg-wiki.com/ffxi/Vishap_Armor_Set_%2B3)
      - [ ] [Vishap Armet +3](https://www.bg-wiki.com/ffxi/Vishap_Armet_%2B3)
      - [ ] [Vishap Mail +3](https://www.bg-wiki.com/ffxi/Vishap_Mail_%2B3)
      - [ ] [Vishap Finger Gauntlets +3](https://www.bg-wiki.com/ffxi/Vishap_Finger_Gauntlets_%2B3)
      - [ ] [Vishap Brais +3](https://www.bg-wiki.com/ffxi/Vishap_Brais_%2B3)
      - [ ] [Vishap Greaves +3](https://www.bg-wiki.com/ffxi/Vishap_Greaves_%2B3)
    - [ ] [Peregrine](https://www.bg-wiki.com/ffxi/Peregrine)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Wyrm Armor Set](https://www.bg-wiki.com/ffxi/Wyrm_Armor_Set)
      - [ ] [Wyrm Brais](https://www.bg-wiki.com/ffxi/Wyrm_Brais)
      - [ ] [Wyrm Greaves](https://www.bg-wiki.com/ffxi/Wyrm_Greaves)
      - [ ] [Wyrm Finger Gauntlets](https://www.bg-wiki.com/ffxi/Wyrm_Finger_Gauntlets)
      - [ ] [Wyrm Mail](https://www.bg-wiki.com/ffxi/Wyrm_Mail)
      - [ ] [Wyrm Armet](https://www.bg-wiki.com/ffxi/Wyrm_Armet)
    - [ ] [Wyrm Armor Set +1](https://www.bg-wiki.com/ffxi/Wyrm_Armor_Set_%2B1)
      - [ ] [Wyrm Brais +1](https://www.bg-wiki.com/ffxi/Wyrm_Brais_%2B1)
      - [ ] [Wyrm Greaves +1](https://www.bg-wiki.com/ffxi/Wyrm_Greaves_%2B1)
      - [ ] [Wyrm Finger Gauntlets +1](https://www.bg-wiki.com/ffxi/Wyrm_Finger_Gauntlets_%2B1)
      - [ ] [Wyrm Mail +1](https://www.bg-wiki.com/ffxi/Wyrm_Mail_%2B1)
      - [ ] [Wyrm Armet +1](https://www.bg-wiki.com/ffxi/Wyrm_Armet_%2B1)
    - [ ] [Wyrm Armor Set +2](https://www.bg-wiki.com/ffxi/Wyrm_Armor_Set_%2B2)
      - [ ] [Wyrm Brais +2](https://www.bg-wiki.com/ffxi/Wyrm_Brais_%2B2)
      - [ ] [Wyrm Greaves +2](https://www.bg-wiki.com/ffxi/Wyrm_Greaves_%2B2)
      - [ ] [Wyrm Finger Gauntlets +2](https://www.bg-wiki.com/ffxi/Wyrm_Finger_Gauntlets_%2B2)
      - [ ] [Wyrm Mail +2](https://www.bg-wiki.com/ffxi/Wyrm_Mail_%2B2)
      - [ ] [Wyrm Armet +2](https://www.bg-wiki.com/ffxi/Wyrm_Armet_%2B2)
    - [ ] [Pteroslaver Armor Set](https://www.bg-wiki.com/ffxi/Pteroslaver_Armor_Set)
      - [ ] [Pteroslaver Armet](https://www.bg-wiki.com/ffxi/Pteroslaver_Armet)
      - [ ] [Pteroslaver Mail](https://www.bg-wiki.com/ffxi/Pteroslaver_Mail)
      - [ ] [Pteroslaver Finger Gauntlets](https://www.bg-wiki.com/ffxi/Pteroslaver_Finger_Gauntlets)
      - [ ] [Pteroslaver Brais](https://www.bg-wiki.com/ffxi/Pteroslaver_Brais)
      - [ ] [Pteroslaver Greaves](https://www.bg-wiki.com/ffxi/Pteroslaver_Greaves)
    - [ ] [Pteroslaver Armor Set +1](https://www.bg-wiki.com/ffxi/Pteroslaver_Armor_Set_%2B1)
      - [ ] [Pteroslaver Armet +1](https://www.bg-wiki.com/ffxi/Pteroslaver_Armet_%2B1)
      - [ ] [Pteroslaver Mail +1](https://www.bg-wiki.com/ffxi/Pteroslaver_Mail_%2B1)
      - [ ] [Pteroslaver Finger Gauntlets +1](https://www.bg-wiki.com/ffxi/Pteroslaver_Finger_Gauntlets_%2B1)
      - [ ] [Pteroslaver Brais +1](https://www.bg-wiki.com/ffxi/Pteroslaver_Brais_%2B1)
      - [ ] [Pteroslaver Greaves +1](https://www.bg-wiki.com/ffxi/Pteroslaver_Greaves_%2B1)
    - [ ] [Pteroslaver Armor Set +2](https://www.bg-wiki.com/ffxi/Pteroslaver_Armor_Set_%2B2)
      - [ ] [Pteroslaver Armet +2](https://www.bg-wiki.com/ffxi/Pteroslaver_Armet_%2B2)
      - [ ] [Pteroslaver Mail +2](https://www.bg-wiki.com/ffxi/Pteroslaver_Mail_%2B2)
      - [ ] [Pteroslaver Finger Gauntlets +2](https://www.bg-wiki.com/ffxi/Pteroslaver_Finger_Gauntlets_%2B2)
      - [ ] [Pteroslaver Brais +2](https://www.bg-wiki.com/ffxi/Pteroslaver_Brais_%2B2)
      - [ ] [Pteroslaver Greaves +2](https://www.bg-wiki.com/ffxi/Pteroslaver_Greaves_%2B2)
    - [ ] [Pteroslaver Armor Set +3](https://www.bg-wiki.com/ffxi/Pteroslaver_Armor_Set_%2B3)
      - [ ] [Pteroslaver Armet +3](https://www.bg-wiki.com/ffxi/Pteroslaver_Armet_%2B3)
      - [ ] [Pteroslaver Mail +3](https://www.bg-wiki.com/ffxi/Pteroslaver_Mail_%2B3)
      - [ ] [Pteroslaver Finger Gauntlets +3](https://www.bg-wiki.com/ffxi/Pteroslaver_Finger_Gauntlets_%2B3)
      - [ ] [Pteroslaver Brais +3](https://www.bg-wiki.com/ffxi/Pteroslaver_Brais_%2B3)
      - [ ] [Pteroslaver Greaves +3](https://www.bg-wiki.com/ffxi/Pteroslaver_Greaves_%2B3)
    - [ ] [Wyrm Belt](https://www.bg-wiki.com/ffxi/Wyrm_Belt)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Dragoon's Collar](https://www.bg-wiki.com/ffxi/Dragoon%27s_Collar)
      - [ ] [Dragoon's Collar +1](https://www.bg-wiki.com/ffxi/Dragoon%27s_Collar_%2B1)
      - [ ] [Dragoon's Collar +2](https://www.bg-wiki.com/ffxi/Dragoon%27s_Collar_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Wyrm Lance](https://www.bg-wiki.com/ffxi/Wyrm_Lance)
      - [ ] [Pteroslaver Lance](https://www.bg-wiki.com/ffxi/Pteroslaver_Lance)
      - [ ] [Aram](https://www.bg-wiki.com/ffxi/Aram)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Lancer's Armor Set](https://www.bg-wiki.com/ffxi/Lancer%27s_Armor_Set)
      - [ ] [Lancer's Schynbalds](https://www.bg-wiki.com/ffxi/Lancer%27s_Schynbalds)
      - [ ] [Lancer's Cuissots](https://www.bg-wiki.com/ffxi/Lancer%27s_Cuissots)
      - [ ] [Lancer's Mezail](https://www.bg-wiki.com/ffxi/Lancer%27s_Mezail)
      - [ ] [Lancer's Vambraces](https://www.bg-wiki.com/ffxi/Lancer%27s_Vambraces)
      - [ ] [Lancer's Plackart](https://www.bg-wiki.com/ffxi/Lancer%27s_Plackart)
    - [ ] [Lancer's Armor Set +1](https://www.bg-wiki.com/ffxi/Lancer%27s_Armor_Set_%2B1)
      - [ ] [Lancer's Schynbalds +1](https://www.bg-wiki.com/ffxi/Lancer%27s_Schynbalds_%2B1)
      - [ ] [Lancer's Cuissots +1](https://www.bg-wiki.com/ffxi/Lancer%27s_Cuissots_%2B1)
      - [ ] [Lancer's Mezail +1](https://www.bg-wiki.com/ffxi/Lancer%27s_Mezail_%2B1)
      - [ ] [Lancer's Vambraces +1](https://www.bg-wiki.com/ffxi/Lancer%27s_Vambraces_%2B1)
      - [ ] [Lancer's Plackart +1](https://www.bg-wiki.com/ffxi/Lancer%27s_Plackart_%2B1)
    - [ ] [Lancer's Armor Set +2](https://www.bg-wiki.com/ffxi/Lancer%27s_Armor_Set_%2B2)
      - [ ] [Lancer's Schynbalds +2](https://www.bg-wiki.com/ffxi/Lancer%27s_Schynbalds_%2B2)
      - [ ] [Lancer's Cuissots +2](https://www.bg-wiki.com/ffxi/Lancer%27s_Cuissots_%2B2)
      - [ ] [Lancer's Mezail +2](https://www.bg-wiki.com/ffxi/Lancer%27s_Mezail_%2B2)
      - [ ] [Lancer's Vambraces +2](https://www.bg-wiki.com/ffxi/Lancer%27s_Vambraces_%2B2)
      - [ ] [Lancer's Plackart +2](https://www.bg-wiki.com/ffxi/Lancer%27s_Plackart_%2B2)
    - [ ] [Peltast's Armor Set](https://www.bg-wiki.com/ffxi/Peltast%27s_Armor_Set)
      - [ ] [Peltast's Mezail](https://www.bg-wiki.com/ffxi/Peltast%27s_Mezail)
      - [ ] [Peltast's Plackart](https://www.bg-wiki.com/ffxi/Peltast%27s_Plackart)
      - [ ] [Peltast's Vambraces](https://www.bg-wiki.com/ffxi/Peltast%27s_Vambraces)
      - [ ] [Peltast's Cuissots](https://www.bg-wiki.com/ffxi/Peltast%27s_Cuissots)
      - [ ] [Peltast's Schynbalds](https://www.bg-wiki.com/ffxi/Peltast%27s_Schynbalds)
    - [ ] [Peltast's Armor Set +1](https://www.bg-wiki.com/ffxi/Peltast%27s_Armor_Set_%2B1)
      - [ ] [Peltast's Mezail +1](https://www.bg-wiki.com/ffxi/Peltast%27s_Mezail_%2B1)
      - [ ] [Peltast's Plackart +1](https://www.bg-wiki.com/ffxi/Peltast%27s_Plackart_%2B1)
      - [ ] [Peltast's Vambraces +1](https://www.bg-wiki.com/ffxi/Peltast%27s_Vambraces_%2B1)
      - [ ] [Peltast's Cuissots +1](https://www.bg-wiki.com/ffxi/Peltast%27s_Cuissots_%2B1)
      - [ ] [Peltast's Schynbalds +1](https://www.bg-wiki.com/ffxi/Peltast%27s_Schynbalds_%2B1)
    - [ ] [Peltast's Armor Set +2](https://www.bg-wiki.com/ffxi/Peltast%27s_Armor_Set_%2B2)
      - [ ] [Peltast's Mezail +2](https://www.bg-wiki.com/ffxi/Peltast%27s_Mezail_%2B2)
      - [ ] [Peltast's Plackart +2](https://www.bg-wiki.com/ffxi/Peltast%27s_Plackart_%2B2)
      - [ ] [Peltast's Vambraces +2](https://www.bg-wiki.com/ffxi/Peltast%27s_Vambraces_%2B2)
      - [ ] [Peltast's Cuissots +2](https://www.bg-wiki.com/ffxi/Peltast%27s_Cuissots_%2B2)
      - [ ] [Peltast's Schynbalds +2](https://www.bg-wiki.com/ffxi/Peltast%27s_Schynbalds_%2B2)
    - [ ] [Peltast's Armor Set +3](https://www.bg-wiki.com/ffxi/Peltast%27s_Armor_Set_%2B3)
      - [ ] [Peltast's Mezail +3](https://www.bg-wiki.com/ffxi/Peltast%27s_Mezail_%2B3)
      - [ ] [Peltast's Plackart +3](https://www.bg-wiki.com/ffxi/Peltast%27s_Plackart_%2B3)
      - [ ] [Peltast's Vambraces +3](https://www.bg-wiki.com/ffxi/Peltast%27s_Vambraces_%2B3)
      - [ ] [Peltast's Cuissots +3](https://www.bg-wiki.com/ffxi/Peltast%27s_Cuissots_%2B3)
      - [ ] [Peltast's Schynbalds +3](https://www.bg-wiki.com/ffxi/Peltast%27s_Schynbalds_%2B3)
    - [ ] Accessories
      - [ ] [Lancer's Torque](https://www.bg-wiki.com/ffxi/Lancer%27s_Torque)
      - [ ] [Lancer's Pelerine](https://www.bg-wiki.com/ffxi/Lancer%27s_Pelerine)
      - [ ] [Lancer's Earring](https://www.bg-wiki.com/ffxi/Lancer%27s_Earring)
      - [ ] [Peltast's Earring](https://www.bg-wiki.com/ffxi/Peltast%27s_Earring)
      - [ ] [Peltast's Earring +1](https://www.bg-wiki.com/ffxi/Peltast%27s_Earring_%2B1)
      - [ ] [Peltast's Earring +2](https://www.bg-wiki.com/ffxi/Peltast%27s_Earring_%2B2)
