### ISSUE TITLE
BLUE JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4405]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [BLU](https://www.bg-wiki.com/ffxi/Blue_Mage)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Magus Attire Set](https://www.bg-wiki.com/ffxi/Magus_Attire_Set)
      - [ ] [Magus Charuqs](https://www.bg-wiki.com/ffxi/Magus_Charuqs)
      - [ ] [Magus Shalwar](https://www.bg-wiki.com/ffxi/Magus_Shalwar)
      - [ ] [Magus Bazubands](https://www.bg-wiki.com/ffxi/Magus_Bazubands)
      - [ ] [Magus Jubbah](https://www.bg-wiki.com/ffxi/Magus_Jubbah)
      - [ ] [Magus Keffiyeh](https://www.bg-wiki.com/ffxi/Magus_Keffiyeh)
    - [ ] [Magus Attire Set +1](https://www.bg-wiki.com/ffxi/Magus_Attire_Set_%2B1)
      - [ ] [Magus Charuqs +1](https://www.bg-wiki.com/ffxi/Magus_Charuqs_%2B1)
      - [ ] [Magus Shalwar +1](https://www.bg-wiki.com/ffxi/Magus_Shalwar_%2B1)
      - [ ] [Magus Bazubands +1](https://www.bg-wiki.com/ffxi/Magus_Bazubands_%2B1)
      - [ ] [Magus Jubbah +1](https://www.bg-wiki.com/ffxi/Magus_Jubbah_%2B1)
      - [ ] [Magus Keffiyeh +1](https://www.bg-wiki.com/ffxi/Magus_Keffiyeh_%2B1)
    - [ ] [Assimilator's Attire Set](https://www.bg-wiki.com/ffxi/Assimilator%27s_Attire_Set)
      - [ ] [Assimilator's Keffiyeh](https://www.bg-wiki.com/ffxi/Assimilator%27s_Keffiyeh)
      - [ ] [Assimilator's Jubbah](https://www.bg-wiki.com/ffxi/Assimilator%27s_Jubbah)
      - [ ] [Assimilator's Bazubands](https://www.bg-wiki.com/ffxi/Assimilator%27s_Bazubands)
      - [ ] [Assimilator's Shalwar](https://www.bg-wiki.com/ffxi/Assimilator%27s_Shalwar)
      - [ ] [Assimilator's Charuqs](https://www.bg-wiki.com/ffxi/Assimilator%27s_Charuqs)
    - [ ] [Assimilator's Attire Set +1](https://www.bg-wiki.com/ffxi/Assimilator%27s_Attire_Set_%2B1)
      - [ ] [Assimilator's Keffiyeh +1](https://www.bg-wiki.com/ffxi/Assimilator%27s_Keffiyeh_%2B1)
      - [ ] [Assimilator's Jubbah +1](https://www.bg-wiki.com/ffxi/Assimilator%27s_Jubbah_%2B1)
      - [ ] [Assimilator's Bazubands +1](https://www.bg-wiki.com/ffxi/Assimilator%27s_Bazubands_%2B1)
      - [ ] [Assimilator's Shalwar +1](https://www.bg-wiki.com/ffxi/Assimilator%27s_Shalwar_%2B1)
      - [ ] [Assimilator's Charuqs +1](https://www.bg-wiki.com/ffxi/Assimilator%27s_Charuqs_%2B1)
    - [ ] [Assimilator's Attire Set +2](https://www.bg-wiki.com/ffxi/Assimilator%27s_Attire_Set_%2B2)
      - [ ] [Assimilator's Keffiyeh +2](https://www.bg-wiki.com/ffxi/Assimilator%27s_Keffiyeh_%2B2)
      - [ ] [Assimilator's Jubbah +2](https://www.bg-wiki.com/ffxi/Assimilator%27s_Jubbah_%2B2)
      - [ ] [Assimilator's Bazubands +2](https://www.bg-wiki.com/ffxi/Assimilator%27s_Bazubands_%2B2)
      - [ ] [Assimilator's Shalwar +2](https://www.bg-wiki.com/ffxi/Assimilator%27s_Shalwar_%2B2)
      - [ ] [Assimilator's Charuqs +2](https://www.bg-wiki.com/ffxi/Assimilator%27s_Charuqs_%2B2)
    - [ ] [Assimilator's Attire Set +3](https://www.bg-wiki.com/ffxi/Assimilator%27s_Attire_Set_%2B3)
      - [ ] [Assimilator's Keffiyeh +3](https://www.bg-wiki.com/ffxi/Assimilator%27s_Keffiyeh_%2B3)
      - [ ] [Assimilator's Jubbah +3](https://www.bg-wiki.com/ffxi/Assimilator%27s_Jubbah_%2B3)
      - [ ] [Assimilator's Bazubands +3](https://www.bg-wiki.com/ffxi/Assimilator%27s_Bazubands_%2B3)
      - [ ] [Assimilator's Shalwar +3](https://www.bg-wiki.com/ffxi/Assimilator%27s_Shalwar_%2B3)
      - [ ] [Assimilator's Charuqs +3](https://www.bg-wiki.com/ffxi/Assimilator%27s_Charuqs_%2B3)
    - [ ] [Immortal's Scimitar](https://www.bg-wiki.com/ffxi/Immortal%27s_Scimitar)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Mirage Attire Set](https://www.bg-wiki.com/ffxi/Mirage_Attire_Set)
      - [ ] [Mirage Charuqs](https://www.bg-wiki.com/ffxi/Mirage_Charuqs)
      - [ ] [Mirage Shalwar](https://www.bg-wiki.com/ffxi/Mirage_Shalwar)
      - [ ] [Mirage Bazubands](https://www.bg-wiki.com/ffxi/Mirage_Bazubands)
      - [ ] [Mirage Jubbah](https://www.bg-wiki.com/ffxi/Mirage_Jubbah)
      - [ ] [Mirage Keffiyeh](https://www.bg-wiki.com/ffxi/Mirage_Keffiyeh)
    - [ ] [Mirage Attire Set +1](https://www.bg-wiki.com/ffxi/Mirage_Attire_Set_%2B1)
      - [ ] [Mirage Charuqs +1](https://www.bg-wiki.com/ffxi/Mirage_Charuqs_%2B1)
      - [ ] [Mirage Shalwar +1](https://www.bg-wiki.com/ffxi/Mirage_Shalwar_%2B1)
      - [ ] [Mirage Bazubands +1](https://www.bg-wiki.com/ffxi/Mirage_Bazubands_%2B1)
      - [ ] [Mirage Jubbah +1](https://www.bg-wiki.com/ffxi/Mirage_Jubbah_%2B1)
      - [ ] [Mirage Keffiyeh +1](https://www.bg-wiki.com/ffxi/Mirage_Keffiyeh_%2B1)
    - [ ] [Mirage Attire Set +2](https://www.bg-wiki.com/ffxi/Mirage_Attire_Set_%2B2)
      - [ ] [Mirage Charuqs +2](https://www.bg-wiki.com/ffxi/Mirage_Charuqs_%2B2)
      - [ ] [Mirage Shalwar +2](https://www.bg-wiki.com/ffxi/Mirage_Shalwar_%2B2)
      - [ ] [Mirage Bazubands +2](https://www.bg-wiki.com/ffxi/Mirage_Bazubands_%2B2)
      - [ ] [Mirage Jubbah +2](https://www.bg-wiki.com/ffxi/Mirage_Jubbah_%2B2)
      - [ ] [Mirage Keffiyeh +2](https://www.bg-wiki.com/ffxi/Mirage_Keffiyeh_%2B2)
    - [ ] [Luhlaza Attire Set](https://www.bg-wiki.com/ffxi/Luhlaza_Attire_Set)
      - [ ] [Luhlaza Keffiyeh](https://www.bg-wiki.com/ffxi/Luhlaza_Keffiyeh)
      - [ ] [Luhlaza Jubbah](https://www.bg-wiki.com/ffxi/Luhlaza_Jubbah)
      - [ ] [Luhlaza Bazubands](https://www.bg-wiki.com/ffxi/Luhlaza_Bazubands)
      - [ ] [Luhlaza Shalwar](https://www.bg-wiki.com/ffxi/Luhlaza_Shalwar)
      - [ ] [Luhlaza Charuqs](https://www.bg-wiki.com/ffxi/Luhlaza_Charuqs)
    - [ ] [Luhlaza Attire Set +1](https://www.bg-wiki.com/ffxi/Luhlaza_Attire_Set_%2B1)
      - [ ] [Luhlaza Keffiyeh +1](https://www.bg-wiki.com/ffxi/Luhlaza_Keffiyeh_%2B1)
      - [ ] [Luhlaza Jubbah +1](https://www.bg-wiki.com/ffxi/Luhlaza_Jubbah_%2B1)
      - [ ] [Luhlaza Bazubands +1](https://www.bg-wiki.com/ffxi/Luhlaza_Bazubands_%2B1)
      - [ ] [Luhlaza Shalwar +1](https://www.bg-wiki.com/ffxi/Luhlaza_Shalwar_%2B1)
      - [ ] [Luhlaza Charuqs +1](https://www.bg-wiki.com/ffxi/Luhlaza_Charuqs_%2B1)
    - [ ] [Luhlaza Attire Set +2](https://www.bg-wiki.com/ffxi/Luhlaza_Attire_Set_%2B2)
      - [ ] [Luhlaza Keffiyeh +2](https://www.bg-wiki.com/ffxi/Luhlaza_Keffiyeh_%2B2)
      - [ ] [Luhlaza Jubbah +2](https://www.bg-wiki.com/ffxi/Luhlaza_Jubbah_%2B2)
      - [ ] [Luhlaza Bazubands +2](https://www.bg-wiki.com/ffxi/Luhlaza_Bazubands_%2B2)
      - [ ] [Luhlaza Shalwar +2](https://www.bg-wiki.com/ffxi/Luhlaza_Shalwar_%2B2)
      - [ ] [Luhlaza Charuqs +2](https://www.bg-wiki.com/ffxi/Luhlaza_Charuqs_%2B2)
    - [ ] [Luhlaza Attire Set +3](https://www.bg-wiki.com/ffxi/Luhlaza_Attire_Set_%2B3)
      - [ ] [Luhlaza Keffiyeh +3](https://www.bg-wiki.com/ffxi/Luhlaza_Keffiyeh_%2B3)
      - [ ] [Luhlaza Jubbah +3](https://www.bg-wiki.com/ffxi/Luhlaza_Jubbah_%2B3)
      - [ ] [Luhlaza Bazubands +3](https://www.bg-wiki.com/ffxi/Luhlaza_Bazubands_%2B3)
      - [ ] [Luhlaza Shalwar +3](https://www.bg-wiki.com/ffxi/Luhlaza_Shalwar_%2B3)
      - [ ] [Luhlaza Charuqs +3](https://www.bg-wiki.com/ffxi/Luhlaza_Charuqs_%2B3)
    - [ ] [Mirage Mantle](https://www.bg-wiki.com/ffxi/Mirage_Mantle)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Mirage Stole](https://www.bg-wiki.com/ffxi/Mirage_Stole)
      - [ ] [Mirage Stole +1](https://www.bg-wiki.com/ffxi/Mirage_Stole_%2B1)
      - [ ] [Mirage Stole +2](https://www.bg-wiki.com/ffxi/Mirage_Stole_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Mirage Sword](https://www.bg-wiki.com/ffxi/Mirage_Sword)
      - [ ] [Luhlaza Sword](https://www.bg-wiki.com/ffxi/Luhlaza_Sword)
      - [ ] [Zomorrodnegar](https://www.bg-wiki.com/ffxi/Zomorrodnegar)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Mavi Attire Set](https://www.bg-wiki.com/ffxi/Mavi_Attire_Set)
      - [ ] [Mavi Basmak](https://www.bg-wiki.com/ffxi/Mavi_Basmak)
      - [ ] [Mavi Tayt](https://www.bg-wiki.com/ffxi/Mavi_Tayt)
      - [ ] [Mavi Kavuk](https://www.bg-wiki.com/ffxi/Mavi_Kavuk)
      - [ ] [Mavi Bazubands](https://www.bg-wiki.com/ffxi/Mavi_Bazubands)
      - [ ] [Mavi Mintan](https://www.bg-wiki.com/ffxi/Mavi_Mintan)
    - [ ] [Mavi Attire Set +1](https://www.bg-wiki.com/ffxi/Mavi_Attire_Set_%2B1)
      - [ ] [Mavi Basmak +1](https://www.bg-wiki.com/ffxi/Mavi_Basmak_%2B1)
      - [ ] [Mavi Tayt +1](https://www.bg-wiki.com/ffxi/Mavi_Tayt_%2B1)
      - [ ] [Mavi Kavuk +1](https://www.bg-wiki.com/ffxi/Mavi_Kavuk_%2B1)
      - [ ] [Mavi Bazubands +1](https://www.bg-wiki.com/ffxi/Mavi_Bazubands_%2B1)
      - [ ] [Mavi Mintan +1](https://www.bg-wiki.com/ffxi/Mavi_Mintan_%2B1)
    - [ ] [Mavi Attire Set +2](https://www.bg-wiki.com/ffxi/Mavi_Attire_Set_%2B2)
      - [ ] [Mavi Basmak +2](https://www.bg-wiki.com/ffxi/Mavi_Basmak_%2B2)
      - [ ] [Mavi Tayt +2](https://www.bg-wiki.com/ffxi/Mavi_Tayt_%2B2)
      - [ ] [Mavi Kavuk +2](https://www.bg-wiki.com/ffxi/Mavi_Kavuk_%2B2)
      - [ ] [Mavi Bazubands +2](https://www.bg-wiki.com/ffxi/Mavi_Bazubands_%2B2)
      - [ ] [Mavi Mintan +2](https://www.bg-wiki.com/ffxi/Mavi_Mintan_%2B2)
    - [ ] [Hashishin Attire Set](https://www.bg-wiki.com/ffxi/Hashishin_Attire_Set)
      - [ ] [Hashishin Kavuk](https://www.bg-wiki.com/ffxi/Hashishin_Kavuk)
      - [ ] [Hashishin Mintan](https://www.bg-wiki.com/ffxi/Hashishin_Mintan)
      - [ ] [Hashishin Bazubands](https://www.bg-wiki.com/ffxi/Hashishin_Bazubands)
      - [ ] [Hashishin Tayt](https://www.bg-wiki.com/ffxi/Hashishin_Tayt)
      - [ ] [Hashishin Basmak](https://www.bg-wiki.com/ffxi/Hashishin_Basmak)
    - [ ] [Hashishin Attire Set +1](https://www.bg-wiki.com/ffxi/Hashishin_Attire_Set_%2B1)
      - [ ] [Hashishin Kavuk +1](https://www.bg-wiki.com/ffxi/Hashishin_Kavuk_%2B1)
      - [ ] [Hashishin Mintan +1](https://www.bg-wiki.com/ffxi/Hashishin_Mintan_%2B1)
      - [ ] [Hashishin Bazubands +1](https://www.bg-wiki.com/ffxi/Hashishin_Bazubands_%2B1)
      - [ ] [Hashishin Tayt +1](https://www.bg-wiki.com/ffxi/Hashishin_Tayt_%2B1)
      - [ ] [Hashishin Basmak +1](https://www.bg-wiki.com/ffxi/Hashishin_Basmak_%2B1)
    - [ ] [Hashishin Attire Set +2](https://www.bg-wiki.com/ffxi/Hashishin_Attire_Set_%2B2)
      - [ ] [Hashishin Kavuk +2](https://www.bg-wiki.com/ffxi/Hashishin_Kavuk_%2B2)
      - [ ] [Hashishin Mintan +2](https://www.bg-wiki.com/ffxi/Hashishin_Mintan_%2B2)
      - [ ] [Hashishin Bazubands +2](https://www.bg-wiki.com/ffxi/Hashishin_Bazubands_%2B2)
      - [ ] [Hashishin Tayt +2](https://www.bg-wiki.com/ffxi/Hashishin_Tayt_%2B2)
      - [ ] [Hashishin Basmak +2](https://www.bg-wiki.com/ffxi/Hashishin_Basmak_%2B2)
    - [ ] [Hashishin Attire Set +3](https://www.bg-wiki.com/ffxi/Hashishin_Attire_Set_%2B3)
      - [ ] [Hashishin Kavuk +3](https://www.bg-wiki.com/ffxi/Hashishin_Kavuk_%2B3)
      - [ ] [Hashishin Mintan +3](https://www.bg-wiki.com/ffxi/Hashishin_Mintan_%2B3)
      - [ ] [Hashishin Bazubands +3](https://www.bg-wiki.com/ffxi/Hashishin_Bazubands_%2B3)
      - [ ] [Hashishin Tayt +3](https://www.bg-wiki.com/ffxi/Hashishin_Tayt_%2B3)
      - [ ] [Hashishin Basmak +3](https://www.bg-wiki.com/ffxi/Hashishin_Basmak_%2B3)
    - [ ] Accessories
      - [ ] [Mavi Scarf](https://www.bg-wiki.com/ffxi/Mavi_Scarf)
      - [ ] [Mavi Tathlum](https://www.bg-wiki.com/ffxi/Mavi_Tathlum)
      - [ ] [Mavi Earring](https://www.bg-wiki.com/ffxi/Mavi_Earring)
      - [ ] [Hashishin Earring](https://www.bg-wiki.com/ffxi/Hashishin_Earring)
      - [ ] [Hashishin Earring +1](https://www.bg-wiki.com/ffxi/Hashishin_Earring_%2B1)
      - [ ] [Hashishin Earring +2](https://www.bg-wiki.com/ffxi/Hashishin_Earring_%2B2)
