### ISSUE TITLE
COR JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4406]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [COR](https://www.bg-wiki.com/ffxi/Corsair)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Corsair's Attire Set](https://www.bg-wiki.com/ffxi/Corsair%27s_Attire_Set)
      - [ ] [Corsair's Bottes](https://www.bg-wiki.com/ffxi/Corsair%27s_Bottes)
      - [ ] [Corsair's Culottes](https://www.bg-wiki.com/ffxi/Corsair%27s_Culottes)
      - [ ] [Corsair's Gants](https://www.bg-wiki.com/ffxi/Corsair%27s_Gants)
      - [ ] [Corsair's Frac](https://www.bg-wiki.com/ffxi/Corsair%27s_Frac)
      - [ ] [Corsair's Tricorne](https://www.bg-wiki.com/ffxi/Corsair%27s_Tricorne)
    - [ ] [Corsair's Attire Set +1](https://www.bg-wiki.com/ffxi/Corsair%27s_Attire_Set_%2B1)
      - [ ] [Corsair's Bottes +1](https://www.bg-wiki.com/ffxi/Corsair%27s_Bottes_%2B1)
      - [ ] [Corsair's Culottes +1](https://www.bg-wiki.com/ffxi/Corsair%27s_Culottes_%2B1)
      - [ ] [Corsair's Gants +1](https://www.bg-wiki.com/ffxi/Corsair%27s_Gants_%2B1)
      - [ ] [Corsair's Frac +1](https://www.bg-wiki.com/ffxi/Corsair%27s_Frac_%2B1)
      - [ ] [Corsair's Tricorne +1](https://www.bg-wiki.com/ffxi/Corsair%27s_Tricorne_%2B1)
    - [ ] [Laksamana's Attire Set](https://www.bg-wiki.com/ffxi/Laksamana%27s_Attire_Set)
      - [ ] [Laksamana's Tricorne](https://www.bg-wiki.com/ffxi/Laksamana%27s_Tricorne)
      - [ ] [Laksamana's Frac](https://www.bg-wiki.com/ffxi/Laksamana%27s_Frac)
      - [ ] [Laksamana's Gants](https://www.bg-wiki.com/ffxi/Laksamana%27s_Gants)
      - [ ] [Laksamana's Trews](https://www.bg-wiki.com/ffxi/Laksamana%27s_Trews)
      - [ ] [Laksamana's Bottes](https://www.bg-wiki.com/ffxi/Laksamana%27s_Bottes)
    - [ ] [Laksamana's Attire Set +1](https://www.bg-wiki.com/ffxi/Laksamana%27s_Attire_Set_%2B1)
      - [ ] [Laksamana's Tricorne +1](https://www.bg-wiki.com/ffxi/Laksamana%27s_Tricorne_%2B1)
      - [ ] [Laksamana's Frac +1](https://www.bg-wiki.com/ffxi/Laksamana%27s_Frac_%2B1)
      - [ ] [Laksamana's Gants +1](https://www.bg-wiki.com/ffxi/Laksamana%27s_Gants_%2B1)
      - [ ] [Laksamana's Trews +1](https://www.bg-wiki.com/ffxi/Laksamana%27s_Trews_%2B1)
      - [ ] [Laksamana's Bottes +1](https://www.bg-wiki.com/ffxi/Laksamana%27s_Bottes_%2B1)
    - [ ] [Laksamana's Attire Set +2](https://www.bg-wiki.com/ffxi/Laksamana%27s_Attire_Set_%2B2)
      - [ ] [Laksamana's Tricorne +2](https://www.bg-wiki.com/ffxi/Laksamana%27s_Tricorne_%2B2)
      - [ ] [Laksamana's Frac +2](https://www.bg-wiki.com/ffxi/Laksamana%27s_Frac_%2B2)
      - [ ] [Laksamana's Gants +2](https://www.bg-wiki.com/ffxi/Laksamana%27s_Gants_%2B2)
      - [ ] [Laksamana's Trews +2](https://www.bg-wiki.com/ffxi/Laksamana%27s_Trews_%2B2)
      - [ ] [Laksamana's Bottes +2](https://www.bg-wiki.com/ffxi/Laksamana%27s_Bottes_%2B2)
    - [ ] [Laksamana's Attire Set +3](https://www.bg-wiki.com/ffxi/Laksamana%27s_Attire_Set_%2B3)
      - [ ] [Laksamana's Tricorne +3](https://www.bg-wiki.com/ffxi/Laksamana%27s_Tricorne_%2B3)
      - [ ] [Laksamana's Frac +3](https://www.bg-wiki.com/ffxi/Laksamana%27s_Frac_%2B3)
      - [ ] [Laksamana's Gants +3](https://www.bg-wiki.com/ffxi/Laksamana%27s_Gants_%2B3)
      - [ ] [Laksamana's Trews +3](https://www.bg-wiki.com/ffxi/Laksamana%27s_Trews_%2B3)
      - [ ] [Laksamana's Bottes +3](https://www.bg-wiki.com/ffxi/Laksamana%27s_Bottes_%2B3)
    - [ ] [Trump Gun](https://www.bg-wiki.com/ffxi/Trump_Gun)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Commodore Attire Set](https://www.bg-wiki.com/ffxi/Commodore_Attire_Set)
      - [ ] [Commodore Bottes](https://www.bg-wiki.com/ffxi/Commodore_Bottes)
      - [ ] [Commodore Trews](https://www.bg-wiki.com/ffxi/Commodore_Trews)
      - [ ] [Commodore Gants](https://www.bg-wiki.com/ffxi/Commodore_Gants)
      - [ ] [Commodore Frac](https://www.bg-wiki.com/ffxi/Commodore_Frac)
      - [ ] [Commodore Tricorne](https://www.bg-wiki.com/ffxi/Commodore_Tricorne)
    - [ ] [Commodore Attire Set +1](https://www.bg-wiki.com/ffxi/Commodore_Attire_Set_%2B1)
      - [ ] [Commodore Bottes +1](https://www.bg-wiki.com/ffxi/Commodore_Bottes_%2B1)
      - [ ] [Commodore Trews +1](https://www.bg-wiki.com/ffxi/Commodore_Trews_%2B1)
      - [ ] [Commodore Gants +1](https://www.bg-wiki.com/ffxi/Commodore_Gants_%2B1)
      - [ ] [Commodore Frac +1](https://www.bg-wiki.com/ffxi/Commodore_Frac_%2B1)
      - [ ] [Commodore Tricorne +1](https://www.bg-wiki.com/ffxi/Commodore_Tricorne_%2B1)
    - [ ] [Commodore Attire Set +2](https://www.bg-wiki.com/ffxi/Commodore_Attire_Set_%2B2)
      - [ ] [Commodore Bottes +2](https://www.bg-wiki.com/ffxi/Commodore_Bottes_%2B2)
      - [ ] [Commodore Trews +2](https://www.bg-wiki.com/ffxi/Commodore_Trews_%2B2)
      - [ ] [Commodore Gants +2](https://www.bg-wiki.com/ffxi/Commodore_Gants_%2B2)
      - [ ] [Commodore Frac +2](https://www.bg-wiki.com/ffxi/Commodore_Frac_%2B2)
      - [ ] [Commodore Tricorne +2](https://www.bg-wiki.com/ffxi/Commodore_Tricorne_%2B2)
    - [ ] [Lanun Attire Set](https://www.bg-wiki.com/ffxi/Lanun_Attire_Set)
      - [ ] [Lanun Tricorne](https://www.bg-wiki.com/ffxi/Lanun_Tricorne)
      - [ ] [Lanun Frac](https://www.bg-wiki.com/ffxi/Lanun_Frac)
      - [ ] [Lanun Gants](https://www.bg-wiki.com/ffxi/Lanun_Gants)
      - [ ] [Lanun Trews](https://www.bg-wiki.com/ffxi/Lanun_Trews)
      - [ ] [Lanun Bottes](https://www.bg-wiki.com/ffxi/Lanun_Bottes)
    - [ ] [Lanun Attire Set +1](https://www.bg-wiki.com/ffxi/Lanun_Attire_Set_%2B1)
      - [ ] [Lanun Tricorne +1](https://www.bg-wiki.com/ffxi/Lanun_Tricorne_%2B1)
      - [ ] [Lanun Frac +1](https://www.bg-wiki.com/ffxi/Lanun_Frac_%2B1)
      - [ ] [Lanun Gants +1](https://www.bg-wiki.com/ffxi/Lanun_Gants_%2B1)
      - [ ] [Lanun Trews +1](https://www.bg-wiki.com/ffxi/Lanun_Trews_%2B1)
      - [ ] [Lanun Bottes +1](https://www.bg-wiki.com/ffxi/Lanun_Bottes_%2B1)
    - [ ] [Lanun Attire Set +2](https://www.bg-wiki.com/ffxi/Lanun_Attire_Set_%2B2)
      - [ ] [Lanun Tricorne +2](https://www.bg-wiki.com/ffxi/Lanun_Tricorne_%2B2)
      - [ ] [Lanun Frac +2](https://www.bg-wiki.com/ffxi/Lanun_Frac_%2B2)
      - [ ] [Lanun Gants +2](https://www.bg-wiki.com/ffxi/Lanun_Gants_%2B2)
      - [ ] [Lanun Trews +2](https://www.bg-wiki.com/ffxi/Lanun_Trews_%2B2)
      - [ ] [Lanun Bottes +2](https://www.bg-wiki.com/ffxi/Lanun_Bottes_%2B2)
    - [ ] [Lanun Attire Set +3](https://www.bg-wiki.com/ffxi/Lanun_Attire_Set_%2B3)
      - [ ] [Lanun Tricorne +3](https://www.bg-wiki.com/ffxi/Lanun_Tricorne_%2B3)
      - [ ] [Lanun Frac +3](https://www.bg-wiki.com/ffxi/Lanun_Frac_%2B3)
      - [ ] [Lanun Gants +3](https://www.bg-wiki.com/ffxi/Lanun_Gants_%2B3)
      - [ ] [Lanun Trews +3](https://www.bg-wiki.com/ffxi/Lanun_Trews_%2B3)
      - [ ] [Lanun Bottes +3](https://www.bg-wiki.com/ffxi/Lanun_Bottes_%2B3)
    - [ ] [Commodore Belt](https://www.bg-wiki.com/ffxi/Commodore_Belt)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Commodore Charm](https://www.bg-wiki.com/ffxi/Commodore_Charm)
      - [ ] [Commodore Charm +1](https://www.bg-wiki.com/ffxi/Commodore_Charm_%2B1)
      - [ ] [Commodore Charm +2](https://www.bg-wiki.com/ffxi/Commodore_Charm_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Commodore's Knife](https://www.bg-wiki.com/ffxi/Commodore%27s_Knife)
      - [ ] [Lanun Knife](https://www.bg-wiki.com/ffxi/Lanun_Knife)
      - [ ] [Rostam](https://www.bg-wiki.com/ffxi/Rostam)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Navarch's Attire Set](https://www.bg-wiki.com/ffxi/Navarch%27s_Attire_Set)
      - [ ] [Navarch's Bottes](https://www.bg-wiki.com/ffxi/Navarch%27s_Bottes)
      - [ ] [Navarch's Culottes](https://www.bg-wiki.com/ffxi/Navarch%27s_Culottes)
      - [ ] [Navarch's Tricorne](https://www.bg-wiki.com/ffxi/Navarch%27s_Tricorne)
      - [ ] [Navarch's Gants](https://www.bg-wiki.com/ffxi/Navarch%27s_Gants)
      - [ ] [Navarch's Frac](https://www.bg-wiki.com/ffxi/Navarch%27s_Frac)
    - [ ] [Navarch's Attire Set +1](https://www.bg-wiki.com/ffxi/Navarch%27s_Attire_Set_%2B1)
      - [ ] [Navarch's Bottes +1](https://www.bg-wiki.com/ffxi/Navarch%27s_Bottes_%2B1)
      - [ ] [Navarch's Culottes +1](https://www.bg-wiki.com/ffxi/Navarch%27s_Culottes_%2B1)
      - [ ] [Navarch's Tricorne +1](https://www.bg-wiki.com/ffxi/Navarch%27s_Tricorne_%2B1)
      - [ ] [Navarch's Gants +1](https://www.bg-wiki.com/ffxi/Navarch%27s_Gants_%2B1)
      - [ ] [Navarch's Frac +1](https://www.bg-wiki.com/ffxi/Navarch%27s_Frac_%2B1)
    - [ ] [Navarch's Attire Set +2](https://www.bg-wiki.com/ffxi/Navarch%27s_Attire_Set_%2B2)
      - [ ] [Navarch's Bottes +2](https://www.bg-wiki.com/ffxi/Navarch%27s_Bottes_%2B2)
      - [ ] [Navarch's Culottes +2](https://www.bg-wiki.com/ffxi/Navarch%27s_Culottes_%2B2)
      - [ ] [Navarch's Tricorne +2](https://www.bg-wiki.com/ffxi/Navarch%27s_Tricorne_%2B2)
      - [ ] [Navarch's Gants +2](https://www.bg-wiki.com/ffxi/Navarch%27s_Gants_%2B2)
      - [ ] [Navarch's Frac +2](https://www.bg-wiki.com/ffxi/Navarch%27s_Frac_%2B2)
    - [ ] [Chasseur's Attire Set](https://www.bg-wiki.com/ffxi/Chasseur%27s_Attire_Set)
      - [ ] [Chasseur's Tricorne](https://www.bg-wiki.com/ffxi/Chasseur%27s_Tricorne)
      - [ ] [Chasseur's Frac](https://www.bg-wiki.com/ffxi/Chasseur%27s_Frac)
      - [ ] [Chasseur's Gants](https://www.bg-wiki.com/ffxi/Chasseur%27s_Gants)
      - [ ] [Chasseur's Culottes](https://www.bg-wiki.com/ffxi/Chasseur%27s_Culottes)
      - [ ] [Chasseur's Bottes](https://www.bg-wiki.com/ffxi/Chasseur%27s_Bottes)
    - [ ] [Chasseur's Attire Set +1](https://www.bg-wiki.com/ffxi/Chasseur%27s_Attire_Set_%2B1)
      - [ ] [Chasseur's Tricorne +1](https://www.bg-wiki.com/ffxi/Chasseur%27s_Tricorne_%2B1)
      - [ ] [Chasseur's Frac +1](https://www.bg-wiki.com/ffxi/Chasseur%27s_Frac_%2B1)
      - [ ] [Chasseur's Gants +1](https://www.bg-wiki.com/ffxi/Chasseur%27s_Gants_%2B1)
      - [ ] [Chasseur's Culottes +1](https://www.bg-wiki.com/ffxi/Chasseur%27s_Culottes_%2B1)
      - [ ] [Chasseur's Bottes +1](https://www.bg-wiki.com/ffxi/Chasseur%27s_Bottes_%2B1)
    - [ ] [Chasseur's Attire Set +2](https://www.bg-wiki.com/ffxi/Chasseur%27s_Attire_Set_%2B2)
      - [ ] [Chasseur's Tricorne +2](https://www.bg-wiki.com/ffxi/Chasseur%27s_Tricorne_%2B2)
      - [ ] [Chasseur's Frac +2](https://www.bg-wiki.com/ffxi/Chasseur%27s_Frac_%2B2)
      - [ ] [Chasseur's Gants +2](https://www.bg-wiki.com/ffxi/Chasseur%27s_Gants_%2B2)
      - [ ] [Chasseur's Culottes +2](https://www.bg-wiki.com/ffxi/Chasseur%27s_Culottes_%2B2)
      - [ ] [Chasseur's Bottes +2](https://www.bg-wiki.com/ffxi/Chasseur%27s_Bottes_%2B2)
    - [ ] [Chasseur's Attire Set +3](https://www.bg-wiki.com/ffxi/Chasseur%27s_Attire_Set_%2B3)
      - [ ] [Chasseur's Tricorne +3](https://www.bg-wiki.com/ffxi/Chasseur%27s_Tricorne_%2B3)
      - [ ] [Chasseur's Frac +3](https://www.bg-wiki.com/ffxi/Chasseur%27s_Frac_%2B3)
      - [ ] [Chasseur's Gants +3](https://www.bg-wiki.com/ffxi/Chasseur%27s_Gants_%2B3)
      - [ ] [Chasseur's Culottes +3](https://www.bg-wiki.com/ffxi/Chasseur%27s_Culottes_%2B3)
      - [ ] [Chasseur's Bottes +3](https://www.bg-wiki.com/ffxi/Chasseur%27s_Bottes_%2B3)
    - [ ] Accessories
      - [ ] [Navarch's Choker](https://www.bg-wiki.com/ffxi/Navarch%27s_Choker)
      - [ ] [Navarch's Mantle](https://www.bg-wiki.com/ffxi/Navarch%27s_Mantle)
      - [ ] [Navarch's Earring](https://www.bg-wiki.com/ffxi/Navarch%27s_Earring)
      - [ ] [Chasseur's Earring](https://www.bg-wiki.com/ffxi/Chasseur%27s_Earring)
      - [ ] [Chasseur's Earring +1](https://www.bg-wiki.com/ffxi/Chasseur%27s_Earring_%2B1)
      - [ ] [Chasseur's Earring +2](https://www.bg-wiki.com/ffxi/Chasseur%27s_Earring_%2B2)
