### ISSUE TITLE
PUP JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4407]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [PUP](https://www.bg-wiki.com/ffxi/Puppetmaster)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Puppetry Attire Set](https://www.bg-wiki.com/ffxi/Puppetry_Attire_Set)
      - [ ] [Puppetry Churidars](https://www.bg-wiki.com/ffxi/Puppetry_Churidars)
      - [ ] [Puppetry Babouches](https://www.bg-wiki.com/ffxi/Puppetry_Babouches)
      - [ ] [Puppetry Dastanas](https://www.bg-wiki.com/ffxi/Puppetry_Dastanas)
      - [ ] [Puppetry Tobe](https://www.bg-wiki.com/ffxi/Puppetry_Tobe)
      - [ ] [Puppetry Taj](https://www.bg-wiki.com/ffxi/Puppetry_Taj)
    - [ ] [Puppetry Attire Set +1](https://www.bg-wiki.com/ffxi/Puppetry_Attire_Set_%2B1)
      - [ ] [Puppetry Churidars +1](https://www.bg-wiki.com/ffxi/Puppetry_Churidars_%2B1)
      - [ ] [Puppetry Babouches +1](https://www.bg-wiki.com/ffxi/Puppetry_Babouches_%2B1)
      - [ ] [Puppetry Dastanas +1](https://www.bg-wiki.com/ffxi/Puppetry_Dastanas_%2B1)
      - [ ] [Puppetry Tobe +1](https://www.bg-wiki.com/ffxi/Puppetry_Tobe_%2B1)
      - [ ] [Puppetry Taj +1](https://www.bg-wiki.com/ffxi/Puppetry_Taj_%2B1)
    - [ ] [Foire Attire Set](https://www.bg-wiki.com/ffxi/Foire_Attire_Set)
      - [ ] [Foire Taj](https://www.bg-wiki.com/ffxi/Foire_Taj)
      - [ ] [Foire Tobe](https://www.bg-wiki.com/ffxi/Foire_Tobe)
      - [ ] [Foire Dastanas](https://www.bg-wiki.com/ffxi/Foire_Dastanas)
      - [ ] [Foire Churidars](https://www.bg-wiki.com/ffxi/Foire_Churidars)
      - [ ] [Foire Babouches](https://www.bg-wiki.com/ffxi/Foire_Babouches)
    - [ ] [Foire Attire Set +1](https://www.bg-wiki.com/ffxi/Foire_Attire_Set_%2B1)
      - [ ] [Foire Taj +1](https://www.bg-wiki.com/ffxi/Foire_Taj_%2B1)
      - [ ] [Foire Tobe +1](https://www.bg-wiki.com/ffxi/Foire_Tobe_%2B1)
      - [ ] [Foire Dastanas +1](https://www.bg-wiki.com/ffxi/Foire_Dastanas_%2B1)
      - [ ] [Foire Churidars +1](https://www.bg-wiki.com/ffxi/Foire_Churidars_%2B1)
      - [ ] [Foire Babouches +1](https://www.bg-wiki.com/ffxi/Foire_Babouches_%2B1)
    - [ ] [Foire Attire Set +2](https://www.bg-wiki.com/ffxi/Foire_Attire_Set_%2B2)
      - [ ] [Foire Taj +2](https://www.bg-wiki.com/ffxi/Foire_Taj_%2B2)
      - [ ] [Foire Tobe +2](https://www.bg-wiki.com/ffxi/Foire_Tobe_%2B2)
      - [ ] [Foire Dastanas +2](https://www.bg-wiki.com/ffxi/Foire_Dastanas_%2B2)
      - [ ] [Foire Churidars +2](https://www.bg-wiki.com/ffxi/Foire_Churidars_%2B2)
      - [ ] [Foire Babouches +2](https://www.bg-wiki.com/ffxi/Foire_Babouches_%2B2)
    - [ ] [Foire Attire Set +3](https://www.bg-wiki.com/ffxi/Foire_Attire_Set_%2B3)
      - [ ] [Foire Taj +3](https://www.bg-wiki.com/ffxi/Foire_Taj_%2B3)
      - [ ] [Foire Tobe +3](https://www.bg-wiki.com/ffxi/Foire_Tobe_%2B3)
      - [ ] [Foire Dastanas +3](https://www.bg-wiki.com/ffxi/Foire_Dastanas_%2B3)
      - [ ] [Foire Churidars +3](https://www.bg-wiki.com/ffxi/Foire_Churidars_%2B3)
      - [ ] [Foire Babouches +3](https://www.bg-wiki.com/ffxi/Foire_Babouches_%2B3)
    - [ ] [Turbo Animator](https://www.bg-wiki.com/ffxi/Turbo_Animator)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Pantin Attire Set](https://www.bg-wiki.com/ffxi/Pantin_Attire_Set)
      - [ ] [Pantin Churidars](https://www.bg-wiki.com/ffxi/Pantin_Churidars)
      - [ ] [Pantin Babouches](https://www.bg-wiki.com/ffxi/Pantin_Babouches)
      - [ ] [Pantin Dastanas](https://www.bg-wiki.com/ffxi/Pantin_Dastanas)
      - [ ] [Pantin Tobe](https://www.bg-wiki.com/ffxi/Pantin_Tobe)
      - [ ] [Pantin Taj](https://www.bg-wiki.com/ffxi/Pantin_Taj)
    - [ ] [Pantin Attire Set +1](https://www.bg-wiki.com/ffxi/Pantin_Attire_Set_%2B1)
      - [ ] [Pantin Churidars +1](https://www.bg-wiki.com/ffxi/Pantin_Churidars_%2B1)
      - [ ] [Pantin Babouches +1](https://www.bg-wiki.com/ffxi/Pantin_Babouches_%2B1)
      - [ ] [Pantin Dastanas +1](https://www.bg-wiki.com/ffxi/Pantin_Dastanas_%2B1)
      - [ ] [Pantin Tobe +1](https://www.bg-wiki.com/ffxi/Pantin_Tobe_%2B1)
      - [ ] [Pantin Taj +1](https://www.bg-wiki.com/ffxi/Pantin_Taj_%2B1)
    - [ ] [Pantin Attire Set +2](https://www.bg-wiki.com/ffxi/Pantin_Attire_Set_%2B2)
      - [ ] [Pantin Churidars +2](https://www.bg-wiki.com/ffxi/Pantin_Churidars_%2B2)
      - [ ] [Pantin Babouches +2](https://www.bg-wiki.com/ffxi/Pantin_Babouches_%2B2)
      - [ ] [Pantin Dastanas +2](https://www.bg-wiki.com/ffxi/Pantin_Dastanas_%2B2)
      - [ ] [Pantin Tobe +2](https://www.bg-wiki.com/ffxi/Pantin_Tobe_%2B2)
      - [ ] [Pantin Taj +2](https://www.bg-wiki.com/ffxi/Pantin_Taj_%2B2)
    - [ ] [Pitre Attire Set](https://www.bg-wiki.com/ffxi/Pitre_Attire_Set)
      - [ ] [Pitre Taj](https://www.bg-wiki.com/ffxi/Pitre_Taj)
      - [ ] [Pitre Tobe](https://www.bg-wiki.com/ffxi/Pitre_Tobe)
      - [ ] [Pitre Dastanas](https://www.bg-wiki.com/ffxi/Pitre_Dastanas)
      - [ ] [Pitre Churidars](https://www.bg-wiki.com/ffxi/Pitre_Churidars)
      - [ ] [Pitre Babouches](https://www.bg-wiki.com/ffxi/Pitre_Babouches)
    - [ ] [Pitre Attire Set +1](https://www.bg-wiki.com/ffxi/Pitre_Attire_Set_%2B1)
      - [ ] [Pitre Taj +1](https://www.bg-wiki.com/ffxi/Pitre_Taj_%2B1)
      - [ ] [Pitre Tobe +1](https://www.bg-wiki.com/ffxi/Pitre_Tobe_%2B1)
      - [ ] [Pitre Dastanas +1](https://www.bg-wiki.com/ffxi/Pitre_Dastanas_%2B1)
      - [ ] [Pitre Churidars +1](https://www.bg-wiki.com/ffxi/Pitre_Churidars_%2B1)
      - [ ] [Pitre Babouches +1](https://www.bg-wiki.com/ffxi/Pitre_Babouches_%2B1)
    - [ ] [Pitre Attire Set +2](https://www.bg-wiki.com/ffxi/Pitre_Attire_Set_%2B2)
      - [ ] [Pitre Taj +2](https://www.bg-wiki.com/ffxi/Pitre_Taj_%2B2)
      - [ ] [Pitre Tobe +2](https://www.bg-wiki.com/ffxi/Pitre_Tobe_%2B2)
      - [ ] [Pitre Dastanas +2](https://www.bg-wiki.com/ffxi/Pitre_Dastanas_%2B2)
      - [ ] [Pitre Churidars +2](https://www.bg-wiki.com/ffxi/Pitre_Churidars_%2B2)
      - [ ] [Pitre Babouches +2](https://www.bg-wiki.com/ffxi/Pitre_Babouches_%2B2)
    - [ ] [Pitre Attire Set +3](https://www.bg-wiki.com/ffxi/Pitre_Attire_Set_%2B3)
      - [ ] [Pitre Taj +3](https://www.bg-wiki.com/ffxi/Pitre_Taj_%2B3)
      - [ ] [Pitre Tobe +3](https://www.bg-wiki.com/ffxi/Pitre_Tobe_%2B3)
      - [ ] [Pitre Dastanas +3](https://www.bg-wiki.com/ffxi/Pitre_Dastanas_%2B3)
      - [ ] [Pitre Churidars +3](https://www.bg-wiki.com/ffxi/Pitre_Churidars_%2B3)
      - [ ] [Pitre Babouches +3](https://www.bg-wiki.com/ffxi/Pitre_Babouches_%2B3)
    - [ ] [Pantin Cape](https://www.bg-wiki.com/ffxi/Pantin_Cape)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Puppetmaster's Collar](https://www.bg-wiki.com/ffxi/Puppetmaster%27s_Collar)
      - [ ] [Puppetmaster's Collar +1](https://www.bg-wiki.com/ffxi/Puppetmaster%27s_Collar_%2B1)
      - [ ] [Puppetmaster's Collar +2](https://www.bg-wiki.com/ffxi/Puppetmaster%27s_Collar_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Pantin Fists](https://www.bg-wiki.com/ffxi/Pantin_Fists)
      - [ ] [Pitre Fists](https://www.bg-wiki.com/ffxi/Pitre_Fists)
      - [ ] [Xiucoatl](https://www.bg-wiki.com/ffxi/Xiucoatl)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Cirque Attire Set](https://www.bg-wiki.com/ffxi/Cirque_Attire_Set)
      - [ ] [Cirque Scarpe](https://www.bg-wiki.com/ffxi/Cirque_Scarpe)
      - [ ] [Cirque Pantaloni](https://www.bg-wiki.com/ffxi/Cirque_Pantaloni)
      - [ ] [Cirque Cappello](https://www.bg-wiki.com/ffxi/Cirque_Cappello)
      - [ ] [Cirque Guanti](https://www.bg-wiki.com/ffxi/Cirque_Guanti)
      - [ ] [Cirque Farsetto](https://www.bg-wiki.com/ffxi/Cirque_Farsetto)
    - [ ] [Cirque Attire Set +1](https://www.bg-wiki.com/ffxi/Cirque_Attire_Set_%2B1)
      - [ ] [Cirque Scarpe +1](https://www.bg-wiki.com/ffxi/Cirque_Scarpe_%2B1)
      - [ ] [Cirque Pantaloni +1](https://www.bg-wiki.com/ffxi/Cirque_Pantaloni_%2B1)
      - [ ] [Cirque Cappello +1](https://www.bg-wiki.com/ffxi/Cirque_Cappello_%2B1)
      - [ ] [Cirque Guanti +1](https://www.bg-wiki.com/ffxi/Cirque_Guanti_%2B1)
      - [ ] [Cirque Farsetto +1](https://www.bg-wiki.com/ffxi/Cirque_Farsetto_%2B1)
    - [ ] [Cirque Attire Set +2](https://www.bg-wiki.com/ffxi/Cirque_Attire_Set_%2B2)
      - [ ] [Cirque Scarpe +2](https://www.bg-wiki.com/ffxi/Cirque_Scarpe_%2B2)
      - [ ] [Cirque Pantaloni +2](https://www.bg-wiki.com/ffxi/Cirque_Pantaloni_%2B2)
      - [ ] [Cirque Cappello +2](https://www.bg-wiki.com/ffxi/Cirque_Cappello_%2B2)
      - [ ] [Cirque Guanti +2](https://www.bg-wiki.com/ffxi/Cirque_Guanti_%2B2)
      - [ ] [Cirque Farsetto +2](https://www.bg-wiki.com/ffxi/Cirque_Farsetto_%2B2)
    - [ ] [Karagoz Attire Set](https://www.bg-wiki.com/ffxi/Karagoz_Attire_Set)
      - [ ] [Karagoz Cappello](https://www.bg-wiki.com/ffxi/Karagoz_Cappello)
      - [ ] [Karagoz Farsetto](https://www.bg-wiki.com/ffxi/Karagoz_Farsetto)
      - [ ] [Karagoz Guanti](https://www.bg-wiki.com/ffxi/Karagoz_Guanti)
      - [ ] [Karagoz Pantaloni](https://www.bg-wiki.com/ffxi/Karagoz_Pantaloni)
      - [ ] [Karagoz Scarpe](https://www.bg-wiki.com/ffxi/Karagoz_Scarpe)
    - [ ] [Karagoz Attire Set +1](https://www.bg-wiki.com/ffxi/Karagoz_Attire_Set_%2B1)
      - [ ] [Karagoz Cappello +1](https://www.bg-wiki.com/ffxi/Karagoz_Cappello_%2B1)
      - [ ] [Karagoz Farsetto +1](https://www.bg-wiki.com/ffxi/Karagoz_Farsetto_%2B1)
      - [ ] [Karagoz Guanti +1](https://www.bg-wiki.com/ffxi/Karagoz_Guanti_%2B1)
      - [ ] [Karagoz Pantaloni +1](https://www.bg-wiki.com/ffxi/Karagoz_Pantaloni_%2B1)
      - [ ] [Karagoz Scarpe +1](https://www.bg-wiki.com/ffxi/Karagoz_Scarpe_%2B1)
    - [ ] [Karagoz Attire Set +2](https://www.bg-wiki.com/ffxi/Karagoz_Attire_Set_%2B2)
      - [ ] [Karagoz Cappello +2](https://www.bg-wiki.com/ffxi/Karagoz_Cappello_%2B2)
      - [ ] [Karagoz Farsetto +2](https://www.bg-wiki.com/ffxi/Karagoz_Farsetto_%2B2)
      - [ ] [Karagoz Guanti +2](https://www.bg-wiki.com/ffxi/Karagoz_Guanti_%2B2)
      - [ ] [Karagoz Pantaloni +2](https://www.bg-wiki.com/ffxi/Karagoz_Pantaloni_%2B2)
      - [ ] [Karagoz Scarpe +2](https://www.bg-wiki.com/ffxi/Karagoz_Scarpe_%2B2)
    - [ ] [Karagoz Attire Set +3](https://www.bg-wiki.com/ffxi/Karagoz_Attire_Set_%2B3)
      - [ ] [Karagoz Cappello +3](https://www.bg-wiki.com/ffxi/Karagoz_Cappello_%2B3)
      - [ ] [Karagoz Farsetto +3](https://www.bg-wiki.com/ffxi/Karagoz_Farsetto_%2B3)
      - [ ] [Karagoz Guanti +3](https://www.bg-wiki.com/ffxi/Karagoz_Guanti_%2B3)
      - [ ] [Karagoz Pantaloni +3](https://www.bg-wiki.com/ffxi/Karagoz_Pantaloni_%2B3)
      - [ ] [Karagoz Scarpe +3](https://www.bg-wiki.com/ffxi/Karagoz_Scarpe_%2B3)
    - [ ] Accessories
      - [ ] [Cirque Necklace](https://www.bg-wiki.com/ffxi/Cirque_Necklace)
      - [ ] [Cirque Sash](https://www.bg-wiki.com/ffxi/Cirque_Sash)
      - [ ] [Cirque Earring](https://www.bg-wiki.com/ffxi/Cirque_Earring)
      - [ ] [Karagoz Earring](https://www.bg-wiki.com/ffxi/Karagoz_Earring)
      - [ ] [Karagoz Earring +1](https://www.bg-wiki.com/ffxi/Karagoz_Earring_%2B1)
      - [ ] [Karagoz Earring +2](https://www.bg-wiki.com/ffxi/Karagoz_Earring_%2B2)
