### ISSUE TITLE
DNC JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4408]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [DNC](https://www.bg-wiki.com/ffxi/Dancer)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Dancer's Attire Set](https://www.bg-wiki.com/ffxi/Dancer%27s_Attire_Set)
      - [ ] [Dancer's Bangles](https://www.bg-wiki.com/ffxi/Dancer%27s_Bangles)
      - [ ] [Dancer's Tiara](https://www.bg-wiki.com/ffxi/Dancer%27s_Tiara)
      - [ ] [Dancer's Toe Shoes](https://www.bg-wiki.com/ffxi/Dancer%27s_Toe_Shoes)
      - [ ] [Dancer's Tights](https://www.bg-wiki.com/ffxi/Dancer%27s_Tights)
      - [ ] [Dancer's Casaque](https://www.bg-wiki.com/ffxi/Dancer%27s_Casaque)
    - [ ] [Dancer's Attire Set +1](https://www.bg-wiki.com/ffxi/Dancer%27s_Attire_Set_%2B1)
      - [ ] [Dancer's Bangles +1](https://www.bg-wiki.com/ffxi/Dancer%27s_Bangles_%2B1)
      - [ ] [Dancer's Tiara +1](https://www.bg-wiki.com/ffxi/Dancer%27s_Tiara_%2B1)
      - [ ] [Dancer's Toe Shoes +1](https://www.bg-wiki.com/ffxi/Dancer%27s_Toe_Shoes_%2B1)
      - [ ] [Dancer's Tights +1](https://www.bg-wiki.com/ffxi/Dancer%27s_Tights_%2B1)
      - [ ] [Dancer's Casaque +1](https://www.bg-wiki.com/ffxi/Dancer%27s_Casaque_%2B1)
    - [ ] [Maxixi Attire Set](https://www.bg-wiki.com/ffxi/Maxixi_Attire_Set)
      - [ ] [Maxixi Tiara](https://www.bg-wiki.com/ffxi/Maxixi_Tiara)
      - [ ] [Maxixi Casaque](https://www.bg-wiki.com/ffxi/Maxixi_Casaque)
      - [ ] [Maxixi Bangles](https://www.bg-wiki.com/ffxi/Maxixi_Bangles)
      - [ ] [Maxixi Tights](https://www.bg-wiki.com/ffxi/Maxixi_Tights)
      - [ ] [Maxixi Toeshoes](https://www.bg-wiki.com/ffxi/Maxixi_Toeshoes)
    - [ ] [Maxixi Attire Set +1](https://www.bg-wiki.com/ffxi/Maxixi_Attire_Set_%2B1)
      - [ ] [Maxixi Tiara +1](https://www.bg-wiki.com/ffxi/Maxixi_Tiara_%2B1)
      - [ ] [Maxixi Casaque +1](https://www.bg-wiki.com/ffxi/Maxixi_Casaque_%2B1)
      - [ ] [Maxixi Bangles +1](https://www.bg-wiki.com/ffxi/Maxixi_Bangles_%2B1)
      - [ ] [Maxixi Tights +1](https://www.bg-wiki.com/ffxi/Maxixi_Tights_%2B1)
      - [ ] [Maxixi Toeshoes +1](https://www.bg-wiki.com/ffxi/Maxixi_Toeshoes_%2B1)
    - [ ] [Maxixi Attire Set +2](https://www.bg-wiki.com/ffxi/Maxixi_Attire_Set_%2B2)
      - [ ] [Maxixi Tiara +2](https://www.bg-wiki.com/ffxi/Maxixi_Tiara_%2B2)
      - [ ] [Maxixi Casaque +2](https://www.bg-wiki.com/ffxi/Maxixi_Casaque_%2B2)
      - [ ] [Maxixi Bangles +2](https://www.bg-wiki.com/ffxi/Maxixi_Bangles_%2B2)
      - [ ] [Maxixi Tights +2](https://www.bg-wiki.com/ffxi/Maxixi_Tights_%2B2)
      - [ ] [Maxixi Toeshoes +2](https://www.bg-wiki.com/ffxi/Maxixi_Toeshoes_%2B2)
    - [ ] [Maxixi Attire Set +3](https://www.bg-wiki.com/ffxi/Maxixi_Attire_Set_%2B3)
      - [ ] [Maxixi Tiara +3](https://www.bg-wiki.com/ffxi/Maxixi_Tiara_%2B3)
      - [ ] [Maxixi Casaque +3](https://www.bg-wiki.com/ffxi/Maxixi_Casaque_%2B3)
      - [ ] [Maxixi Bangles +3](https://www.bg-wiki.com/ffxi/Maxixi_Bangles_%2B3)
      - [ ] [Maxixi Tights +3](https://www.bg-wiki.com/ffxi/Maxixi_Tights_%2B3)
      - [ ] [Maxixi Toeshoes +3](https://www.bg-wiki.com/ffxi/Maxixi_Toeshoes_%2B3)
    - [ ] [War Hoop](https://www.bg-wiki.com/ffxi/War_Hoop)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Etoile Attire Set](https://www.bg-wiki.com/ffxi/Etoile_Attire_Set)
      - [ ] [Etoile Bangles](https://www.bg-wiki.com/ffxi/Etoile_Bangles)
      - [ ] [Etoile Tiara](https://www.bg-wiki.com/ffxi/Etoile_Tiara)
      - [ ] [Etoile Toe Shoes](https://www.bg-wiki.com/ffxi/Etoile_Toe_Shoes)
      - [ ] [Etoile Tights](https://www.bg-wiki.com/ffxi/Etoile_Tights)
      - [ ] [Etoile Casaque](https://www.bg-wiki.com/ffxi/Etoile_Casaque)
    - [ ] [Etoile Attire Set +1](https://www.bg-wiki.com/ffxi/Etoile_Attire_Set_%2B1)
      - [ ] [Etoile Bangles +1](https://www.bg-wiki.com/ffxi/Etoile_Bangles_%2B1)
      - [ ] [Etoile Tiara +1](https://www.bg-wiki.com/ffxi/Etoile_Tiara_%2B1)
      - [ ] [Etoile Toe Shoes +1](https://www.bg-wiki.com/ffxi/Etoile_Toe_Shoes_%2B1)
      - [ ] [Etoile Tights +1](https://www.bg-wiki.com/ffxi/Etoile_Tights_%2B1)
      - [ ] [Etoile Casaque +1](https://www.bg-wiki.com/ffxi/Etoile_Casaque_%2B1)
    - [ ] [Etoile Attire Set +2](https://www.bg-wiki.com/ffxi/Etoile_Attire_Set_%2B2)
      - [ ] [Etoile Bangles +2](https://www.bg-wiki.com/ffxi/Etoile_Bangles_%2B2)
      - [ ] [Etoile Tiara +2](https://www.bg-wiki.com/ffxi/Etoile_Tiara_%2B2)
      - [ ] [Etoile Toe Shoes +2](https://www.bg-wiki.com/ffxi/Etoile_Toe_Shoes_%2B2)
      - [ ] [Etoile Tights +2](https://www.bg-wiki.com/ffxi/Etoile_Tights_%2B2)
      - [ ] [Etoile Casaque +2](https://www.bg-wiki.com/ffxi/Etoile_Casaque_%2B2)
    - [ ] [Horos Attire Set](https://www.bg-wiki.com/ffxi/Horos_Attire_Set)
      - [ ] [Horos Tiara](https://www.bg-wiki.com/ffxi/Horos_Tiara)
      - [ ] [Horos Casaque](https://www.bg-wiki.com/ffxi/Horos_Casaque)
      - [ ] [Horos Bangles](https://www.bg-wiki.com/ffxi/Horos_Bangles)
      - [ ] [Horos Tights](https://www.bg-wiki.com/ffxi/Horos_Tights)
      - [ ] [Horos Toe Shoes](https://www.bg-wiki.com/ffxi/Horos_Toe_Shoes)
    - [ ] [Horos Attire Set +1](https://www.bg-wiki.com/ffxi/Horos_Attire_Set_%2B1)
      - [ ] [Horos Tiara +1](https://www.bg-wiki.com/ffxi/Horos_Tiara_%2B1)
      - [ ] [Horos Casaque +1](https://www.bg-wiki.com/ffxi/Horos_Casaque_%2B1)
      - [ ] [Horos Bangles +1](https://www.bg-wiki.com/ffxi/Horos_Bangles_%2B1)
      - [ ] [Horos Tights +1](https://www.bg-wiki.com/ffxi/Horos_Tights_%2B1)
      - [ ] [Horos Toe Shoes +1](https://www.bg-wiki.com/ffxi/Horos_Toe_Shoes_%2B1)
    - [ ] [Horos Attire Set +2](https://www.bg-wiki.com/ffxi/Horos_Attire_Set_%2B2)
      - [ ] [Horos Tiara +2](https://www.bg-wiki.com/ffxi/Horos_Tiara_%2B2)
      - [ ] [Horos Casaque +2](https://www.bg-wiki.com/ffxi/Horos_Casaque_%2B2)
      - [ ] [Horos Bangles +2](https://www.bg-wiki.com/ffxi/Horos_Bangles_%2B2)
      - [ ] [Horos Tights +2](https://www.bg-wiki.com/ffxi/Horos_Tights_%2B2)
      - [ ] [Horos Toe Shoes +2](https://www.bg-wiki.com/ffxi/Horos_Toe_Shoes_%2B2)
    - [ ] [Horos Attire Set +3](https://www.bg-wiki.com/ffxi/Horos_Attire_Set_%2B3)
      - [ ] [Horos Tiara +3](https://www.bg-wiki.com/ffxi/Horos_Tiara_%2B3)
      - [ ] [Horos Casaque +3](https://www.bg-wiki.com/ffxi/Horos_Casaque_%2B3)
      - [ ] [Horos Bangles +3](https://www.bg-wiki.com/ffxi/Horos_Bangles_%2B3)
      - [ ] [Horos Tights +3](https://www.bg-wiki.com/ffxi/Horos_Tights_%2B3)
      - [ ] [Horos Toe Shoes +3](https://www.bg-wiki.com/ffxi/Horos_Toe_Shoes_%2B3)
    - [ ] [Etoile Cape](https://www.bg-wiki.com/ffxi/Etoile_Cape)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Etoile Gorget](https://www.bg-wiki.com/ffxi/Etoile_Gorget)
      - [ ] [Etoile Gorget +1](https://www.bg-wiki.com/ffxi/Etoile_Gorget_%2B1)
      - [ ] [Etoile Gorget +2](https://www.bg-wiki.com/ffxi/Etoile_Gorget_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Etoile Knife](https://www.bg-wiki.com/ffxi/Etoile_Knife)
      - [ ] [Horos Knife](https://www.bg-wiki.com/ffxi/Horos_Knife)
      - [ ] [Setan Kober](https://www.bg-wiki.com/ffxi/Setan_Kober)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Charis Attire Set](https://www.bg-wiki.com/ffxi/Charis_Attire_Set)
      - [ ] [Charis Toe shoes](https://www.bg-wiki.com/ffxi/Charis_Toe_shoes)
      - [ ] [Charis Tights](https://www.bg-wiki.com/ffxi/Charis_Tights)
      - [ ] [Charis Tiara](https://www.bg-wiki.com/ffxi/Charis_Tiara)
      - [ ] [Charis Bangles](https://www.bg-wiki.com/ffxi/Charis_Bangles)
      - [ ] [Charis Casaque](https://www.bg-wiki.com/ffxi/Charis_Casaque)
    - [ ] [Charis Attire Set +1](https://www.bg-wiki.com/ffxi/Charis_Attire_Set_%2B1)
      - [ ] [Charis Toe shoes +1](https://www.bg-wiki.com/ffxi/Charis_Toe_shoes_%2B1)
      - [ ] [Charis Tights +1](https://www.bg-wiki.com/ffxi/Charis_Tights_%2B1)
      - [ ] [Charis Tiara +1](https://www.bg-wiki.com/ffxi/Charis_Tiara_%2B1)
      - [ ] [Charis Bangles +1](https://www.bg-wiki.com/ffxi/Charis_Bangles_%2B1)
      - [ ] [Charis Casaque +1](https://www.bg-wiki.com/ffxi/Charis_Casaque_%2B1)
    - [ ] [Charis Attire Set +2](https://www.bg-wiki.com/ffxi/Charis_Attire_Set_%2B2)
      - [ ] [Charis Toe shoes +2](https://www.bg-wiki.com/ffxi/Charis_Toe_shoes_%2B2)
      - [ ] [Charis Tights +2](https://www.bg-wiki.com/ffxi/Charis_Tights_%2B2)
      - [ ] [Charis Tiara +2](https://www.bg-wiki.com/ffxi/Charis_Tiara_%2B2)
      - [ ] [Charis Bangles +2](https://www.bg-wiki.com/ffxi/Charis_Bangles_%2B2)
      - [ ] [Charis Casaque +2](https://www.bg-wiki.com/ffxi/Charis_Casaque_%2B2)
    - [ ] [Maculele Attire Set](https://www.bg-wiki.com/ffxi/Maculele_Attire_Set)
      - [ ] [Maculele Tiara](https://www.bg-wiki.com/ffxi/Maculele_Tiara)
      - [ ] [Maculele Casaque](https://www.bg-wiki.com/ffxi/Maculele_Casaque)
      - [ ] [Maculele Bangles](https://www.bg-wiki.com/ffxi/Maculele_Bangles)
      - [ ] [Maculele Tights](https://www.bg-wiki.com/ffxi/Maculele_Tights)
      - [ ] [Maculele Toe Shoes](https://www.bg-wiki.com/ffxi/Maculele_Toe_Shoes)
    - [ ] [Maculele Attire Set +1](https://www.bg-wiki.com/ffxi/Maculele_Attire_Set_%2B1)
      - [ ] [Maculele Tiara +1](https://www.bg-wiki.com/ffxi/Maculele_Tiara_%2B1)
      - [ ] [Maculele Casaque +1](https://www.bg-wiki.com/ffxi/Maculele_Casaque_%2B1)
      - [ ] [Maculele Bangles +1](https://www.bg-wiki.com/ffxi/Maculele_Bangles_%2B1)
      - [ ] [Maculele Tights +1](https://www.bg-wiki.com/ffxi/Maculele_Tights_%2B1)
      - [ ] [Maculele Toe Shoes +1](https://www.bg-wiki.com/ffxi/Maculele_Toe_Shoes_%2B1)
    - [ ] [Maculele Attire Set +2](https://www.bg-wiki.com/ffxi/Maculele_Attire_Set_%2B2)
      - [ ] [Maculele Tiara +2](https://www.bg-wiki.com/ffxi/Maculele_Tiara_%2B2)
      - [ ] [Maculele Casaque +2](https://www.bg-wiki.com/ffxi/Maculele_Casaque_%2B2)
      - [ ] [Maculele Bangles +2](https://www.bg-wiki.com/ffxi/Maculele_Bangles_%2B2)
      - [ ] [Maculele Tights +2](https://www.bg-wiki.com/ffxi/Maculele_Tights_%2B2)
      - [ ] [Maculele Toe Shoes +2](https://www.bg-wiki.com/ffxi/Maculele_Toe_Shoes_%2B2)
    - [ ] [Maculele Attire Set +3](https://www.bg-wiki.com/ffxi/Maculele_Attire_Set_%2B3)
      - [ ] [Maculele Tiara +3](https://www.bg-wiki.com/ffxi/Maculele_Tiara_%2B3)
      - [ ] [Maculele Casaque +3](https://www.bg-wiki.com/ffxi/Maculele_Casaque_%2B3)
      - [ ] [Maculele Bangles +3](https://www.bg-wiki.com/ffxi/Maculele_Bangles_%2B3)
      - [ ] [Maculele Tights +3](https://www.bg-wiki.com/ffxi/Maculele_Tights_%2B3)
      - [ ] [Maculele Toe Shoes +3](https://www.bg-wiki.com/ffxi/Maculele_Toe_Shoes_%2B3)
    - [ ] Accessories
      - [ ] [Charis Necklace](https://www.bg-wiki.com/ffxi/Charis_Necklace)
      - [ ] [Charis Feather](https://www.bg-wiki.com/ffxi/Charis_Feather)
      - [ ] [Charis Earring](https://www.bg-wiki.com/ffxi/Charis_Earring)
      - [ ] [Maculele Earring](https://www.bg-wiki.com/ffxi/Maculele_Earring)
      - [ ] [Maculele Earring +1](https://www.bg-wiki.com/ffxi/Maculele_Earring_%2B1)
      - [ ] [Maculele Earring +2](https://www.bg-wiki.com/ffxi/Maculele_Earring_%2B2)
