### ISSUE TITLE
SCH JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4409]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [SCH](https://www.bg-wiki.com/ffxi/Scholar)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [ ] [Scholar's Attire Set](https://www.bg-wiki.com/ffxi/Scholar%27s_Attire_Set)
      - [ ] [Scholar's Bracers](https://www.bg-wiki.com/ffxi/Scholar%27s_Bracers)
      - [ ] [Scholar's Loafers](https://www.bg-wiki.com/ffxi/Scholar%27s_Loafers)
      - [ ] [Scholar's Pants](https://www.bg-wiki.com/ffxi/Scholar%27s_Pants)
      - [ ] [Scholar's Gown](https://www.bg-wiki.com/ffxi/Scholar%27s_Gown)
      - [ ] [Scholar's Mortarboard](https://www.bg-wiki.com/ffxi/Scholar%27s_Mortarboard)
    - [ ] [Scholar's Attire Set +1](https://www.bg-wiki.com/ffxi/Scholar%27s_Attire_Set_%2B1)
      - [ ] [Scholar's Bracers +1](https://www.bg-wiki.com/ffxi/Scholar%27s_Bracers_%2B1)
      - [ ] [Scholar's Loafers +1](https://www.bg-wiki.com/ffxi/Scholar%27s_Loafers_%2B1)
      - [ ] [Scholar's Pants +1](https://www.bg-wiki.com/ffxi/Scholar%27s_Pants_%2B1)
      - [ ] [Scholar's Gown +1](https://www.bg-wiki.com/ffxi/Scholar%27s_Gown_%2B1)
      - [ ] [Scholar's Mortarboard +1](https://www.bg-wiki.com/ffxi/Scholar%27s_Mortarboard_%2B1)
    - [ ] [Academic's Attire Set](https://www.bg-wiki.com/ffxi/Academic%27s_Attire_Set)
      - [ ] [Academic's Mortarboard](https://www.bg-wiki.com/ffxi/Academic%27s_Mortarboard)
      - [ ] [Academic's Gown](https://www.bg-wiki.com/ffxi/Academic%27s_Gown)
      - [ ] [Academic's Bracers](https://www.bg-wiki.com/ffxi/Academic%27s_Bracers)
      - [ ] [Academic's Pants](https://www.bg-wiki.com/ffxi/Academic%27s_Pants)
      - [ ] [Academic's Loafers](https://www.bg-wiki.com/ffxi/Academic%27s_Loafers)
    - [ ] [Academic's Attire Set +1](https://www.bg-wiki.com/ffxi/Academic%27s_Attire_Set_%2B1)
      - [ ] [Academic's Mortarboard +1](https://www.bg-wiki.com/ffxi/Academic%27s_Mortarboard_%2B1)
      - [ ] [Academic's Gown +1](https://www.bg-wiki.com/ffxi/Academic%27s_Gown_%2B1)
      - [ ] [Academic's Bracers +1](https://www.bg-wiki.com/ffxi/Academic%27s_Bracers_%2B1)
      - [ ] [Academic's Pants +1](https://www.bg-wiki.com/ffxi/Academic%27s_Pants_%2B1)
      - [ ] [Academic's Loafers +1](https://www.bg-wiki.com/ffxi/Academic%27s_Loafers_%2B1)
    - [ ] [Academic's Attire Set +2](https://www.bg-wiki.com/ffxi/Academic%27s_Attire_Set_%2B2)
      - [ ] [Academic's Mortarboard +2](https://www.bg-wiki.com/ffxi/Academic%27s_Mortarboard_%2B2)
      - [ ] [Academic's Gown +2](https://www.bg-wiki.com/ffxi/Academic%27s_Gown_%2B2)
      - [ ] [Academic's Bracers +2](https://www.bg-wiki.com/ffxi/Academic%27s_Bracers_%2B2)
      - [ ] [Academic's Pants +2](https://www.bg-wiki.com/ffxi/Academic%27s_Pants_%2B2)
      - [ ] [Academic's Loafers +2](https://www.bg-wiki.com/ffxi/Academic%27s_Loafers_%2B2)
    - [ ] [Academic's Attire Set +3](https://www.bg-wiki.com/ffxi/Academic%27s_Attire_Set_%2B3)
      - [ ] [Academic's Mortarboard +3](https://www.bg-wiki.com/ffxi/Academic%27s_Mortarboard_%2B3)
      - [ ] [Academic's Gown +3](https://www.bg-wiki.com/ffxi/Academic%27s_Gown_%2B3)
      - [ ] [Academic's Bracers +3](https://www.bg-wiki.com/ffxi/Academic%27s_Bracers_%2B3)
      - [ ] [Academic's Pants +3](https://www.bg-wiki.com/ffxi/Academic%27s_Pants_%2B3)
      - [ ] [Academic's Loafers +3](https://www.bg-wiki.com/ffxi/Academic%27s_Loafers_%2B3)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Argute Attire Set](https://www.bg-wiki.com/ffxi/Argute_Attire_Set)
      - [ ] [Argute Bracers](https://www.bg-wiki.com/ffxi/Argute_Bracers)
      - [ ] [Argute Loafers](https://www.bg-wiki.com/ffxi/Argute_Loafers)
      - [ ] [Argute Pants](https://www.bg-wiki.com/ffxi/Argute_Pants)
      - [ ] [Argute Gown](https://www.bg-wiki.com/ffxi/Argute_Gown)
      - [ ] [Argute Mortarboard](https://www.bg-wiki.com/ffxi/Argute_Mortarboard)
    - [ ] [Argute Attire Set +1](https://www.bg-wiki.com/ffxi/Argute_Attire_Set_%2B1)
      - [ ] [Argute Bracers +1](https://www.bg-wiki.com/ffxi/Argute_Bracers_%2B1)
      - [ ] [Argute Loafers +1](https://www.bg-wiki.com/ffxi/Argute_Loafers_%2B1)
      - [ ] [Argute Pants +1](https://www.bg-wiki.com/ffxi/Argute_Pants_%2B1)
      - [ ] [Argute Gown +1](https://www.bg-wiki.com/ffxi/Argute_Gown_%2B1)
      - [ ] [Argute Mortarboard +1](https://www.bg-wiki.com/ffxi/Argute_Mortarboard_%2B1)
    - [ ] [Argute Attire Set +2](https://www.bg-wiki.com/ffxi/Argute_Attire_Set_%2B2)
      - [ ] [Argute Bracers +2](https://www.bg-wiki.com/ffxi/Argute_Bracers_%2B2)
      - [ ] [Argute Loafers +2](https://www.bg-wiki.com/ffxi/Argute_Loafers_%2B2)
      - [ ] [Argute Pants +2](https://www.bg-wiki.com/ffxi/Argute_Pants_%2B2)
      - [ ] [Argute Gown +2](https://www.bg-wiki.com/ffxi/Argute_Gown_%2B2)
      - [ ] [Argute Mortarboard +2](https://www.bg-wiki.com/ffxi/Argute_Mortarboard_%2B2)
    - [ ] [Pedagogy Attire Set](https://www.bg-wiki.com/ffxi/Pedagogy_Attire_Set)
      - [ ] [Pedagogy Mortarboard](https://www.bg-wiki.com/ffxi/Pedagogy_Mortarboard)
      - [ ] [Pedagogy Gown](https://www.bg-wiki.com/ffxi/Pedagogy_Gown)
      - [ ] [Pedagogy Bracers](https://www.bg-wiki.com/ffxi/Pedagogy_Bracers)
      - [ ] [Pedagogy Pants](https://www.bg-wiki.com/ffxi/Pedagogy_Pants)
      - [ ] [Pedagogy Loafers](https://www.bg-wiki.com/ffxi/Pedagogy_Loafers)
    - [ ] [Pedagogy Attire Set +1](https://www.bg-wiki.com/ffxi/Pedagogy_Attire_Set_%2B1)
      - [ ] [Pedagogy Mortarboard +1](https://www.bg-wiki.com/ffxi/Pedagogy_Mortarboard_%2B1)
      - [ ] [Pedagogy Gown +1](https://www.bg-wiki.com/ffxi/Pedagogy_Gown_%2B1)
      - [ ] [Pedagogy Bracers +1](https://www.bg-wiki.com/ffxi/Pedagogy_Bracers_%2B1)
      - [ ] [Pedagogy Pants +1](https://www.bg-wiki.com/ffxi/Pedagogy_Pants_%2B1)
      - [ ] [Pedagogy Loafers +1](https://www.bg-wiki.com/ffxi/Pedagogy_Loafers_%2B1)
    - [ ] [Pedagogy Attire Set +2](https://www.bg-wiki.com/ffxi/Pedagogy_Attire_Set_%2B2)
      - [ ] [Pedagogy Mortarboard +2](https://www.bg-wiki.com/ffxi/Pedagogy_Mortarboard_%2B2)
      - [ ] [Pedagogy Gown +2](https://www.bg-wiki.com/ffxi/Pedagogy_Gown_%2B2)
      - [ ] [Pedagogy Bracers +2](https://www.bg-wiki.com/ffxi/Pedagogy_Bracers_%2B2)
      - [ ] [Pedagogy Pants +2](https://www.bg-wiki.com/ffxi/Pedagogy_Pants_%2B2)
      - [ ] [Pedagogy Loafers +2](https://www.bg-wiki.com/ffxi/Pedagogy_Loafers_%2B2)
    - [ ] [Pedagogy Attire Set +3](https://www.bg-wiki.com/ffxi/Pedagogy_Attire_Set_%2B3)
      - [ ] [Pedagogy Mortarboard +3](https://www.bg-wiki.com/ffxi/Pedagogy_Mortarboard_%2B3)
      - [ ] [Pedagogy Gown +3](https://www.bg-wiki.com/ffxi/Pedagogy_Gown_%2B3)
      - [ ] [Pedagogy Bracers +3](https://www.bg-wiki.com/ffxi/Pedagogy_Bracers_%2B3)
      - [ ] [Pedagogy Pants +3](https://www.bg-wiki.com/ffxi/Pedagogy_Pants_%2B3)
      - [ ] [Pedagogy Loafers +3](https://www.bg-wiki.com/ffxi/Pedagogy_Loafers_%2B3)
    - [ ] [Argute Belt](https://www.bg-wiki.com/ffxi/Argute_Belt)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Argute Stole](https://www.bg-wiki.com/ffxi/Argute_Stole)
      - [ ] [Argute Stole +1](https://www.bg-wiki.com/ffxi/Argute_Stole_%2B1)
      - [ ] [Argute Stole +2](https://www.bg-wiki.com/ffxi/Argute_Stole_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Argute Staff](https://www.bg-wiki.com/ffxi/Argute_Staff)
      - [ ] [Pedagogy Staff](https://www.bg-wiki.com/ffxi/Pedagogy_Staff)
      - [ ] [Musa](https://www.bg-wiki.com/ffxi/Musa)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Savant's Attire Set](https://www.bg-wiki.com/ffxi/Savant%27s_Attire_Set)
      - [ ] [Savant's Loafers](https://www.bg-wiki.com/ffxi/Savant%27s_Loafers)
      - [ ] [Savant's Pants](https://www.bg-wiki.com/ffxi/Savant%27s_Pants)
      - [ ] [Savant's Bonnet](https://www.bg-wiki.com/ffxi/Savant%27s_Bonnet)
      - [ ] [Savant's Bracers](https://www.bg-wiki.com/ffxi/Savant%27s_Bracers)
      - [ ] [Savant's Gown](https://www.bg-wiki.com/ffxi/Savant%27s_Gown)
    - [ ] [Savant's Attire Set +1](https://www.bg-wiki.com/ffxi/Savant%27s_Attire_Set_%2B1)
      - [ ] [Savant's Loafers +1](https://www.bg-wiki.com/ffxi/Savant%27s_Loafers_%2B1)
      - [ ] [Savant's Pants +1](https://www.bg-wiki.com/ffxi/Savant%27s_Pants_%2B1)
      - [ ] [Savant's Bonnet +1](https://www.bg-wiki.com/ffxi/Savant%27s_Bonnet_%2B1)
      - [ ] [Savant's Bracers +1](https://www.bg-wiki.com/ffxi/Savant%27s_Bracers_%2B1)
      - [ ] [Savant's Gown +1](https://www.bg-wiki.com/ffxi/Savant%27s_Gown_%2B1)
    - [ ] [Savant's Attire Set +2](https://www.bg-wiki.com/ffxi/Savant%27s_Attire_Set_%2B2)
      - [ ] [Savant's Loafers +2](https://www.bg-wiki.com/ffxi/Savant%27s_Loafers_%2B2)
      - [ ] [Savant's Pants +2](https://www.bg-wiki.com/ffxi/Savant%27s_Pants_%2B2)
      - [ ] [Savant's Bonnet +2](https://www.bg-wiki.com/ffxi/Savant%27s_Bonnet_%2B2)
      - [ ] [Savant's Bracers +2](https://www.bg-wiki.com/ffxi/Savant%27s_Bracers_%2B2)
      - [ ] [Savant's Gown +2](https://www.bg-wiki.com/ffxi/Savant%27s_Gown_%2B2)
    - [ ] [Arbatel Attire Set](https://www.bg-wiki.com/ffxi/Arbatel_Attire_Set)
      - [ ] [Arbatel Bonnet](https://www.bg-wiki.com/ffxi/Arbatel_Bonnet)
      - [ ] [Arbatel Gown](https://www.bg-wiki.com/ffxi/Arbatel_Gown)
      - [ ] [Arbatel Bracers](https://www.bg-wiki.com/ffxi/Arbatel_Bracers)
      - [ ] [Arbatel Pants](https://www.bg-wiki.com/ffxi/Arbatel_Pants)
      - [ ] [Arbatel Loafers](https://www.bg-wiki.com/ffxi/Arbatel_Loafers)
    - [ ] [Arbatel Attire Set +1](https://www.bg-wiki.com/ffxi/Arbatel_Attire_Set_%2B1)
      - [ ] [Arbatel Bonnet +1](https://www.bg-wiki.com/ffxi/Arbatel_Bonnet_%2B1)
      - [ ] [Arbatel Gown +1](https://www.bg-wiki.com/ffxi/Arbatel_Gown_%2B1)
      - [ ] [Arbatel Bracers +1](https://www.bg-wiki.com/ffxi/Arbatel_Bracers_%2B1)
      - [ ] [Arbatel Pants +1](https://www.bg-wiki.com/ffxi/Arbatel_Pants_%2B1)
      - [ ] [Arbatel Loafers +1](https://www.bg-wiki.com/ffxi/Arbatel_Loafers_%2B1)
    - [ ] [Arbatel Attire Set +2](https://www.bg-wiki.com/ffxi/Arbatel_Attire_Set_%2B2)
      - [ ] [Arbatel Bonnet +2](https://www.bg-wiki.com/ffxi/Arbatel_Bonnet_%2B2)
      - [ ] [Arbatel Gown +2](https://www.bg-wiki.com/ffxi/Arbatel_Gown_%2B2)
      - [ ] [Arbatel Bracers +2](https://www.bg-wiki.com/ffxi/Arbatel_Bracers_%2B2)
      - [ ] [Arbatel Pants +2](https://www.bg-wiki.com/ffxi/Arbatel_Pants_%2B2)
      - [ ] [Arbatel Loafers +2](https://www.bg-wiki.com/ffxi/Arbatel_Loafers_%2B2)
    - [ ] [Arbatel Attire Set +3](https://www.bg-wiki.com/ffxi/Arbatel_Attire_Set_%2B3)
      - [ ] [Arbatel Bonnet +3](https://www.bg-wiki.com/ffxi/Arbatel_Bonnet_%2B3)
      - [ ] [Arbatel Gown +3](https://www.bg-wiki.com/ffxi/Arbatel_Gown_%2B3)
      - [ ] [Arbatel Bracers +3](https://www.bg-wiki.com/ffxi/Arbatel_Bracers_%2B3)
      - [ ] [Arbatel Pants +3](https://www.bg-wiki.com/ffxi/Arbatel_Pants_%2B3)
      - [ ] [Arbatel Loafers +3](https://www.bg-wiki.com/ffxi/Arbatel_Loafers_%2B3)
    - [ ] Accessories
      - [ ] [Savant's Treatise](https://www.bg-wiki.com/ffxi/Savant%27s_Treatise)
      - [ ] [Savant's Chain](https://www.bg-wiki.com/ffxi/Savant%27s_Chain)
      - [ ] [Savant's Earring](https://www.bg-wiki.com/ffxi/Savant%27s_Earring)
      - [ ] [Arbatel Earring](https://www.bg-wiki.com/ffxi/Arbatel_Earring)
      - [ ] [Arbatel Earring +1](https://www.bg-wiki.com/ffxi/Arbatel_Earring_%2B1)
      - [ ] [Arbatel Earring +2](https://www.bg-wiki.com/ffxi/Arbatel_Earring_%2B2)
