### ISSUE TITLE
GEO JSE completeness tracker

### ISSUE THREAD

**Issue by helixhamin** [DerpyProjectGroup/topaz#4410]
Please note, this will not include method to obtain the JSE, only that the JSE is usable, has the right stats, etc.

- [ ] [GEO](https://www.bg-wiki.com/ffxi/Geomancer)
  - [ ] [Artifact Armor](https://www.bg-wiki.com/ffxi/Artifact_Armor)
    - [x] [Geomancy Attire Set](https://www.bg-wiki.com/ffxi/Geomancy_Attire_Set)
      - [x] [Geomancy Galero](https://www.bg-wiki.com/ffxi/Geomancy_Galero)
      - [x] [Geomancy Tunic](https://www.bg-wiki.com/ffxi/Geomancy_Tunic)
      - [x] [Geomancy Mitaines](https://www.bg-wiki.com/ffxi/Geomancy_Mitaines)
      - [x] [Geomancy Pants](https://www.bg-wiki.com/ffxi/Geomancy_Pants)
      - [x] [Geomancy Sandals](https://www.bg-wiki.com/ffxi/Geomancy_Sandals)
    - [x] [Geomancy Attire Set +1](https://www.bg-wiki.com/ffxi/Geomancy_Attire_Set_%2B1)
      - [x] [Geomancy Galero +1](https://www.bg-wiki.com/ffxi/Geomancy_Galero_%2B1)
      - [x] [Geomancy Tunic +1](https://www.bg-wiki.com/ffxi/Geomancy_Tunic_%2B1)
      - [x] [Geomancy Mitaines +1](https://www.bg-wiki.com/ffxi/Geomancy_Mitaines_%2B1)
      - [x] [Geomancy Pants +1](https://www.bg-wiki.com/ffxi/Geomancy_Pants_%2B1)
      - [x] [Geomancy Sandals +1](https://www.bg-wiki.com/ffxi/Geomancy_Sandals_%2B1)
    - [ ] [Geomancy Attire Set +2](https://www.bg-wiki.com/ffxi/Geomancy_Attire_Set_%2B2)
      - [ ] [Geomancy Galero +2](https://www.bg-wiki.com/ffxi/Geomancy_Galero_%2B2)
      - [ ] [Geomancy Tunic +2](https://www.bg-wiki.com/ffxi/Geomancy_Tunic_%2B2)
      - [ ] [Geomancy Mitaines +2](https://www.bg-wiki.com/ffxi/Geomancy_Mitaines_%2B2)
      - [ ] [Geomancy Pants +2](https://www.bg-wiki.com/ffxi/Geomancy_Pants_%2B2)
      - [ ] [Geomancy Sandals +2](https://www.bg-wiki.com/ffxi/Geomancy_Sandals_%2B2)
    - [ ] [Geomancy Attire Set +3](https://www.bg-wiki.com/ffxi/Geomancy_Attire_Set_%2B3)
      - [ ] [Geomancy Galero +3](https://www.bg-wiki.com/ffxi/Geomancy_Galero_%2B3)
      - [ ] [Geomancy Tunic +3](https://www.bg-wiki.com/ffxi/Geomancy_Tunic_%2B3)
      - [ ] [Geomancy Mitaines +3](https://www.bg-wiki.com/ffxi/Geomancy_Mitaines_%2B3)
      - [ ] [Geomancy Pants +3](https://www.bg-wiki.com/ffxi/Geomancy_Pants_%2B3)
      - [ ] [Geomancy Sandals +3](https://www.bg-wiki.com/ffxi/Geomancy_Sandals_%2B3)
    - [ ] [Dowser's Wand](https://www.bg-wiki.com/ffxi/Dowser%27s_Wand)
    - [ ] [Filiae Bell](https://www.bg-wiki.com/ffxi/Filiae_Bell)
  - [ ] [Relic Armor](https://www.bg-wiki.com/ffxi/Relic_Armor)
    - [ ] [Bagua Attire Set](https://www.bg-wiki.com/ffxi/Bagua_Attire_Set)
      - [ ] [Bagua Galero](https://www.bg-wiki.com/ffxi/Bagua_Galero)
      - [ ] [Bagua Tunic](https://www.bg-wiki.com/ffxi/Bagua_Tunic)
      - [ ] [Bagua Mitaines](https://www.bg-wiki.com/ffxi/Bagua_Mitaines)
      - [ ] [Bagua Pants](https://www.bg-wiki.com/ffxi/Bagua_Pants)
      - [ ] [Bagua Sandals](https://www.bg-wiki.com/ffxi/Bagua_Sandals)
    - [ ] [Bagua Attire Set +1](https://www.bg-wiki.com/ffxi/Bagua_Attire_Set_%2B1)
      - [ ] [Bagua Galero +1](https://www.bg-wiki.com/ffxi/Bagua_Galero_%2B1)
      - [ ] [Bagua Tunic +1](https://www.bg-wiki.com/ffxi/Bagua_Tunic_%2B1)
      - [ ] [Bagua Mitaines +1](https://www.bg-wiki.com/ffxi/Bagua_Mitaines_%2B1)
      - [ ] [Bagua Pants +1](https://www.bg-wiki.com/ffxi/Bagua_Pants_%2B1)
      - [ ] [Bagua Sandals +1](https://www.bg-wiki.com/ffxi/Bagua_Sandals_%2B1)
    - [ ] [Bagua Attire Set +2](https://www.bg-wiki.com/ffxi/Bagua_Attire_Set_%2B2)
      - [ ] [Bagua Galero +2](https://www.bg-wiki.com/ffxi/Bagua_Galero_%2B2)
      - [ ] [Bagua Tunic +2](https://www.bg-wiki.com/ffxi/Bagua_Tunic_%2B2)
      - [ ] [Bagua Mitaines +2](https://www.bg-wiki.com/ffxi/Bagua_Mitaines_%2B2)
      - [ ] [Bagua Pants +2](https://www.bg-wiki.com/ffxi/Bagua_Pants_%2B2)
      - [ ] [Bagua Sandals +2](https://www.bg-wiki.com/ffxi/Bagua_Sandals_%2B2)
    - [ ] [Bagua Attire Set +3](https://www.bg-wiki.com/ffxi/Bagua_Attire_Set_%2B3)
      - [ ] [Bagua Galero +3](https://www.bg-wiki.com/ffxi/Bagua_Galero_%2B3)
      - [ ] [Bagua Tunic +3](https://www.bg-wiki.com/ffxi/Bagua_Tunic_%2B3)
      - [ ] [Bagua Mitaines +3](https://www.bg-wiki.com/ffxi/Bagua_Mitaines_%2B3)
      - [ ] [Bagua Pants +3](https://www.bg-wiki.com/ffxi/Bagua_Pants_%2B3)
      - [ ] [Bagua Sandals +3](https://www.bg-wiki.com/ffxi/Bagua_Sandals_%2B3)
    - [ ] [JSE Neck](https://www.bg-wiki.com/ffxi/JSE_Necks)
      - [ ] [Bagua Charm](https://www.bg-wiki.com/ffxi/Bagua_Charm)
      - [ ] [Bagua Charm +1](https://www.bg-wiki.com/ffxi/Bagua_Charm_%2B1)
      - [ ] [Bagua Charm +2](https://www.bg-wiki.com/ffxi/Bagua_Charm_%2B2)
    - [ ] [Divergence Weapon](https://www.bg-wiki.com/ffxi/Dynamis_Divergence_Weapon_Augments)
      - [ ] [Bagua Wand](https://www.bg-wiki.com/ffxi/Bagua_Wand)
      - [ ] [Sifang Wand](https://www.bg-wiki.com/ffxi/Sifang_Wand)
      - [ ] [Bhima](https://www.bg-wiki.com/ffxi/Bhima)
  - [ ] [Empyrean Armor](https://www.bg-wiki.com/ffxi/Empyrean_Armor)
    - [ ] [Azimuth Attire Set](https://www.bg-wiki.com/ffxi/Azimuth_Attire_Set)
      - [ ] [Azimuth Hood](https://www.bg-wiki.com/ffxi/Azimuth_Hood)
      - [ ] [Azimuth Coat](https://www.bg-wiki.com/ffxi/Azimuth_Coat)
      - [ ] [Azimuth Gloves](https://www.bg-wiki.com/ffxi/Azimuth_Gloves)
      - [ ] [Azimuth Tights](https://www.bg-wiki.com/ffxi/Azimuth_Tights)
      - [ ] [Azimuth Gaiters](https://www.bg-wiki.com/ffxi/Azimuth_Gaiters)
    - [ ] [Azimuth Attire Set +1](https://www.bg-wiki.com/ffxi/Azimuth_Attire_Set_%2B1)
      - [ ] [Azimuth Hood +1](https://www.bg-wiki.com/ffxi/Azimuth_Hood_%2B1)
      - [ ] [Azimuth Coat +1](https://www.bg-wiki.com/ffxi/Azimuth_Coat_%2B1)
      - [ ] [Azimuth Gloves +1](https://www.bg-wiki.com/ffxi/Azimuth_Gloves_%2B1)
      - [ ] [Azimuth Tights +1](https://www.bg-wiki.com/ffxi/Azimuth_Tights_%2B1)
      - [ ] [Azimuth Gaiters +1](https://www.bg-wiki.com/ffxi/Azimuth_Gaiters_%2B1)
    - [ ] [Azimuth Attire Set +2](https://www.bg-wiki.com/ffxi/Azimuth_Attire_Set_%2B2)
      - [ ] [Azimuth Hood +2](https://www.bg-wiki.com/ffxi/Azimuth_Hood_%2B2)
      - [ ] [Azimuth Coat +2](https://www.bg-wiki.com/ffxi/Azimuth_Coat_%2B2)
      - [ ] [Azimuth Gloves +2](https://www.bg-wiki.com/ffxi/Azimuth_Gloves_%2B2)
      - [ ] [Azimuth Tights +2](https://www.bg-wiki.com/ffxi/Azimuth_Tights_%2B2)
      - [ ] [Azimuth Gaiters +2](https://www.bg-wiki.com/ffxi/Azimuth_Gaiters_%2B2)
    - [ ] [Azimuth Attire Set +3](https://www.bg-wiki.com/ffxi/Azimuth_Attire_Set_%2B3)
      - [ ] [Azimuth Hood +3](https://www.bg-wiki.com/ffxi/Azimuth_Hood_%2B3)
      - [ ] [Azimuth Coat +3](https://www.bg-wiki.com/ffxi/Azimuth_Coat_%2B3)
      - [ ] [Azimuth Gloves +3](https://www.bg-wiki.com/ffxi/Azimuth_Gloves_%2B3)
      - [ ] [Azimuth Tights +3](https://www.bg-wiki.com/ffxi/Azimuth_Tights_%2B3)
      - [ ] [Azimuth Gaiters +3](https://www.bg-wiki.com/ffxi/Azimuth_Gaiters_%2B3)
    - [ ] Accessories
      - [ ] [Azimuth Earring](https://www.bg-wiki.com/ffxi/Azimuth_Earring)
      - [ ] [Azimuth Earring +1](https://www.bg-wiki.com/ffxi/Azimuth_Earring_%2B1)
      - [ ] [Azimuth Earring +2](https://www.bg-wiki.com/ffxi/Azimuth_Earring_%2B2)
