### ISSUE TITLE
Todo: url's in project md files

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#5]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/DerpyProjectGroup/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/DerpyProjectGroup/topaz/blob/release/CONTRIBUTING.md)
- [x] I have specified what branch this happens on: ALL

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Right now, all the links point at files in the old repo...this will be a rare case where the work happens in the topaz branch and then goes out to the other branches.

**Comment by TeoTwawki** [comment]
ignore info branch.

**Comment by TeoTwawki** [comment]
#815
