### ISSUE TITLE
Moh Gates III RoE tracking Writhing Obdella instead of Ferocious Funguar

### ISSUE THREAD

**Issue by RAIST5150** [DerpyProjectGroup/topaz#576]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Everything Branch
**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Canaria, Everything Branch
Client version 30210706_0

The room where F-G/10-11 squares meet is full of the Ferocious Funguar (accessible only from the western entrance because we can't climb vines yet)--but none of them track for the RoE objective.

Killed the Writhing Obdella leeches at H-9/I-9 and they counted for the objective

![Moh_Gates_III](https://user-images.githubusercontent.com/73744368/128111757-3614dd54-62d6-469a-b58b-d53ed552fb69.jpg)
