### ISSUE TITLE
[TODO] Ensure that SetWeather is called exactly once when a zone wakes up

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#877]
As discussed during https://github.com/LandSandBoat/server/pull/786

There is NPC/Mob hiding/showing logic that relies on the weather being correct. I'm not sure if we can guarantee that the starting weather for a zone is correct when it wakes up.

It doesn't seem to be as simple as just calling `CZone::UpdateWeather()` as that enqueues another task with the same weather update name, and there doesn't appear to be any de-dupe logic to stop tasks from getting doubled up. 

- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
